- build.sh
command -v is specified by POSIX and should
be more portable than hash.
Fixes build with ksh(1) on OpenBSD.
Idea for using "command" utility from
http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
and here a link to the posix specification:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html
This fixes issue https://github.com/Valloric/YouCompleteMe/issues/1320
> replace "hash" with "command -v"

- ycmd/completers/cs/cs_completer.py
- ycmd/default_settings.json
I saw this issue: 
https://github.com/Valloric/YouCompleteMe/issues/802
Obviously, two completion plugins active at the same time is a bad idea, but Omnisharp has functionality that isn't exposed in YCM (e.g. refactoring tools, find usages of a symbol, etc.). With this change, YCM will start the Omnisharp server listening on a fixed port. This value is already being set to 2000 (where Omnisharp's vim plugin expects the server) in default_settings.json, but was not being used by anything.
I've signed the CLA.
> Use the omnisharp port specified in user_options

- build.py
This PR fix the following error in a rare case where Python 2.6 is system default:
```
RAN: '/usr/bin/python -c import sys;i=sys.version_info;print "python%d.%d" % (i.major, i.minor)'
STDOUT:
STDERR:
File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
```
---
CLA signed.
> Fix CustomPythonCmakeArgs() on Python 2.6

- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- cpp/ycm/ClangCompleter/ClangCompleter.h
- cpp/ycm/ClangCompleter/ClangUtils.h
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.h
- cpp/ycm/ycm_core.cpp
- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/GetParent_Clang_test.cc
- ycmd/tests/testdata/GetType_Clang_test.cc
- ycmd/tests/testdata/GoTo_Clang_ZeroBasedLineAndColumn_test.cc
- ycmd/tests/testdata/GoTo_all_Clang_test.cc
GetType - returns the type of the word at a specific location. This is used by
YouCompleteMe and echo'd in vim. Where the canonical type (the "derived" type,
e.g. for a typedef) is different from the declared type, that is also returned,
separated with " => ".
GetParent - returns the semantic parent of the word at a specific location.
This is also echo'd in vim by YouCompleteMe.
One other change was required to satisty the cylomatic complexity check in the
test suite: the  if:elif: pattern in OnUserCommand was changed to a pythonic
switch (a dictionary)
see also https://github.com/Valloric/ycmd/pull/87 for details and history.
> New completer subcommands GetType and GetParent

- run_tests.sh
- ycmd/tests/test_utils.py
Enhance test suite
Update run_tests.sh to allow arguments to be passed directly to "nosetests".
This allows developers to run specific test scripts or specific test methods.
Ensure also that the test suite does not hang forever when problems with, say,
the installation cause OmniSharpServer to fail to start. Instead timeout after
20s.
> Enhance test suite

- build.py
Currently, build.py only pipes the make's stdout to its stdout. The stderr
is included in the exception output, but truncated. The lack of full
stderr for make causes difficulty debugging make issues.
> Change build.py to also pipe the make's stderr

- ycmd/completers/completer_utils.py
- ycmd/completers/completer_utils_test.py
Related to Valloric/YouCompleteMe#84.
With these additions, triggers for Objective-C semantic completion behave like Xcode.  This should be a sensible default because 99% of Objective-C developers are going to be used to Xcode.
I added both positive and negative unit tests for every case I could think of and thoroughly tested it by hand in a real project.  All unit tests pass. It works very well!
All of the syntax situations presented [here](http://clang.llvm.org/docs/ObjectiveCLiterals.html) are covered. 
Without these changes, Objective-C semantic triggering is unusable.  It fails to trigger in 90% of the cases a developer will expect it.
> Improve Objective-C semantic completion triggering

- cpp/ycm/ClangCompleter/CompletionData.cpp
- cpp/ycm/ClangCompleter/CompletionData.h
- cpp/ycm/tests/ClangCompleter/ClangCompleter_test.cpp
- cpp/ycm/tests/testdata/SWObject.h
- cpp/ycm/tests/testdata/SWObject.m
> when completing multi-param in objective-c files, the origin implementation only
> completed the last param. this commit fixed it. it will complete the first param,
> then after the user input param, call completion again to get second param, and
> so on.
> it also support completing declared methods or inherited methods. the user can
> call the completion after input '+ ' or '- '
here I fixed objective-c support in ycm. I have used it for months. 
I think a good support for objective-c can earn more iOS & MAC developers. 
Relative Issue: [YouCompleteMe #1221](https://github.com/Valloric/YouCompleteMe/issues/1221)
here is a preview:
(I already sign **Google Contributor License Agreement**)
> fixed complete in objective-c.

- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/tests/gocode_completer_test.py
`gocode` also returns `class` information for candidate. Add this to `detailed_info`
I have read and signed the Google CLA.
> Add additionial class information to gocode completion data

- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/tests/flags_test.py
-Xclang flags are typically not used in the front-end, so they shouldn't affect anything that we care about for code completion.
Some background on why I made this change: I was trying to get YCM to work on the Mozilla code base.  We use a clang plugin to perform some static analysis checks when building our code.  When ycmd tries to use libclang, libclang fails to load the plugin so semantic code completion doesn't work.
When I was thinking about how to fix this, we realized that we should just ignore -Xclang options, since they are intended for cc1, which means they usually affect code generation but not syntax parsing and AST generation, which is all we need from libclang for code completion.
> Blacklist -Xclang flags for C/C++ completion

- run_tests.sh
The clang case has [] - the no clang case should too.
I've already signed the CLA.
> Fix run_tests.sh for no clang case

- ycmd/completers/python/jedi_completer.py
- ycmd/tests/get_completions_test.py
jedi provides the location of the completion candidate as `line` and `path`. In `company-ycmd` for Emacs this information can be used to jump to the location while completion popup is open.
I have read and signed the Google CLA
> Add path and line to python completion data

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/testy/GetTypeTestCase.cs
- ycmd/tests/testdata/testy/TypeLookupTestCase.cs
- ycmd/tests/testdata/testy/testy.csproj
This command displays documentation on the type under the cursor.
This is the command I was using in the screenshot in  https://github.com/Valloric/YouCompleteMe/pull/1499.
I've already signed the CLA.
> Add GetType completer command for CSharp completer

- .travis.yml
Pip no longer supports --use-mirrors since version 1.5. See https://github.com/pypa/pip/pull/1098.
CLA signed.
> Remove deprecated --use-mirrors argument from pip

- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/hook.py
- ycmd/completers/go/tests/gocode_completer_test.py
This pull request fixes the default Gocode path on Windows by adding the `.exe` extension and using `os.path.join` for the full path. Otherwise, python does not find `gocode.exe` and there is no completion (and no exception raised).
There are other changes:
- the logic in `hook.py` was moved to the `GoCodeCompleter` class. This avoids calling `FindGoCodeBinary` two times. An exception is raised when no binary is found (like in the `CsCompleter` class). 
- `FindGoCodeBinary` is now a method of the `GoCodeCompleter` class since not used elsewhere. `os.path.exists` was replaced by `os.path.isfile`.
- Add test for `FindGoCodeBinary` method (it does not test finding `gocode` binary in the `PATH`).
- Fix code style and clean-up code.
There are still problems on Windows but it will be for …
> Fix Gocode path on Windows

- ycmd/completers/go/gocode_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/test_utils.py
cc @ekfriis
This PR adds commands to start and stop the `GoCode` server. This allows us to:
- manually start and stop the `GoCode` server in the client.
- stop the `GoCode` server when `ycmd` is terminated.
- stop the `GoCode` server at the end of the `GetCompletions_GoCodeCompleter` test.
- start the `GoCode` server (or do nothing if the server is already started) when the file is ready. This avoids getting a timeout when triggering semantic completion for the first time.
I did some refactoring by creating a `_GoCode` method to execute `gocode` with given parameters.
CLA signed.
> Add StartServer and StopServer commands to GoCode completer

- ycmd/completers/cs/cs_completer.py
- ycmd/utils.py
In the C# completer, the `shell` option is set to `True` when starting the `OmniSharp` server to disable the creation of a console window on Windows. This is working but there are some issues:
- this option can be a [security hazard](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments).
- this is useless on other platforms.
- the creation of a console window is not specific to the `OmniSharp` server.
This PR fixes these issues by using the [CREATE_NO_WINDOW](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx) flag on Windows directly in the `SafePopen` function. No more pesky console window when starting any process!
A side-effect of this change is that the `pythonw` executable is no longer needed on Windows. Strangely enough, this …
> Use CREATE_NO_WINDOW flag on Windows instead of shell = True

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/diagnostics_test.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/test_utils.py
Omnisharp only supports a single solution per instance. Therefore, to support multiple solutions, we have to have multiple instances of Omnisharp. We only need one instance per solution and we can tell which solution a file belongs to though FindSolutionPath, so for each request, lookup the solution, find a corresponding instance of Omnisharp, spawning it first if needed, and send it the request.
I implemented this by splitting the solution-specific parts of ``CsharpCompleter`` into a ``CsharpSolutionCompleter``. There is one instance of ``CsharpCompleter`` which manages a set of ``CsharpSolutionCompleter``, one per solution. The main section of ycmd calls ``CsharpCompleter``, which examines each request, determines the correct ``CsharpSolutionCompleter``, creating it if needed, and …
> Support multiple C# solutions

- ycmd/handlers.py
I encountered this with a network exception. Instead of receiving the
network exception, I received a AttributeError that __dict__ did not
exist in obj.
Instead of crashing, fallback to str in this case.
> Handle serializing objects without __dict__

- ycmd/tests/get_completions_test.py
Previously, starting the Omnisharp server generating the solution file,
and the SolutionFile method/command merely returned it. Now, the
SolutionFile command can generate it on its own. Since starting
Omnisharp is slow, no longer required and not the point of this test,
omit doing it.
> Faster solution finder tests

- .gitignore
- cpp/ycm/CMakeLists.txt
This fixes #48. Archives are downloaded in the `clang_archives` folder.
I bumped the cmake version to 2.8.7 cause the function to get the hash of a file is only available since 2.8.7 (fortunately, this is the version used by Travis).
I also replaced the `MD5` hash function by the more secure `SHA256` (and updated the hashes).
> Cache Clang download

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/subcommands_test.py
Sometimes ``StopServer`` fails. For example, if the server died,
it will fail with connection refused error.  Ignore error sending the
``StopServer`` requests, and retrying sending it every time we wait.
Similarly, if the server hasn't been started, logs files will be ``None``,
which will cause an error. Only delete log files if they exist.
This change made ``StopServer`` slower, thus there is a second change.
If the server is not running, both ``/stopserver`` and ``/checkalivestatus``
will sometime spin for the default network timeout of 2 seconds. This
normally doesn't matter, but in the tests, we spin up and shutdown
Omnisharp many times, and this accordingly adds many seconds to the
test suite run time. Similarly, the sleep time between still-running
checks in ``StopServer`` is a …
> C# StopServer improvements

- cpp/ycm/CMakeLists.txt
I made a mistake in PR #147. The `SHA256` option should be set without quotes when downloading Clang. I am not sure why it was working on Travis but it did not work on my linux machine. This is certainly the cmake version.
I also removed some trailing spaces.
Sorry for the trouble.
CLA already signed.
> Fix hash check when downloading Clang

- cpp/llvm/include/clang-c/BuildSystem.h
- cpp/llvm/include/clang-c/CXCompilationDatabase.h
- cpp/llvm/include/clang-c/CXErrorCode.h
- cpp/llvm/include/clang-c/CXString.h
- cpp/llvm/include/clang-c/Documentation.h
- cpp/llvm/include/clang-c/Index.h
- cpp/llvm/include/clang-c/Platform.h
- cpp/ycm/CMakeLists.txt
I also updated the headers in `cpp/llvm/include/clang-c`. No changes in `clang_include` except I could not find `arm_neon.h` in new versions of Clang. Why do we need this file?
Important: we should merge PR #150 before merging this one. It fixes a bug I introduced in PR #147.
CLA signed.
> Bump Clang version to 3.6.1

- ycmd/completers/cs/cs_completer.py
The default timeout in requests is actually None. We should use that to maintain
backward compatibility.
This is probably why https://github.com/Valloric/ycmd/pull/152 failed.
> Default timeout should be none

- ycmd/handlers.py
- ycmd/tests/test_utils.py
I'm working on using my http wrapper for jedi ([JediHTTP](/vheon/JediHTTP)). While working on it I needed something like `WaitUntilJediHTTPIsReady` without depending on OmniSharpServer, so the `include_subservers` that currently works for `/ready` wasn't useful. This will simplify the testing of the readiness of server-backed semantic engine.
> Add possibility to /ready for specific subserver

- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/tests/gocode_completer_test.py
This adds support for the Go completer to populate the preview window. 
https://groups.google.com/forum/#!searchin/ycm-users/preview$20window$20go/ycm-users/FMMoZBqZSrs/mTKP1uHjxmoJ
I've signed the CLA.
> ycmd: Add detailed_info to Go completion results.

- cpp/CMakeLists.txt
Hi,
CMake 2.8.12 was required due to YouCompleteMe issue #1439 which seems to be limited to OSX Yosemite. Requiring this version of CMake breaks compilation on CentOS / RHEL7 which comes with CMake 2.8.11 but compiles ycmd without issue.
I've adjusted `cpp/CMakeLists.txt` to detect CentOS/RHEL 7 and allow the use of CMake 2.8.11. All other operating systems and distributions will still require 2.8.12.
Thanks
> Allow use of CMake 2.8.11 on CentOS/RHEL 7.x

- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cs/cs_completer.py
Following the discussion of PR Valloric/YouCompleteMe#1545, this is an attempt to remove the 5 minimum lines restriction when compiling C-family files. This also removes the restriction for C# files (these lines were certainly copied from the Clang completer).
I did not see any lines restriction in [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim) repository so the change is safe for C# (I also tested it). For C-family files, I did not encountered issues but more testing may be needed.
Pros:
- message is annoying
- ~~remove the 'hit-enter' prompt in Vim when editing a new file~~ PR Valloric/YouCompleteMe#1545 made this irrelevant
- choice of the minimum number of lines is arbitrary
- less confusion when testing ycmd on C-family and C# files
- ~~[one-liner …
> Remove minimum lines restriction for C-family and C# files

- ycmd/completers/completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/testdata/testy/ContinuousTest.cs
- ycmd/tests/testdata/testy/testy.csproj
While researching [NRefactory](https://github.com/icsharpcode/NRefactory), which our C# completer, [Omnisharp](https://github.com/OmniSharp/omnisharp-server), is a wrapper of, I noticed that it provided a "controlspace" parameter to a completion generator method. Upon investigation, it appears that [it should called with true for explicit completion (by, for example, pressing control-space), and with false for non-explicit completion (the completion-as-you-type that Ycmd is used for)](https://github.com/icsharpcode/SharpDevelop/blob/newNR/src/AddIns/BackendBindings/CSharpBinding/Project/Src/Completion/CSharpCompletionBinding.cs). This pull request implements this behavior.
When you are typing, the C# semantic completer is called in non-controlspace mode. Additionally, it is called …
> Continuous C# completions

- cpp/ycm/CMakeLists.txt
`LIBCLANG_TARGET` is correct when building with MinGW, so we should only copy `libclang.dll` when building with MSVC (where `LIBCLANG_TARGET` is `libclang.lib` instead of `libclang.dll`). See issue #165.
CLA signed.
> Only copy libclang DLL when building with MSVC

- ycmd/completers/cs/cs_completer.py
Looks like the user specified omnisharp server port functionality (https://github.com/Valloric/ycmd/pull/82) got lost in the refactor of the cs completer.
> use user specified port for omnisharp if provided

- cpp/ycm/CMakeLists.txt
No changes in the `clang_includes` and `cpp/llvm/clang-c/include` folders. And no worries, I kept the Ubuntu version to 14.04 this time.
CLA signed.
> Bump Clang version to 3.6.2

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/testdata/test.ts
Contents should be encoded to UTF-8 if containing non-ascii characters before writing it to a temporary file in Typescript completer.
Fix issue Valloric/YouCompleteMe#1616.
CLA signed.
> Encode contents in Typescript completer

- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/tests/ClangCompleter/TranslationUnit_test.cpp
- cpp/ycm/tests/testdata/goto.cpp
- ycmd/tests/subcommands_test.py
Previously it would return the current position unchanged.
Based on comments in the test, I think this was considered a bug. This is also required for another pull request I am about to make.
> Make ClangCompleter's GoToDeclaration work when on the definition

- ycmd/completers/general/filename_completer.py
- ycmd/completers/general/tests/filename_completer_test.py
In response to https://github.com/Valloric/YouCompleteMe/issues/1600, this change allows the filename completer to expand environment variables when offering completions.
This works with the following types of path:
```
$HOME/something
$HOME/something/$something_else
$h0mE/something/etc.
/home/$USER/somewhere
/home/${USER}/somewhere_${USER}_knows_about
etc.
```
That is, variables containing 1 or more alpha, numeric, underscore or `{` and `}` chars.
> Support environment variable substitution in filename completer

- build.py
- ycmd/completers/cs/cs_completer.py
Using the release configuration of OmniSharp.
*** There are currently bugs with the Release configuration that need to be fixed with https://github.com/OmniSharp/omnisharp-server/pull/206, so this shouldn't be merged until the OmniSharp fix is merged and the submodule updated.  I'll update this PR if/when that happens.
> use release omnisharp

- ycmd/completers/cpp/flags.py
- ycmd/completers/general/filename_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/testdata/client_data/include.cpp
Fix issue Valloric/YouCompleteMe#1631.
Although it concerns C-family completions, it does not depend on the Clang completer but on the filename completer so I added the test to the (new) FilenameCompleter group.
> Pass client_data parameter to the FlagsForFile function of .ycm_extra_conf.py file for #include completion

- ycmd/completers/cpp/tests/flags_test.py
This test was not run cause of the missing `_test` part and was not correctly written.
> Fix RemoveXclangFlags test

- ycmd/completers/all/identifier_completer.py
- ycmd/completers/general/filename_completer.py
- ycmd/handlers.py
- ycmd/responses.py
- ycmd/server_state.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/testdata/general_fallback/.ycm_extra_conf.py
- ycmd/tests/testdata/general_fallback/lang_c.c
- ycmd/tests/testdata/general_fallback/lang_cpp.cc
- ycmd/tests/testdata/general_fallback/lang_python.py
TL;DR
=====
- supply general completions (alongside any errors raised) when the semantic completer (`clang_completer`, `jedi_completer`, `omnisharp_completer`, etc.) returns no results for the query and semantic completion is not forced
- tag results from the identifier completer with `[ID]`
- add tests for the above cases
Background
=========
Submitted in reference to the following issues:
* https://github.com/Valloric/YouCompleteMe/issues/1506
* https://github.com/Valloric/YouCompleteMe/issues/1225
* https://github.com/Valloric/ycmd/issues/67
The semantic engine is called either if the user enters a semantic trigger, or if they _force_ semantic completion. There may be many reasons why the semantic engine might return no results, but most commonly:
* there are errors in the file, and …
> Fall back to general completions when semantic engine has no suggestions

- .gitmodules
- build.py
Using sh module on Windows returns the following error:
```
ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```
so we drop it in favor of native and portable python functions.
We use the `--build` option of `cmake` to build the target because `make` is not available on Windows.
> [Windows support] Remove sh dependency

- ycmd/extra_conf_store.py
- ycmd/tests/extra_conf_store_test.py
We need to normalize paths in _PathsToAllParentFolders function to convert all `/` separators to `\` on Windows. We do the same in the tests since results are platform dependent.
Fix 2 tests (2 failures) on Windows: `PathsToAllParentFolders_Basic` and `PathsToAllParentFolders_WindowsPath`.
> [Windows support] Normalize paths in _PathsToAllParentFolders

- ycmd/completers/cs/cs_completer.py
- ycmd/handlers.py
- ycmd/tests/diagnostics_test.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/test_utils.py
Use the `os.path.join` function to join each component of a path (instead of using the `/` separator).
Fix 15 tests (11 failures and 4 errors) on Windows (listed in the commit message).
> [Windows support] Join path components in a portable way

- ycmd/tests/subcommands_test.py
`ycmd` returns absolute platform-dependent paths in requests (example: `/foo.py` on Linux and `c:\\foo.py` on Windows) so we need to do the same in the tests.
Fix 26 tests (26 failures) on Windows (listed in the commit message).
> [Windows support] Fix absolute paths in tests

- ycmd/completers/general/filename_completer.py
- ycmd/completers/general/tests/filename_completer_test.py
Background
====
Fixes: https://github.com/Valloric/YouCompleteMe/issues/1655
The documentation for YouCompleteMe says:
>The g:ycm_filepath_completion_use_working_dir option
> By default, YCM's filepath completion will interpret relative paths like ../ as being relative to the folder of the file of the currently active buffer. Setting this option will force YCM to always interpret relative paths as being relative to Vim's current working directory.
> Default: 0
>  let g:ycm_filepath_completion_use_working_dir = 0
But previously, only the working directory of `ycmd` was used. This meant that operations like changing the working directory of the client were not reflected in completion suggestions.
What this change does
====
The client can now (optionally) pass a `working_dir` property to the …
> Use client working directory if supplied for filename completer

- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/GetType_Clang_test.cc
Since it was the same issue, I merged the OS X fix from @puremourning and my Windows fix to this PR. Thanks to him.
Fix 3 tests (3 failures) on OS X and Windows.
>  [OS X support] [Windows support] Do not depend on std::string implementation specifics

- ycmd/tests/get_completions_test.py
- ycmd/utils.py
Python 2 fails to execute a command with unicode characters on Windows. In ycmd case, only paths in command are likely to contain such characters so the trick is to convert them to short path name (also called 8.3 path or DOS path) which only contains ascii characters.
Fix GetCompletions_CsCompleter_PathWithSpace test.
> [Windows support] Convert paths to short path name on Windows

- ycmd/completers/completer_utils_test.py
The proposed change is to fix the test `ycmd.completers.completer_utils_test.FiletypeTriggerDictFromSpec_Works_test` which previoulsy used an equality check which relied on `_sre.SRE_Pattern` objects in the dictionary being the same instances. However, this is not reliable as demonstrated in spurious test failures in https://github.com/Valloric/ycmd/pull/120.
In the instances where this test works it is relying on the call to `re.compile()` caching results and returning the same objects for the same patterns. The Python [docs](https://docs.python.org/2/library/re.html#re.compile) state that:
> The compiled versions of the most recent patterns passed to `re.match()`, `re.search()` or `re.compile()` are cached, so programs that use only a few regular expressions at a time needn’t worry …
> Fix flaky regular expression comparison test

- ycmd/tests/diagnostics_test.py
- ycmd/tests/testdata/FixIt_Clang_cpp11.cpp
The `Diagnostics_ClangCompleter_FixIt_Available` test depends on the absence of a C++11 feature (explicit conversion functions) to succeed. By default, this is the case on Linux (and certainly OS X), not on Windows. This is solved by specifying an older version of C++ (C++03) in the test.
> [Windows support] Force C++03 in diagnostics FixIt test

- .gitignore
Ignore the `libclang.so.3.7` file. I forgot to do this when updating Clang to 3.7.0.
> Add soversion Clang library to .gitignore

- run_tests.py
Forgot this when converting the run_tests script to Python in commit ce6343f6525f0731d308efebf93cbb34de590cc1.
> Build ycm_core_tests target when running tests

- build.py
- run_tests.py
Add the following options to `build.py` and `run_tests.py` scripts:
- `--msvc`: pick the MSVC version between 11, 12 (default), and 14 (respectively 2012, 2013, or 2015);
- `--arch`: force 32 or 64 bits architecture. Default is the python interpreter architecture used to start the script. Can be useful if both python 32 and 64 bits are installed. See discussion in issue Valloric/YouCompleteMe#1651.
> [Windows support] Add Windows options to scripts

- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/tests/IdentifierUtils_test.cpp
The filesystem boost library will not consider a path like `/foo/zoo` as absolute on Windows. As a result, `path.is_relative()` will return true and the computed path will be wrong. To obtain the right path, we need to use the [fs::absolute](http://www.boost.org/doc/libs/1_46_0/libs/filesystem/v3/doc/reference.html#absolute) function.
The [make_preferred](http://www.boost.org/doc/libs/1_46_0/libs/filesystem/v3/doc/reference.html#path-make_preferred) method converts slashes to backslahes on Windows.
Fix IdentifierUtilsTest.ExtractIdentifiersFromTagsFileWorks test.
> [Windows support] Fix Gmock tests

- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- cpp/ycm/ClangCompleter/ClangCompleter.h
- cpp/ycm/ClangCompleter/Documentation.cpp
- cpp/ycm/ClangCompleter/Documentation.h
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.h
- cpp/ycm/ycm_core.cpp
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/tests/comment_strip.py
- ycmd/responses.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/testdata/.ycm_extra_conf.py
- ycmd/tests/testdata/GetDoc_Clang.cc
- ycmd/tests/testdata/GetDoc_Clang.h
References 
====
Feature request: https://github.com/Valloric/YouCompleteMe/issues/1653
YCM change: https://github.com/Valloric/YouCompleteMe/pull/1694
Overview
====
The GetDoc subcommand returns detailed information (sometimes known as
QuickInfo) for the identifier at a particular location.
For C-family languages, we display:
```
<declaration of the identifier>
<brief>
Type: <canonical type>
Name: <display name>
---
<Detailed information from the doxygen comment>
```
Technical Information 
===
Clang actually has very rich support for parsing of doxygen comments. However,
this API is not strictly part of the "libclang" API - it is technically a
separate module. The core libclang module does include methods to get the raw
comment string (as typed in the buffer) and the "brief" as parsed by …
> Support GetDoc subcommand for Clang completer

- ycmd/completers/cpp/flags.py
- ycmd/tests/subcommands_test.py
This PR is a delicate one.
On Windows, templates are not parsed until instantation time which makes commands like GetType and GetParent not returning the expected value when the cursor is inside a template. To fix this, we add the flag `-fno-delayed-template-parsing` on Windows (this is the default on other platforms). We also add it to the `RunCompleterCommand_GetParent_Clang` tests to fix two tests on Windows.
However, there are some concerns about adding automatically this flag. From this comment (see this [issue](https://code.google.com/p/include-what-you-use/issues/detail?id=129))
> When IWYU runs on Windows it defaults to MSVC compatibility, to be able to parse Microsoft's STL  and Platform SDK headers. Turning off delayed template parsing will likely make it fail to parse these …
> [Windows support] Do not delay parsing of templates on Windows

- ycmd/completers/cpp/clang_completer.py
Fix subcommands completion and listing. `GetDoc` subcommand was not directly affected by this.
> Fix missing comma in Clang completer subcommands

- ycmd/completers/cpp/tests/comment_strip_test.py
`ycmd/completers/cpp/tests/comment_strip.py` tests was not run automatically by nosetests because `_test` was missing at the end of the filename.
> Fix filename of comment_strip tests

- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/tests/comment_strip_test.py
- ycmd/tests/subcommands_test.py
Using `os.linesep` makes things complicated for no benefits:
- Clang returns `\n` for newlines on Windows;
- Python and editors should manage without issue `\n` on Windows;
- there is a bug with `textwrap.dedent()` and `\r\n` newline;
- tests are a pain to fix with platform-dependent newlines.
@puremourning Could you update your PRs (#232, #233, and #234) accordingly?
> [Windows support] Do not use os.linesep

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/testy/GetDocTestCase.cs
- ycmd/tests/testdata/testy/GetTypeTestCase.cs
This builds on the support added for the Clang completer and simply returns the
type information along with the documentation provided by OmniSharp-server.
Change GetType to just return the type
The documentation provided by OmniSharp-server was previously included in the
GetType subcommand. In the Vim client, this is echo'd to the console and
requires hitting a key to dismiss. Now that there is the GetDoc command, this
has been changed to just return the type, for consistency with go completer and
Clang completer.
References: 
* https://github.com/Valloric/YouCompleteMe/issues/1653
* https://github.com/Valloric/YouCompleteMe/pull/1694
* https://github.com/Valloric/ycmd/pull/229
> Add GetDoc subcommand for c-sharp completer

- ycmd/completers/python/jedi_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/GetDoc_Jedi.py
This builds on the Clang completer support and returns the docstring from any
associated declarations for the context.
References: : 
* https://github.com/Valloric/YouCompleteMe/issues/1653
* https://github.com/Valloric/YouCompleteMe/pull/1694
* https://github.com/Valloric/ycmd/pull/229
> Add GetDoc support to Python completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/test.ts
This builds on the Clang completer support for GetDoc subcommand, and just
returns the docuemntation supplied by tsserver in the quickinfo response.
References: 
* https://github.com/Valloric/YouCompleteMe/issues/1653
* https://github.com/Valloric/YouCompleteMe/pull/1694
* https://github.com/Valloric/ycmd/pull/229
> Add GetDoc subcommand to typescript completer

- cpp/ycm/CMakeLists.txt
`7-zip` is the best way I found to obtain the files from the Clang installer without installing it.
> [Windows support] Add Clang downloads for Windows

- build.py
- run_tests.py
Since this is the version that users will download and install if they don't already have it, it makes sense to set the default to MSVC 14. It will also simplify the Windows documentation (no need to tell the user to set the option `--msvc` to 14).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/239)
> Set default MSVC version to 14

- cpp/ycm/CMakeLists.txt
Some AppVeyor runs are failing because of network issues when downloading Clang. This PR should fix this by trying to download Clang multiple times until successful.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/245)
> Improve Clang download robustness

- .travis.yml
- build.py
- test_requirements.txt
- travis/README.md
- travis/travis_install.linux.sh
- travis/travis_install.osx.sh
- travis/travis_install.sh
Fixes https://github.com/Valloric/ycmd/issues/191
Dependency
====
Merging this will require @Valloric to request OS X support for ycmd repo. This requires sending a mail to support@travis-ci.com and requesting to feature-flag the repo for multiple OS support.
Overview
====
This involved 2 changes:
- switching to the new Travis infrastructure, and
- getting build scripts set up to bootstrap on OS X
Unfortunately, the "python" Travis config is not yet supported on OS X, so we actually transition to the "csharp" one (because that just handles installing mono for us), and we implement the required multi-python-environment stuff manually.
This involves using a third-party repo for Linux and some cool built-in multi-lib stuff on OS X. 
Multiple Python Versions
========
We use an environment …
> Test on on OS X using Travis

- ycmd/utils.py
This code is specific to Vim and should be moved to YouCompleteMe. See Valloric/YouCompleteMe#1719.
For @Valloric, is the Vim-related code really needed in `ycmd/completers/completer.py`?
```python
if RunningInsideVim():
from ycm_client_support import FilterAndSortCandidates
else:
from ycm_core import FilterAndSortCandidates
```
I tried it without the `RunningInsideVim` part and it was working so I am wondering if we can safely remove it. Ideally, ycmd should not contain any Vim specifics.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/249)
> Remove Vim-specific code

- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/tests/flags_test.py
Currently, if we have a header file for which its corresponding C++ file exists
in the compilation database, we forget that it's supposed to be a C++ header by
stripping away the compiler.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/248)
> Replace compiler with language flag if it's a C++ compiler.

- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/tests/flags_test.py
PR #248 introduced an unexpected behavior when dealing with compilation database. When commands (like `ccache`) are used before the actual compiler, YCM considers the first of those commands as the compiler path, which leads YCM to use the wrong language flag (`-x c`) for C++ files. This was found in issue Valloric/YouCompleteMe#1737.
New behavior is to assume that the flag just before the first one starting with a dash is the compiler path. All flags preceding the compiler path are ignored.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/253)
> Ignore commands before the compiler path when replacing it with language flag

- cpp/ycm/CMakeLists.txt
With this PR, `PATH_TO_LLVM_ROOT` is correctly set on Windows with the new 7-zip release (15.12).
Issue was found on the [ycm-users](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ycm-users/Rro51uaFooU/sR3Px2PDBwAJ) list.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/261)
> Fix LLVM path for new 7-zip release

- ycmd/completers/completer.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/gocode_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/subcommands_test.py
Currently, each semantic completer reimplements the `OnUserCommand` and `DefinedSubcommands` in about the same way. To avoid duplication of code, this PR moves the logic of these methods to the `Completer` class. Completers only need to implement a new function `GetSubcommandsMap` that return a map between the subcommands name and the methods to call. The map structure is explained in the method documentation. 
Minor improvements:
- `DefinedSubcommands` now returns an alphabetically sorted list (tests updated to reflect this);
- Fix issue in PR #263.
Important: if this PR is merged, the `OmniCompleter` class will need to be updated in YCM by inheriting from `GeneralCompleter` instead of `Completer` or implementing the `GetSubcommandsMap` method.
[<img …
> Move subcommands logic to Completer class

- .gitignore
- .travis.yml
- README.md
- TESTS.md
- run_tests.py
- travis/travis_install.sh
Add information on running coverage tests and tidy up the developer test documentation.
Run a new Travis build with coverage enabled.
Pass coverage data to coveralls.io.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/271)
> [ready] Add coverage testing support

- .coveragerc
There is no point to get the coverage of the tests and `__init__.py` files are empties so we exclude them from the coverage report.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/274)
> Add configuration to exclude tests and empty files from Coveralls.io report

- test_requirements.txt
- ycmd/tests/javascript/event_notification_test.py
- ycmd/tests/javascript/get_completions_test.py
- ycmd/tests/javascript/javascript_handlers_test.py
- ycmd/tests/javascript/subcommands_test.py
- Move related completer tests to their own subdirectories:
```
ycmd
└── tests        
├── clang
│   ├── testdata
│   ├── __init__.py
│   ├── get_completions_test.py
│   ├── diagnostics_test.py
│   ├── subcommands_test.py
│   └── utils.py 
├── cs ── ... 
├── python ── ...
├── go ── ...
...
```
- Regroup tests in classes and subclasses: take advantage of fixtures (`setUp` and `tearDown` methods) and inheritance.
- Rename tests: names are now shorter;
- Fix coding style;
- Update copyright notices;
- No tests were harmed during the making of this PR: 458 tests before, 458 tests after.
- Code to set the Bottle debug mode:
```python
import bottle
bottle.debug( True )
```
was removed from all tests inheriting from `Handlers_test` where it is set in the `setUp` method. Is it enough to enable …
> [READY] Refactoring integration tests

- .travis.yml
`run_tests.py` automatically uses coverage options if the `COVERAGE` environment variable is defined.
Maybe it would be better to change the name of this environment variable to `YCMD_COVERAGE`, `COVERAGE` is too generic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/279)
> Remove coverage options on Travis because we can

- ycmd/completers/javascript/tern_completer.py
Fixes #278 
As described on the issue, the Tern server exits when a timeout is hit. The Tern server's timeout is actually a guesstimate anyway, and ignores I/O time. We're better off just removing it and relying on ycmd client requests timing out. It doesn't appear that the other completers add any other time-out.
We can re-asses should https://github.com/ternjs/tern/issues/702 be fixed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/281)
> [READY] Remove timeout from Tern completer

- ycmd/completers/javascript/tern_completer.py
- ycmd/tests/javascript/event_notification_test.py
Fixes #277 
We simply suppress the warning if we detect a `.tern-project` or a user's `~/.tern-config`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/280)
> [READY] Recognise ~/.tern-config in Tern completer

- appveyor.yml
AppVeyor just updated python to 2.7.11 and core tests are now failing with the error `ImportError: No module named site`. Setting `PYTHONHOME` environment variable fix this issue. It may be related to [this python issue](http://bugs.python.org/issue25824) even if I cannot reproduce it on my setup. I expect this issue to be fixed with the next python release but for the time being, use this workaround.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/283)
> [READY] Fix python error on AppVeyor

- build.py
Basicaly, everything is in the name.
When I tried to build ycmd on Windows I found out that build script uses wrong names for all generators, that are used to build project on Windows.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/285)
> Fixed names for CMake generators, used on Windows.

- ycmd/server_state.py
I was looking at the coverage and I noticed that this method is not tested, a quick grep on the codebase showed why: we apparently don't use it.
> Remove unused method

- .gitmodules
- appveyor.yml
- build.py
- run_tests.py
- travis/travis_install.sh
- ycmd/completers/rust/hook.py
- ycmd/completers/rust/rust_completer.py
- ycmd/default_settings.json
- ycmd/tests/rust/get_completions_test.py
- ycmd/tests/rust/rust_handlers_test.py
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/rust/testdata/test.rs
[racerd][] and the ycmd completer wrapper for racerd are finally ready for some peer review and testing. There are some blocking issues that need to get resolved before we can launch; these are enumerated later.
This gif shows semantic completion support (module paths and object members) and GoTo jumping (starting with BinaryHeap and further into the standard library). GoTo, GoToDefinition, and GoToDeclaration are all equivalent at this time.
1. Install [multirust][] if you don't already have it.
2. Add this branch to your local ycmd installation. For example,
```
cd $YCMD_PATH
git remote add jwilm https://github.com/jwilm/ycmd.git
git fetch jwilm
git checkout rust-support
```
3. Run the ycmd build.py script with an additional argument. If you only care about rust support, the build …
> [READY] Add support for the Rust programming language

- ycmd/completers/python/jedi_completer.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/testdata/goto_references.py
The feature to find usages/references of thing at point has been added recently to JediHTTP https://github.com/vheon/JediHTTP/commit/c7104b199f22082070fa669e52e2f5aac312ffb7.
This patch adds a subcommand in python completer to get usages.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/298)
> Add FindUsages subcommand in jedi completer

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/get_completions_test.py
- ycmd/tests/rust/testdata/std_completions.rs
If a completion request to racerd fails AND the user has not set the
rust_src_path config option, then we return a nice error message
mentioning to the user that they likely reason of the failure is the
empty value for that option. This should provide the user with something
to search for in the YCM docs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/299)
> Error message when rust_src_path unset

- ycmd/completers/completer_utils.py
Improves semantic trigger match.
Match triggers until user's caret column solely. Trying to match
triggers with characters after user's caret column doesn't seem
to have any utility.
---
This is the first in a series of pull-requests that will transparently enable
#1300 for any completer that cares for. After this minimal foundation is
stablished, an initial Swift completer will be available, supporting diagnostics,
fix-it's, semantic completion and argument hints. Changes will also be
proposed to enable hints for C and C++.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/292)
> Improves semantic trigger match.

- ycmd/completers/python/jedi_completer.py
`RestartServer` subcommand is not working because the `request_data` parameter is not given to the `RestartServer` method. Since this parameter is not used, remove it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/303)
> [READY] Fix RestartServer command in Python completer

- ycmd/completers/completer_utils.py
- ycmd/completers/completer_utils_test.py
Since regex triggers have been enabled, _StringTriggerMatches was
actually not in use anymore since _PrepareTrigger always return
regexes, making triggers never a instance of basestring.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/300)
> Removes dead code.

- ycmd/completers/completer_utils.py
- ycmd/completers/completer_utils_test.py
Allows one to obtain the current trigger regex from inside semantic
completers, enabling customized completions based on it, like normal
code completion or argument hints.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/305)
> Extends PreparedTriggers.

- cpp/CMakeLists.txt
Remove CMAKE_LEGACY_CYGWIN_WIN32, since we are now requiring CMake >=
2.8.4, where it was forced to our current setting and only produces a
warning when set.
Reverts https://github.com/Valloric/YouCompleteMe/commit/aa719665da7c726cefdc417a93c90830c45ec0b0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/308)
> Remove CMake legacy mode for cygwin

- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/tests/flags_test.py
Hello,
I use YCM in a cross compiled project.
To compile the project we use '--sysroot' and '-gcc-toolchain' these directories were removed from the compiling commandline and resulted in build fails.
Therefore I added those to the INCLUDE_FLAGS.
Greetings,
Nagua
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/312)
> Add --sysroot and -gcc-toolchain as INCLUDE_FLAGS

- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/handlers.py
- ycmd/tests/cs/cs_handlers_test.py
- ycmd/utils.py
Currently, C# completer starts a new server on the `FileReadyToParse` event if no port is defined or the running server does not respond. This can lead to situations where multiple servers with same port and solution are started until one of them become ready. See PR #284 and Valloric/YouCompleteMe#1913. 
This is fixed by using `ServerIsActive` instead of `ServerIsRunning` to start the server in `OnFileReadyToParse`. We then check `ServerIsRunning` for an early return.
`ServerIsActive` is updated to check the handle (instead of the port) and to poll the process. We cannot only rely on the port because it can be defined while the process is down: server crashed during start up or its process was directly terminated by the user.
`ServerIsRunning` and `ServerIsReady` are also changed. We …
> [READY] Prevent simultaneous starts of OmniSharp server

- ycmd/completers/python/jedi_completer.py
- ycmd/default_settings.json
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/handlers_test.py
- ycmd/tests/python/get_completions_test.py
- ycmd/tests/python/python_handlers_test.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/user_defined_python_test.py
I'm starting this PR as WIP because it lacks tests and I wanted to ask for suggestion about that. What do you think would be the best approach? I was thinking about configuring the `user_option` and check how the `utils.SafePopen` was called but in general I'm not a fan of this kind of tests, so I'm open to suggestion :smiley:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/295)
> [READY] Make python binary specifiable by the user

- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/typescript_handlers_test.py
The typescript completer have some feature that are not tested; this is one of them that was also found by a user in https://github.com/Valloric/YouCompleteMe/issues/1878. I'm going to add tests for GoTo in a separate PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/317)
> [READY] Add test for typescript MAX_DETAILED_COMPLETION

- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/responses.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/javascript/testdata/.tern-project
- ycmd/tests/javascript/testdata/file1.js
- ycmd/tests/javascript/testdata/file2.js
- ycmd/tests/javascript/testdata/file3.js
- ycmd/tests/javascript/testdata/file4.js
- ycmd/tests/javascript/testdata/simple_test.js
Tern server supports renames of variables only. It can do this across multiple files, only when it knows about those files. This feature is supported by tern_for_vim, so with the addition of this feature we should have feature-parity on that front.
This re-uses the existing FixIt infrastructure, with no changes to the JSON API. The only change is that this is the first time the command will return changes in multiple files.
The largest change is moving the Cs* classes that are equivalent of the C++ classes representing diagnostics/FixIts to `responses.py`, so they can be shared by other completers.
A Vim client change is required to recognise FixIt responses by the contents of the response, rather than the command name, and to apply the chunks across files.
## FileReadyToParse
Previously, …
> [READY] Support for rename in tern completer

- build.py
While I was playing with `EXTRA_CMAKE_ARGS` environment variable to answer issue Valloric/YouCompleteMe#1925, I found out it was not possible to pass CMake arguments with spaces in it because the variable is split on spaces. For example:
```sh
EXTRA_CMAKE_ARGS="-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_FLAGS='-march=native -O3'"
```
gives
```python
['-DCMAKE_VERBOSE_MAKEFILE=ON', "-DCMAKE_CXX_FLAGS='-march=native", "-O3'"]
```
which obviously fail.
This is fixed by using the [`shlex` module and its split feature](https://docs.python.org/2/library/shlex.html). With this, example above results in:
```python
['-DCMAKE_VERBOSE_MAKEFILE=ON', '-DCMAKE_CXX_FLAGS=-march=native -O3']
```
which make us happy.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> [READY] Properly split EXTRA_CMAKE_ARGS environment variable in build.py script

- ycmd/completers/completer.py
- ycmd/completers/completer_utils.py
- ycmd/completers/completer_utils_test.py
- ycmd/tests/get_completions_test.py
This PR fixes issues Valloric/YouCompleteMe#1602 and Valloric/YouCompleteMe#1930.
I updated the tests and added some cases.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/319)
> [READY] Relax semantic trigger matching to match between column start and current cursor column

- .gitignore
- .gitmodules
- build.py
- third_party/tern_runtime/package.json
- ycmd/completers/javascript/tern_completer.py
The Tern server supports a large number of plugins which add both functionality and databases of common libraries, like `express`. We want to allow users to install third party plugins to node_modules of the Tern runtime.  We also want to be able to install our own plugins to improve the user experience for all users.
This is not possible if we use a git submodule for Tern and simply run 'npm install' within the submodule source directory, as subsequent 'npm install tern-my-plugin' will (heinously) install another (arbitrary) version of Tern within the Tern source tree (e.g. third_party/tern/node_modules/tern. The reason for this is that the plugin that gets installed has "tern" as a dependency, and npm isn't smart enough to know that you're installing *within* the Tern distribution. Or …
> [READY] Support Tern plugins by installing into a sandbox

- ycmd/completers/cs/cs_completer.py
I ran into a case where the Omnisharp server returned invalid json while starting up, which caused a ValueError.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/323)
> CsCompleter: Revert to trapping all exceptions for status checks

- appveyor.yml
Homu does not support AppVeyor so there is no need to run the `auto` branch on AppVeyor.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/324)
> [READY] Ignore the branch used by Homu on AppVeyor

- build.py
So there is this new error that occurs occasionally on AppVeyor:
```sh
WindowsError: [Error 145] The directory is not empty: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\ycm_build.***\\ycm\\tests'
```
It probably happens because the `ycm_core_tests` executable is still used by some process while the build folder is removed.
I see three ways to fix this:
- ignore the error;
- ignore it but print a warning;
- retry several times (`3` should be enough).
I implemented the first approach because it is the simplest but I don't really like the idea of leaving (in rare cases) some files in the temporary folder (Windows does not automatically clean this folder). This is why the PR is marked as RFC. Ideally, we should implement the third approach.
[<img …
> [READY] Fix error when removing temporary folder on AppVeyor

- .travis.yml
We used to have 9 (5 Linux, 4 Mac) rows in our test matrix; these
changes should bring it down to 6 (3 Linux, 3 Mac).
First, we cut out clang on/off for Python 2.7. There's already
two rows for clang on/off on Python 2.6, and testing the same
on/off setup with 2.7 seems wasteful. We now just test 2.7 with clang
on. This is two rows down (Linux & Mac each).
Another row killed is Linux-clang-py2.7, because we also have
Linux-clang-py2.7-coverage. That one runs all the tests and also runs
coverage, so contains the row we're killing.
All together, this should speed up our Travis runs.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/335)
> [READY] Pruning the size of the Travis test matrix

- .gitmodules
- run_tests.py
- ycmd/responses.py
- ycmd/utils.py
We'll use this for Python 3 compatibility. Also changed responses.py
using futurize so that it uses a module from python-future to ensure the
sys.path module pickup is working.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/332)
> [READY] Adding new python-future dependency

- .travis.yml
- build.py
- ci/travis/travis_install.linux.sh
- ci/travis/travis_install.osx.sh
- Using clang instead of gcc; compiles faster and with less memory,
meaning we can build in parallel.
- Caching more stuff so startup is faster. In particular, the Rust
toolchain.
- Using the ninja build tool which tends to be faster than Make.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/336)
> [READY] More travis run speedups

- run_tests.py
Passing it doesn't hurt and makes it possible to sensibly use the `--failed` flag.
Without `--with-id`, the first time we use `--failed`, it runs _all_ the tests, not just the failing ones. Only the second run with `--failed` runs only the failing tests. The reason for this is that the test name ID map needs to be generated, which passing `--with-id` enables by default.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/341)
> Now always passing --with-id to nosetests

- run_tests.py
Makes it possible to skip the flake8 run. Speeds up the dev workflow
when repeatedly running a single failing test.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/342)
> New --no-flake8 flag for run_tests.py

- .gitignore
Now that we pass the `--with-id` option to nosetests (PR #341), the `.noseids` file is created. We ignore it.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/345)
> [READY] Ignore file created by nosetests --with-id option

- ycmd/completers/typescript/typescript_completer.py
The way it currently works, each sequence of requests/responses acquire a global lock. This restricts the usage of tsserver commands/functionality that can take a bit of time to complete (syntax checking / compilation errors).
**I need help with naming things**
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/344)
> TypeScript: Allow concurrent requests

- ycmd/completers/completer.py
- ycmd/tests/completer_test.py
When the first candidate from the Omnifunc candidates list is the string `words` or contains the substring `word`, the following error is raised:
```python
TypeError: string/list indices must be integers, not str
```
Reason is that the condition `<key> in <dictionary>` can also return true if `<dictionary>` is a list or a string.
Add tests covering these edge cases. Check if `candidates` and `candidate[ 0 ]` are dictionaries before looking at the existence of the `word` and `words` keys.
This PR fixes Valloric/YouCompleteMe#1953.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/349)
> [READY] Fix issue when first candidate contains keywords as its substring

- build.py
I find this useful when developing, as I always enable all completers.
```
./install.py --all
```
rather than
```
./install.py --clang-completer --omnisharp-completer --gocode-completer --racer-completer
```
If you guys think this is also useful, we can merge it and I will update YCM's README. If not, then I'm not precious about this - i'll just maintain it in my fork :)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/352)
> [READY] Add --all option to build.py

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/cs/cs_handlers_test.py
- ycmd/tests/cs/diagnostics_test.py
- ycmd/tests/cs/get_completions_test.py
- ycmd/tests/cs/subcommands_test.py
Running all the tests in ycmd takes a long time. The reason for this is
repeatedly starting and stopping Omnisharp servers. To mitigated this, whenever
we start an instance of Omnisharp during testing, we cache it, and reuses it
from the cache whenever a test requires a instance of Omnisharp on the same
solution.
As part of this, add Set/GetOmnisharpPort commands to the C# completer. These
commands allow setting the port it uses to communicate with the Omnisharp
server. This allows sharing of the Omnisharp server by retrieving the port and
using it in other clients, or get the port another client is using and using it
here.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/339)
> Persistent Omnisharp in tests

- ycmd/tests/python/python_handlers_test.py
I've tried to debug and reproduce the flakiness of JediHTTP but I couldn't. So for now let's just bump the number of tries to 100 and see how it goes. If it will happen again I'll take a deeper look.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/357)
> [READY] Wait longer for JediHTTP to be ready in tests

- cpp/ycm/CMakeLists.txt
Search not only for clang, but also for libclang.so.1.
This way the system-wide installed libclang is found on Debian-based systems.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/361)
> Find system-libclang on Debian x386 systems

- ycmd/completers/typescript/typescript_completer.py
It sets a timeout of 100 seconds, which is a little long.
Should not conflict with PR #358.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/359)
> [READY] Fix wrong constant used in Typescript completer

- .travis.yml
- build.py
- ci/travis/travis_install.linux.sh
- ci/travis/travis_install.osx.sh
- ci/travis/travis_install.sh
On OS X, Python and all of its extension libraries must be built using the same *shared* python library. If any of them contain a statically linked libpython.a, then the global variable linkage gets broken, and you are presented with an obscure crash. We force users to link against a dynamically linked python.
Fixes https://github.com/Valloric/YouCompleteMe/issues/18#issuecomment-182634945.
Pyenv works fine if you specify the `--enable-framework` at build time (as noted above).
Also, the virtualenv bug is fixed, so bump the version to latest.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/363)
> [READY] Test python 3.3 on OS X

- appveyor.yml
- build.py
- ci/appveyor/appveyor_install.bat
- run_tests.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/cs/cs_handlers_test.py
- ycmd/utils.py
We cannot pass an environment variable containing unicode literals to `Popen` on Windows and Python2. Instead of converting all environment variables to native strings, we only convert the ones we use.
We update the requests submodule to fix a compatibility error between requests and Python 3.5.
Fix from PR #211 is only needed for Python 2.
In `build.py`, we prepend the folder of the `ycm_core_tests` executable to the `PATH` instead of replacing it so that the executable is able to find the `python35.dll` library.
We don't reuse Omnisharp instances in C♯ tests on Windows and Python 3 because of the following random error occuring when running those tests:
```python
OSError: [WinError 6] The handle is invalid
```
We append the `-DUSE_DEV_FLAGS=ON` option to `EXTRA_CMAKE_ARGS` environment …
> [READY] Fix Python 2 support and add Python 3 support on Windows

- ci/travis/travis_install.sh
For some reason, when using python 3.3.0 setuptools [ends up being
broken](https://travis-ci.org/Valloric/ycmd/jobs/109484455) which breaks out Travis config. But using python 3.3.6 fixes it
(other versions >3.3.0 & <3.3.6 might also work).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/371)
> [READY] Fixing Travis issues with setuptools

- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- cpp/ycm/ClangCompleter/ClangCompleter.h
- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/CompletionData.cpp
- cpp/ycm/ClangCompleter/CompletionData.h
- cpp/ycm/ClangCompleter/Documentation.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/DLLDefines.h
- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/tests/Candidate_test.cpp
- cpp/ycm/tests/ClangCompleter/ClangCompleter_test.cpp
- cpp/ycm/tests/IdentifierCompleter_test.cpp
- cpp/ycm/versioning.h
- vagrant_bootstrap.sh
People forget to run it in PRs so we've accumulated some things that
don't follow the style guide.
Since astyle isn't perfect, this also makes some code worse (like
the #define indents), but we don't want to make manual changes to astyle
output. (If clang-format were more flexible, we could use that, but
currently it produces worse output that astyle for our codebase.)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/372)
> [READY] Running ./style_format.sh to reformat C++

- build.py
- ycmd/completers/rust/rust_completer.py
We don't use the `--release` flag on Travis/AppVeyor because it makes building racerd 2.5x slower and we don't care about the speed of the produced racerd.
The 2.5x slower number is from my local workstation, but I'm guessing it's similar on Travis as well.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/366)
> [READY] Not using --release on CI when building racerd

- ycmd/completers/javascript/tern_completer.py
It was easier to fix than I thought. We just need to use the `stdin_windows` option when starting the Tern server.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/369)
> [READY] Fix logs issue in Javascript completer on Windows

- cpp/ycm/CandidateRepository.cpp
- cpp/ycm/CandidateRepository.h
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/tests/CandidateRepository_test.cpp
This prevents issues with auto-generated strings entering the database
and screwing everything up.
Fixes Valloric/YouCompleteMe#520
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/370)
> [READY] Setting a max candidate size limit (80 chars)

- ycmd/bottle_utils.py
- ycmd/handlers.py
- ycmd/hmac_plugin.py
- ycmd/tests/bottle_utils_test.py
- ycmd/tests/utils_test.py
Bottle is dumb when it comes to headers and bytes vs unicode. Details in source comments.
Funny thing: the reason why I didn't notice this problem while working on the py3 compatibility PR is that all our tests skip the main WSGI interface, so to test that part too since we don't have ycmd smoke tests (yet, but I'll be fixing that), I used the example_client to talk to ycmd. This worked great, but since the example_client only works on py3, I only tested in a py3 pyenv, which ran ycmd in a py3 interpreter... but this problem only appears on a py2 interpreter, which I'm using now while trying to make YCM work with latest ycmd.
Yet another case of "having more tests would have caught this early and saved you a ton of effort and hair-pulling" (which I'm naming _The Perennial Lesson_ AKA …
> [READY] Fixing issues with setting headers on py2

- ycmd/__main__.py
Details in source comment.
This whole py2 -> py3 process has turned my dislike of dynamic languages into pure, unbridled hatred.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/379)
> [READY] Fixing issues with libs printing to stdout

- ycmd/__main__.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
The fix from #379 fixed py2, but broke py3. This fixes both and adds a test.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/381)
> [READY] More fixes for printing with custom sys.stdout

- ycmd/tests/utils_test.py
- ycmd/utils.py
They used to return `u'None'`/`b'None'`, which we don't want.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/383)
> [READY] ToBytes/ToUnicode return empty bytes/str for None

- cpp/ycm/tests/CMakeLists.txt
Fix the link error:
```
ycm_core_tests.exe : fatal error LNK1169: one or more multiply defined symbols found
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/387)
> [READY] Fix ycm_core_tests linking order on Windows

- cpp/ycm/CMakeLists.txt
This is not working as expected because if one download fails, CMake considers the configuration as incomplete even if a subsequent download is successful, and the `build.py` script returns an error.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/391)
> [READY] Revert "Auto merge of #245 - micbou:clang-download, r=Valloric"

- .travis.yml
- appveyor.yml
This introduces the following changes with Travis and AppVeyor caches:
- remove DNX cache on Travis. It is not related to OmniSharp server but Omnisharp Roslyn;
- add NPM cache on Travis (`TypeScript` and `Tern` packages);
- remove OmniSharp compilation folder from cache because the gain is negligible: it takes 6s to compile and its the OmniSharp dependencies that takes the most time to compile, not OmniSharp itself (it is almost instantaneous);
- add Clang downloads to cache on AppVeyor: avoid network issues when downloading Clang;
- disable cache invalidation for Rust on AppVeyor: apparently, it is not needed.
Overall, try to uniformize the cache rules between CI services.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …
> [READY] Update Travis and AppVeyor caches

- ycmd/completers/completer_utils.py
We want to prevent Vim from importing ycm_core.
@vheon @micbou You guys noticed the issue in https://github.com/valloric/youcompleteme/pull/2004
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/393)
> [READY] ycm_core imported inside wrap function

- ycmd/tests/python_support_test.py
- ycmd/tests/testdata/unix/compile_commands.json
- ycmd/tests/testdata/windows/compile_commands.json
- ycmd/utils.py
Fix tests by using a specific `compile_commands.json` for Windows. Refactor them to reduce code duplication.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/396)
> [READY] Fix Python support tests on Windows

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
We now ensure that we pass a py2 str object to the user's FlagsForFile
function (in ycm_extra_conf.py) when running in a py2 interpreter. For
py3, we pass a py3 str object (so unicode).
For strings coming in from FlagsForFile, we accept all of [py2 str, py2
unicode, py3 bytes, py3 unicode]. UTF-8 for the encoded types.
Also, fixes a bug in ToCppStringCompatible which would break things with
unicode flags.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/398)
> [READY] Defined handling of str vs bytes for FlagsForFile

- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/hook.py
- ycmd/tests/go/gocode_completer_test.py
- ycmd/utils.py
I believe that looking at the user PATH is not user friendly as showned by https://github.com/Valloric/ycmd/issues/354. If the user really want to use a different binary than the one we ship there's always the user option `gocode_binary_path` and `godef_binary_path` available.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/355)
> [READY] Don't look for binaries in user's PATH for Go

- ci/appveyor/appveyor_install.bat
I found out that they backported the fix in Rust 1.6 so here we go. Fixes #293.
@jwilm You may update `appveyor.yml` in `racerd` repository too.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/401)
> [READY] Use MSVC version of the Rust compiler on AppVeyor

- ycmd/completers/go/go_completer.py
- ycmd/completers/go/hook.py
- ycmd/tests/go/go_completer_test.py
Now that we use `godef` along with `gocode` it doesn't make much sense
to keep calling the completer GoCodeCompleter.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/404)
> [READY] Rename GoCodeCompleter -> GoCompleter

- build.py
Previously you had to specify both `--all` and `--clang-completer` in order to have `--system-libclang`.
This fixes that, and updates the error message when you have neither.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/407)
> [READY] Allow --system-libclang with --all

- build.py
We're currently hard-coding 2.6 or 2.7 for the supported version of the 2.x Python branch instead of checking for >= 2.6.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/405)
> [READY] Make Python version checking more robust

- cpp/ycm/CMakeLists.txt
In OS X El Capitan, Apple introduced System Integrity Protection.  Amongst other things, this introduces features to the dynamic loader (dyld) which cause it to "sanitise" (and complain about) embedded LC_RPATH entries which contain @executable_path when then are loaded into "restricted" binaries.  For our purposes, "restricted" here means "supplied by Apple" and includes the system versions of python.  For unknown reasons, the libclang.dylib that comes from llvm.org includes an LC_RPATH entry '@executable_path/../lib' which causes the OS X dynamic loader to print a cryptic warning to stderr of the form:
> dyld: warning, LC_RPATH @executable_path/../lib in /path/to/ycmd/libclang.dylib being ignored in restricted program because of @executable_path
Note: This does not happen when using …
> [READY] Prevent annoying on OS X El Capitan when using system python

- README.md
Just fixing a link in the README.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/413)
> Fix README link to Mac OS X installation

- ycmd/completers/completer_utils.py
- ycmd/tests/completer_utils_test.py
Fixes Valloric/YouCompleteMe#2022.
Here's the full traceback from the error:
```python
File "<string>", line 24, in <module>
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\setup.py", line 59, in SetUpYCM
return YouCompleteMe( user_options_store.GetAll() )
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\youcompleteme.py", line 95, in __init__
self._omnicomp = OmniCompleter( user_options )
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\omni_completer.py", line 38, in __init__
super( OmniCompleter, self ).__init__( user_options )
File "C:\Users\micbou\.vim\bundle\YouCompleteMe\python\ycm\..\..\third_party\ycmd\ycmd\completers\completer.py", line 113, in __init__
if …
```
> [READY] Convert triggers to unicode before compiling them as a regex

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/test_utils.py
OS X (by default) has 2 ways to set up development environment: Xcode.app and
installation of the CommandLineTools. As previously known, libclang does not
automatically add these system include paths as clang's own driver does.
Previously, ycmd would add the Xcode.app c++ include directories. This change
ensures that we add the system include paths when only the CommandLineTools are
installed (they are significantly lighter weight than xcode and installed
automatically when first attempting to run things like clang).
Additionally, around Xcode 7, additional include paths became required which are
located in versioned directories. These headers are clang-specific headers (such
as stddef.h). This change includes a mechanism to find such includes by
selecting the highest versioned set of …
> [READY] Automatically include clang includes on OS X

- ycmd/completers/cs/cs_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/testdata/file2.ts
- ycmd/tests/typescript/testdata/file3.ts
- ycmd/tests/typescript/testdata/tsconfig.json
Fixes https://github.com/Valloric/YouCompleteMe/issues/2018
This also contains a pretty important fix to the javascript tests where the tests weren't actually executing a matcher on `RefactorRename` tests.
Currently RFC because this was done pretty quickly and tested fairly casually. I'm pretty confident it works because it is almost identical to the javascript implementation (In the sense that the hard work is still done by the client, which is unchanged), but still worth some additional testing.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/417)
> [READY] Add RefactorRename support to typescript

- cpp/ycm/CMakeLists.txt
Currently, headers are included by CMake in this order (when compiling with Clang support):
- BoostParts
- Python
- Clang
- `cpp\ycm`
- `cpp\ycm\ClangCompleter`
The issue with this order is that if one of our headers has the same name as one of BoostParts, Python, or Clang headers, the wrong header may be included (depending on how it is included in the code). It can't happen with GCC and Clang compilers because the `-isystem` flag is used for these includes (`-isystem` directories are searched after `-I` directories). However, it is possible on Windows since there is no `-isystem` equivalent for MSVC. See issue in PR #291 where Python `token.h` is included instead of ycmd `Token.h`.
We prevent this by including the Boost, Python, and Clang directories after the ycmd ones.
---
This change …
> [READY] Include headers from external projects last

- README.md
It seems that all the listed known ycmd clients do in fact require the user to build and set up ycmd on their systems (except for YouCompleteMe, but even that still requires occasional recompilation). Removing this comment reduces potential confusion for people seeking to set up their ycmd client as most client's install instructions link to this section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/434)
> Removed comment about clients building ycmd

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
These are commonly used for HTML templating; see Handlebars, Angular
etc.
Fixes Valloric/YouCompleteMe#2058
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/436)
> Ignoring HTML template chars `{` and `}`

- cpp/ycm/ClangCompleter/CompletionData.cpp
For C-family languages, we used to remove two consecutive underscores in
identifiers out of a misguided attempt to reduce verbosity of reserved
identifiers. This only produced user confusion.
This logic also had no tests! Oh the shame...
Fixes Valloric/YouCompleteMe#2059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/437)
> Removing special-case handling of two underscores

- ycmd/completers/python/jedi_completer.py
This is what we do when starting the ycmd server in YCM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/438)
> [READY] Use ToUnicode for HMAC secret in Python completer

- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
Modules from our `python-future` package may be overridden by ones from already installed packages: a package using the same name for its modules (ex: `builtins`) or a different version of `python-future`.
With a package installing a `builtins` module:
```sh
pip install pies2overrides
```
results in:
```
File "<string>", line 24, in <module>
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\setup.py", line 49, in SetUpYCM
base.LoadJsonDefaultsIntoVim()
File "C:\\Users\\micbou\\.vim\\bundle\\YouCompleteMe\\autoload\..\python\ycm\base.py", line 55, in LoadJsonDefaultsIntoVim
defaults = user_options_store.DefaultOptions()
File "C:\Users\micbou\.vim\bundle\YouCompleteMe\python\ycm\..\..\third_party\ycmd\ycmd\user_options_store.py", …
```
> [READY] Add python-future to sys.path just before packages path

- ycmd/default_settings.json
As Netrw is a browser for either local or remote files, it doesn't need completion. When YCM is compiled with `--clang-completer` and user doesn't have set `g:ycm_global_ycm_extra_conf`, browsing any directory in which doesn't have `.ycm_extra_conf.py` using Netrw makes YCM print an error message.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/456)
> Add netrw to the default filetype blacklist

- ci/travis/travis_install.sh
These Git commands:
```sh
git fetch --tags
git checkout v20160202
```
are not executed in the right folder when setting up pyenv on Travis. Execute them in the pyenv folder.
Instead of using `set +e`  and `set -e`, check if the `~/.pyenv` folder exists before cloning the pyenv repository.
Remove the `git fetch --tags` command because it is not needed after cloning a repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/459)
> [READY] Fix and improve pyenv setup in Travis script

- ci/travis/travis_install.sh
I made two mistakes in [previous PR](https://github.com/Valloric/ycmd/pull/459) (shame on me).
First mistake is that even if Travis don't cache anything, an empty directory is still created so the condition that checks if the `pyenv` directory doesn't exist is always false, resulting in a failure when nothing is cached. We fix this by checking if the `.git` folder exists instead.
Second mistake is the removal of the tags fetching: it is still useful if we bump the `pyenv` tag without clearing the cache (may not be a good idea though).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/460)
> [READY] Fix pyenv setup on Travis

- .gitignore
- build.py
We'll use this in YCM to ensure we start ycmd with the same version of
Python that was used for building the C++ libraries loaded into ycmd.
Related to https://github.com/Valloric/YouCompleteMe/issues/2136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/466)
> [READY] Storing path to Python used in build.py

- cpp/ycm/CMakeLists.txt
llvm.org provides prebuilt x86 binaries for Fedora 23, use them instead
of forcing the user to compile clang from source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/470)
> Use libclang prebuilt binaries even for 32 bit linux

- .travis.yml
Currently we use beta mono for some reason, which seems to be blowing up
in our face.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/473)
> Fixing travis Mac runs with stable mono

- ycmd/tests/cs/__init__.py
- ycmd/tests/cs/get_completions_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
By updating the `PyFlakes` component of `flake8` from 1.0.0 to 1.1.0 , I encountered the following errors when running the tests:
```sh
ycmd\tests\cs\__init__.py:65:24: F999 OnTravis may be undefined, or defined from star imports: builtins
ycmd\tests\cs\get_completions_test.py:413:5: F999 WaitUntilOmniSharpServerReady may be undefined, or defined from star imports: builtins
ycmd\tests\cs\get_completions_test.py:414:5: F999 StopOmniSharpServer may be undefined, or defined from star imports: builtins
```
Those are legitimate errors but instead of fixing them by adding the missing imports, I removed the usage of the concerned functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> [READY] Fix F999 issues reported by flake8

- ycmd/utils.py
Add a print in the codebase, start the ycmd server, and open the `stdout` logfile while the server is running. You will never see the result of the print unless you flush it or it is really long. This is due to buffering and it is not a desirable behavior for logs.
Note that the `stderr` logfile is not really affected by this because the `logging` module automatically flushes the output after each call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/478)
> [READY] Disable buffering for logfiles

- ycmd/handlers.py
- ycmd/tests/misc_handlers_test.py
We have a hard limit on the size of the request that ycmd can handle that is set to 1Mb. This is dictated by Bottle and there is no way around it.
When a client makes a request greater than 1Mb Bottle returns an error that is not generated by us and thus it is not a json response, but an html one, and it doesn't contain the HMAC header which causes  errors like #476. 
For now I've pushed only the failing test. Once I see it fail on Travis I will push the fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/482)
> [READY] Return a proper response when the request is too big.

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
Commonly used latex identifiers are not covered by the default regex.
The new regex is covered by test cases similar to the ones for perl and haskell.
With this regex it is easy to reference with YCM from all figures, sections, etc. in the document. Using `fig:` and so on is best practice in latex but I haven't found a spec that could serve as reference.
I wasn't able to run the full test suite (see message on ycmd-users) but I ran
```
nosetests ycmd/tests/identifier_utils_test.py
```
successfully.
Ultimatively, I think the user should be able to give a custom identifier regex for different filetypes in their .vimrc (and its analogue in other editors).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> Add tex identifier regex

- ycmd/completers/javascript/tern_completer.py
Since PR #450 seems stale (no answer from the author) and this is a rather important issue, I am opening a PR that supersedes it.
@puremourning suggested to use the `--ignore-stdin` option but it is not available in the last version of Tern (0.18.0) and it would require users to update their Tern version. In addition, the solution proposed here is already used by some plugin. See [this comment](https://github.com/ternjs/tern/issues/740#issuecomment-203979749).
Fixes Valloric/YouCompleteMe#2152
Closes #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/483)
> [READY] Always open a pipe to stdin when starting Tern

- ycmd/tests/__init__.py
- ycmd/tests/clang/__init__.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/go/__init__.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/python/__init__.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/__init__.py
- ycmd/tests/typescript/get_completions_test.py
When sharing the application in tests (using the `@SharedYcmd` decorator), the completions cache is not invalidated between each test. This can make a test not working like expected. For instance, the completions are detailed in the `GetCompletions_MaxDetailedCompletion_test` TypeScript test because of the previous test. However, the test is still passing because the `has_entries` matcher does not check for exact entries.
Improve the `GetCompletions_MaxDetailedCompletion_test` TypeScript test by checking that there are no detailed completions.
Invalidate the completions cache for all completers stored by the server state before running each test when sharing the application.
For now, I am only sending the test improvement so that we can confirm the test is failing because we don't clear …
> [READY] Clear completions cache when sharing the application between tests

- .travis.yml
- build.py
- ci/appveyor/appveyor_install.bat
- ci/travis/travis_install.linux.sh
- ci/travis/travis_install.osx.sh
- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
CMake is not able to find the Python libraries from `pyenv`. We can observe this on Travis. If we look at the build output of the Python 2.6 run on Linux, we have the following line during the CMake configuration:
```sh
-- Found PythonLibs: /usr/lib/libpython2.7.so (found suitable version "2.7.3", minimum required is "2.6")
```
which, in addition to be the wrong version, is the system library instead of the `pyenv` one. We confirm this by inspecting the `ycm_core.so` library from the build:
```sh
$ ldd ycm_core.so | grep python
libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0 (0x00007f0521fa1000)
```
Same issue with the Python 2.7 and 3.3 Linux runs although the library version is correct in these cases.
In the Travis configuration file, there is this comment:
> This is because stupid …
> [READY] Do not rely on CMake to find Python libraries

- build.py
- run_tests.py
With the changes from PR #481, the `--arch` option cannot be used anymore to specify the architecture on Windows because the architecture of the Python library is now the same as the Python interpreter running the `build.py` script and this architecture must match the one used to compile ycmd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/484)
> [READY] Remove architecture option in scripts

- DEV_SETUP.md
- Vagrantfile
- build.py
- run_tests.py
Adds some stuff that developers might find useful. I'm totally aware that these changes are probably most useful to me personally, so as usual I won't be offended if you don't want to merge them. Patch contains:
- instructions on debugging python and the python c++ module (it took me a *long* time to do this successfully)
- `--enable-debug` flag to the build
- `--dump-path` flag to `run_tests.py`. This is useful if you want to run `nosetests` directly (e.g. as `env PYTHONPATH=`./run_tests.py --dump-path` pdb nosetests ...`
- Parallels provider to the Vagrantfile (as I seem to have a moral objection to using virtual box when spend hard earned on Parallels :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> [READY] Add debugging instructions and tools

- build.py
We can't use `sys.exec_prefix` to find the Python libraries when running the `build.py` script in a virtual environment (like `pyvenv` or `virtualenv`) because the virtual environment doesn't contain the libraries.
We need to find them from the Python used to create the virtual environment. This is done by looking at the `LIBDIR` and `INCLUDEDIR` variables on Unix platforms and the `INCLUDEPY` variable on Windows from the `distutils.sysconfig` module. 
Fixes #486.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/488)
> [READY] Handle Python virtual environment in build script

- ci/appveyor/appveyor_install.bat
AppVeyor builds was broken by PR #493. A more recent version of Rust is needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/496)
> [READY] Bump Rust version to 1.8.0 on AppVeyor

- ycmd/completers/typescript/typescript_completer.py
This change was suggested by @puremourning in PR https://github.com/puremourning/ycmd-1/pull/1.
With this change, we have nothing to do if issue https://github.com/Microsoft/TypeScript/issues/3403 is fixed and we will still support TSServer versions without the fix.
Also, according to this comment in the code:
> The response message is a JSON object which comes back on one line. Since this might change in the future, we use the 'Content-Length' header.
we should use `read` instead of `readline`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/503)
> [READY] Improve newline TypeScript fix on Windows

- vagrant_bootstrap.sh
With the new `build.py` script, CMake now picks the `pyenv` Python library instead of the system one on our Vagrant configuration. This library needs to be built as a shared library. This is done by adding the `--enable-shared` flag to the `PYTHON_CONFIGURE_OPTS` like [we are doing on Travis](https://github.com/Valloric/ycmd/blob/master/ci/travis/travis_install.linux.sh#L22).
I can't test it myself (I can't make Vagrant work on Windows) so if someone could test it, that would be great. PR is marked as RFC for this reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/504)
> [READY] Build Python as a shared library on Vagrant

- build.py
This should take care of:
- system Python (with or without the `m` suffix in the library name for Python 3) on Linux, OS X, and Windows;
- `pyenv` Python on Linux and OS X (no `pyenv` on Windows);
- virtual environments (`virtualenv` and `pyvenv`) on Linux, OS X, and Windows.
Fixes #494.
Fixes #500.
Fixes #502.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2162.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2175.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/499)
> [READY] Rewrite FindPythonLibraries function in build script

- Vagrantfile
The current config has a bug. It wants to set a custom box for the
parallels VM provider but instead it overwrites the global config,
breaking the virtualbox provider (since that one can't use the parallels
box) on box creation.
The correct way to do a per-provider box is with an override param.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/511)
> [READY] Unbreak vagrant config for non-parallels

- .travis.yml
- ci/travis/travis_install.linux.sh
Since [LLVM APT repository is not available anymore](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html) and we were using it to install Clang and build ycmd with it, we go back to GCC to make the tests pass again on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/514)
> [READY] Switch back to GCC on Linux Travis

- ycmd/completers/python/jedi_completer.py
Now that [`JediHTTP` has an option to set its logging level](https://github.com/vheon/JediHTTP/pull/15), we can pass `ycmd` logging level to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/513)
> [READY] Pass ycmd logging level to JediHTTP

- ycmd/completers/go/go_completer.py
- ycmd/tests/go/__init__.py
- ycmd/tests/go/debug_info_test.py
- ycmd/tests/go/go_completer_test.py
- ycmd/tests/go/subcommands_test.py
This PR includes the changes mentioned in PR #282 for the Go completer and other small changes (listed in the commit message). The main change is the way we start the `gocode` daemon: instead of letting the client automatically start the daemon, we directly start it by running the `gocode` executable in server mode (using the `-s` parameter). This allows us to:
- get its PID;
- log stdout and stderr into files;
- enable `gocode` debug mode;
- set the port listened by `gocode`;
- terminate the process;
- implement the `_ServerIs*` methods;
- etc.
The second important change is the implementation of the `DebugInfo` method to show debug informations about the Go completer. The way informations are displayed will be adapted to other completers. Here's the output obtained in Vim when editing a …
> [READY] Overhaul Go completer

- ycmd/completers/python/jedi_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/python/user_defined_python_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
I'm marking as an RFC because there is also #424 which does almost the same thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/429)
> [READY] Search user defined python binary also in PATH

- build.py
Currently, the `build.py` script may found a debug version of the Python library instead of the release version because it searches through all the subdirectories of the standard library path. See issue #518 for details. The solution suggested by @jmenashe (using `LIBPL` variable) works fine for system Python but not for `pyenv` because there is no dynamic library in the directory returned by the `LIBPL` variable.
Taking this into account, we now search the Python library in a list of directories. On Windows, this list only contains one directory; the same one as before. On other platforms, it contains two directories:
- the one returned by the `LIBPL` variable (for system Python);
- the parent directory of the standard Python library modules (for pyenv).
Closes #518.
---
This change is …
> [READY] Use LIBPL variable to find Python library

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/get_completions_test.py
`http.client.NO_CONTENT` is an enumeration member while `response.status_code` is an int so we need to use an equality instead of an identity.
Added a test for when racerd returns a no content response.
On a side note, I think we should use [`requests.codes` instead of `http.client`](http://docs.python-requests.org/en/master/user/quickstart/?highlight=status_code#response-status-codes) in these situations. This would prevent this kind of issue (`requests.codes.no_content` is an int) and we would not have to import the `http.client` module. If you agree, I'll send a PR replacing all `http.client` occurences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/521)
> [READY] Use equality instead of identity when checking the status response in Rust completer

- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/hmac_plugin.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/subcommands_test.py
- ycmd/tests/diagnostics_test.py
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/javascript/event_notification_test.py
- ycmd/tests/javascript/get_completions_test.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/python/get_completions_test.py
See [the requests documentation](http://docs.python-requests.org/en/master/user/quickstart/?highlight=status_code#response-status-codes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/523)
> [READY] Use HTTP status codes from requests module instead of http one

- test_requirements.txt
- ycmd/tests/go/__init__.py
flake8 2.6.0 adds a new [check](https://gitlab.com/pycqa/flake8/blob/master/docs/warnings.rst):
> F405: `name` may be undefined, or defined from star imports: `module`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/526)
> [READY] Update flake8 requirement for tests and fix issue reported by the new version

- ycmd/tests/filename_completer_test.py
This test seems to pass on some machines but not on others and the
reason is different unicode sort order. The actual order doesn't matter
for the test so we specify that it doesn't matter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/527)
> [READY] Fix failing unicode test

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/get_completions_test.py
We were only checking that the path was set to something, not that there
was something there. This blows up in the user's face if they have
a common editor config across machines that gets synced but they forget
to actually place the required files in that location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/528)
> [READY] Also checking that rust_src_path exists

- ycmd/completers/completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/completer_test.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/javascript/event_notification_test.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/typescript/get_completions_test.py
This should cover the first point from https://github.com/Valloric/ycmd/pull/282#issuecomment-220062574
What I did was:
- Remove `StartServer` from completers
- Add `RestartServer` to completers
- Make `StopServer` unavailable to the end user but usable for testing porpuse
This change didn't involve the `Go` completer because I knew that @micbou was working on it.
I'm still not fully convinced about the C# completer, so I'm marking this as WIP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/506)
> [READY] Make completer interface uniform throughout completers

- ycmd/tests/rust/get_completions_test.py
See PR #523.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/531)
> [READY] Use status code from requests instead of http.client in Rust test

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/rust/get_completions_test.py
This PR is a proof that the changes introduced in PR #528 are not working as expected. By waiting for the racerd server to be ready at the start of the tests instead of waiting in the `IsolatedYcmd` decorator, the `GetCompletions_RustSrcPathSetButDoesntExist` test does not pass the CI runs. The reason is that when calling the `WaitUntilRacerdServerReady` function, the Rust completer is initialized and thus patching the `RUST_SRC_PATH` environment variable has no effect (the `_GetRustSrcPath` method is already called). In other words, the `GetCompletions_RustSrcPathSetButDoesntExist` test in its current state is identical to the `GetCompletions_WhenStandardLibraryCompletionFails_MentionRustSrcPath` one.
When patching `RUST_SRC_PATH` before waiting for racerd, the server will not return an …
> [READY] Check if Rust sources path exists at completer initialization

- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/handlers.py
- ycmd/tests/clang/debug_info_test.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/cs/debug_info_test.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/go/__init__.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/javascript/debug_info_test.py
- ycmd/tests/javascript/event_notification_test.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/python/__init__.py
- ycmd/tests/python/debug_info_test.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/rust/debug_info_test.py
- ycmd/tests/rust/get_completions_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/__init__.py
- ycmd/tests/typescript/debug_info_test.py
This PR makes the string returned by the `DebugInfo` method more consistent throughout completers. It also adds more informations:
- status of the `.ycm_extra_conf.py` file for the C-family completer;
- subserver PID when relevant (needed for the tests in PR #282);
- executable(s) used by the completer;
- current solution for the C♯ completer;
- Rust sources path for the Rust completer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/533)
> [READY] Uniformize debug informations

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Fixes #534 
Some of the pre-processor flags that we blacklist take file arguments, but were not registered as doing so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/547)
> [READY] Some of the preprocessor flags take file arguments

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/subcommands_test.py
- ycmd/tests/clang/testdata/FixIt_Clang_cpp11.cpp
Fixes #546 
We enable spell-checking to get better FixIt suggestions. The only time we don't is if the user's flags explicitly request it is disabled.
The change is in `PrepareFlagsForClang` because that is run both when getting the flags from the `FlagsForFile` function and when supplying them in the request. However, rather than having to update every test which does this to also expect `-fspell-checking` in the result, we use the same approach as `FlagsForFile` to allow the test system to disable adding it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/548)
> [READY] Always enable spell checking for better FixIts

- ycmd/handlers.py
- ycmd/tests/misc_handlers_test.py
See #536 for the rationale.
We choose to return `True` instead of an empty dictionary because it allows clients to use the response like this:
```python
response = ...
if response:
```
while it would be awkward with an empty dictionary.
Adds one test for each handler and updates the existing ones.
Closes #536.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/551)
> [READY] Return True as JSON in /load_extra_conf_file and /ignore_extra_conf_file handlers

- .coveragerc
- .gitignore
- ci/travis/travis_install.sh
- examples/example_client.py
- run_tests.py
- test_requirements.txt
- ycmd/__main__.py
- ycmd/handlers.py
- ycmd/tests/client_test.py
- ycmd/tests/shutdown_test.py
- ycmd/watchdog_plugin.py
- ycmd/wsgi_server.py
When killing a process on Windows, it is terminated like it received a `SIGKILL` signal on Linux. This means that @atexit functions will not be called. In our case, `ServerCleanup` is not executed:
completers `Shutdown` methods are not called, neither the `Shutdown` function in the global extra conf. In particular, subservers like `OmniSharpServer` and `Tern.js` are left running.
This issue happens in two situations:
- [a client like YCM terminates the ycmd server](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/youcompleteme.py#L175);
- [watchdog plugin pulls the trigger](https://github.com/Valloric/ycmd/blob/master/ycmd/watchdog_plugin.py#L92).
How to solve it?
First situation should be solved by adding a new handler `/shutdown` to properly shut down the ycmd server …
> [READY] Properly shut down on Windows

- ycmd/completers/typescript/typescript_completer.py
The exact same code is repeated in the `_StartServer` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/556)
> [READY] Do not set up log file multiple times during startup

- ycmd/wsgi_server.py
#282 breaks emacs-ycmd as it parses the standard output to get the port that ycmd is listening on.
While it probably makes sense for emacs-ycmd to specify the port, this is a regression so we re-introduce the output equivalent to [`waitress.serve`](https://github.com/Pylons/waitress/blob/3850e4c09aa9a55dc5c61985981b4ef719d5ebb8/waitress/__init__.py#L13-L14)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/555)
> [READY] Print a message equivalent to that printed by waitress.serve

- ci/appveyor/appveyor_install.bat
[Python 2.7.12 is now available on AppVeyor](https://github.com/appveyor/ci/issues/903). This version does not suffer from [the bug affecting 2.7.11](http://bugs.python.org/issue25824).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/571)
> [READY] Remove Python 2.7.11 workaround on AppVeyor

- .travis.yml
- ci/travis/travis_script.sh
Last version of flake8 cannot be used anymore on our code base with Python 2.6. In fact, [support for Python 2.6, 3.2 and 3.3 was dropped in version 3.0.0](http://flake8.pycqa.org/en/latest/release-notes/3.0.0.html#id1). I thought about freezing its version to the last working one (3.0.3) but new versions of flake8 may detect issues in the code that weren't found before (see https://github.com/Valloric/ycmd/pull/472 for instance). So, I went for disabling it for Python 2.6 (but not for Python 3.3 since it is still working with this version).
There is also the option to drop support for Python 2.6 (Python 3.3 is out of the question; it is [maintained until September 2017](https://www.python.org/dev/peps/pep-0398/#id11)). Thoughts?
---
This change is [<img …
> [READY] Disable flake8 for Python 2.6 on Travis

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/diagnostics_test.py
- ycmd/tests/cs/testdata/testy/DiagnosticRange.cs
For some diagnostics (especially warnings), the OmniSharp server returns a valid end of range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/575)
> [READY] Add end of range to diagnostics in C# completer

- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
In PR #448, I made the assumption that the `site-packages` paths are always placed after the standard library path so that if we insert the `python-future` module just before the first `site-packages` path, it would necessary be after the standard library. Turns out that it is not true when a `site-packages` path is added to the `PYTHONPATH` environment variable, e.g, when using the software [ROS](http://www.ros.org/). See issue https://github.com/Valloric/YouCompleteMe/issues/2186. When this happens, the `python-future` module will raise the following exception on Python 3:
```python
ImportError: This package should not be accessible on Python 3.
Either you are trying to run from the python-future src folder or
your installation of python-future is corrupted.
```
We prevent this by …
> [READY] Insert python-future module just after the standard library path

- ycmd/__main__.py
- ycmd/handlers.py
- ycmd/server_state.py
We don't want subservers from filetype completers to automatically shut down for inactivity while ycmd is still up so we periodically check if they are healthy (by calling the `ServerIsHealthy` method for each loaded filetype completer), which should effectively keep them alive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/576)
> [READY] Keep subservers alive while ycmd is up

- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
It turns out that using `get_python_lib` from the `sysconfig` module to find the standard library path in `sys.path` is not reliable. See issue https://github.com/Valloric/YouCompleteMe/issues/2293. Instead, we now look for the `os.py` file through all paths of `sys.path`. You may ask why `os.py` and not another file from the standard library. Python itself is using this file to [find the `sys.prefix` path](https://github.com/python/cpython/blob/master/Modules/getpath.c#L109) so it is a safe bet.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2293.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/579)
> [READY] Search os.py file to find standard library path in sys.path

- cpp/ycm/.ycm_extra_conf.py
- examples/.ycm_extra_conf.py
- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/testdata/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/client_data/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/general_fallback/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/noflags/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/test-include/.ycm_extra_conf.py
The `do_cache` item returned by the `FlagsForFile` function in `.ycm_extra_conf.py` is generally always set to `True` so let's make it optional with a default value of `True`. This simplifies a little the `.ycm_extra_conf.py` file and should be less confusing for users trying to understand it (cache + filename + flags? Sorry, can't compute).
This change is backward compatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/592)
> [READY] Make the do_cache item returned by FlagsForFile optional

- README.md
It makes sense to actually document the file format, as mentioned in https://github.com/Valloric/YouCompleteMe/issues/2310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/591)
> [READY] Document .ycm_extra_conf.py format

- ycmd/__main__.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/handlers.py
- ycmd/tests/client_test.py
- ycmd/tests/go/go_completer_test.py
- ycmd/tests/shutdown_test.py
- ycmd/utils.py
With this PR, we now remove `ycmd` logfiles at program termination and not only when receiving the `SIGTERM` or `SIGINT` signals. This fixes the long-standing bug where logfiles were never removed on Windows and the regression where they were not removed anymore on Unix platforms when receiving the `shutdown` request or through the watchdog plugin.
In addition, when shutting down a sub-server in a completer, we always wait for its process to be terminated before removing the logfiles. We need this on Windows because we cannot remove a file that it still used by a process on this platform. Most of the completers were already waiting but not the Python and C♯ completers.
Shutdown tests are updated to check if the logfiles are removed.
---
This change is [<img …
> [READY] Properly remove logfiles at program termination

- examples/example_client.py
When shutting down the server in the example client, we get the following traceback:
```python
File "./examples/example_client.py", line 494, in <module>
Main()
File "./examples/example_client.py", line 490, in Main
server.Shutdown()
File "./examples/example_client.py", line 116, in Shutdown
self.PostToHandlerAndLog( 'shutdown' )
File "./examples/example_client.py", line 120, in PostToHandlerAndLog
self._CallHttpie( 'post', handler, data )
File "./examples/example_client.py", line 249, in _CallHttpie
data )
File "./examples/example_client.py", line 220, in _HmacForRequest
self._hmac_secret ) ), 'utf8' )
File "./examples/example_client.py", line 276, in CreateRequestHmac
body = ToBytes( body )
File "./examples/example_client.py", line 266, in ToBytes …
```
> [READY] Fix shutdown request in example client

- ycmd/completers/cpp/flags.py
Fixes https://github.com/Valloric/YouCompleteMe/issues/2268
Apple seeded the GM release of macOS Sierra today, so will be publicly released fairly soon. Let's fix this before it breaks everyone.
Some parts of the standard libraries and include paths are now found in the platform-and-sdk-specific include areas. So to mitigate the number of problems this will cause, we just add a path which we know works.
This isn't super pretty (just hard-coding to MacOSX.platform), but it should work and should prevent random failures for most users. If users using iPhone/tvOS/etc. have problems, we can deal with them when they are raised. It's significantly more fiddly to test those setups.
Testing:
- install OSX Sierra GM seed in VM
- install YCM + dips
- write the following file:
```c++
#include …
```
> [READY] Fix default include paths for macOS Sierra

- ycmd/completers/javascript/tern_completer.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/javascript/testdata/simple_test.modified.js
The Tern server returns relative paths. When using a
.tern-project file, paths are returned relative to that file. When
no .tern-project file exists, paths are relative to the working
directory of the Tern server.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/596)
> [READY] Fix javascript subcommand errors for relative paths.

- ycmd/completers/go/go_completer.py
This fixes the go completer issue in #607.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/608)
> Use utils.OpenForStdHandle instead of open in go_completer.

- .travis.yml
- ci/travis/travis_install.sh
This fixes our OS X Travis builds. See https://github.com/Valloric/ycmd/pull/612#issuecomment-250829416.
As suggested by @vheon, I went for using the latest version available on Travis. This is currently OS X 10.11 (with Xcode 8) but according to [this blog post](https://blog.travis-ci.com/2016-09-15-new-default-osx-image-coming/), it could be soon macOS 10.12.
When using Python 2.7.6 on this new version of OS X, we get this error while installing (and compiling) the `psutil` dependency for our tests:
```sh
clang: error: no such file or directory: 'Python.framework/Versions/2.7/Python'
error: command 'clang' failed with exit status 1
```
This error goes away with Python 2.7.8 or later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [READY] Use OS X 10.11 on Travis

- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/clang/subcommands_test.py
This sacrifices accuracy for speed, so that it can be used from, say, a vim auto command.
I've had this for a _long_ time in my fork, and a number of people have requested PR for it, so here it is.
I know there was some discussion that is should be GetTypeImprecise, but personally I think that's a bit of a mouthful (fistful?) to type... Open to thoughts, though all my bindings are to `GetTypeQuick` so I am totally biassed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/609)
> [READY] Support GetTypeQuick completer subcommand in clang completer

- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/clang/subcommands_test.py
For consistency with other subcommands (`GoToImprecise` and `GetTypeImprecise`). We don't care about backward compatibility because this subcommand is not documented.
Added a test to check the list of subcommands defined by the Clang completer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/615)
> [READY] Rename GetDocQuick subcommand to GetDocImprecise

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Currently, if we find a compiler path in the list of flags and its name is not a C++ one, we set the language flag `-x` to `c`. This is unnecessary and even harmful in some cases because libclang guesses the language mode from the file extension. For instance, if the compiler name is `clang` and the file extension is `.cpp`, libclang will automatically use C++. We don't want to set the language to C in this case.
Fixes #538.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/603)
> [READY] Add language flag only for C++ compilers

- .travis.yml
- ci/travis/travis_install.linux.sh
Since we are planning to move the code base to C++11, using on Travis [the first version of GCC that fully support it](https://gcc.gnu.org/projects/cxx-status.html#cxx11) makes sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/616)
> [READY] Use GCC 4.8 instead of GCC 6 on Travis

- cpp/ycm/CMakeLists.txt
Found this discussion and just did what seemed to be left doing: https://gitter.im/Valloric/YouCompleteMe/archives/2016/04/03 and it worked on my freshly installed system with FreeBSD 11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/614)
> Support for libclang on FreeBSD added

- ycmd/tests/utils_test.py
- ycmd/utils.py
This is a (much) faster equivalent to
'\n'.join ( utils.ToUnicode( x ) for x in lines )
This is useful in the YCM routines that read in the entire buffer from
vim -- using this instead of ToUnicode reduces the keypress latency for
me on a large file (15+k loc) from ~100ms to <10ms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/617)
> Add utils.JoinLinesAsUnicode.

- ycmd/completers/general/filename_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/tests/filename_completer_test.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/javascript/event_notification_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
On Python 2, `os.getcwd` does not return a unicode object but bytes. Since we are internally always working with unicode objects, we need to use [`os.getcwdu`](https://docs.python.org/2/library/os.html#os.getcwdu) instead. Another reason to use the unicode version is that `os.getcwd` returns an invalid path for paths containing unicode characters on Windows.
The current directory is used in two places: the filename completer and the JavaScript completer. I added a test that currently fails for the filename completer but not for the JS completer as it needed too much refactoring.
For now, I am only pushing the test so that you can see the issue. I'll send the fix once the builds have failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [READY] Fix unicode issues when working with current directory on Python 2

- ycmd/extra_conf_store.py
See issue #618 and the comment.
I've verified that it does not affect the ycmd sources as we care a lot about ycmd loading speed. They are still compiled with this change.
Resolves #618.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/623)
> [READY] Do not compile ycm_extra_conf.py files

- ycmd/server_state.py
- ycmd/tests/test_utils.py
The set returned by `GetLoadedFiletypeCompleters` may contain `None` when a filetype exists with no semantic completer. This results in the following error in [`KeepSubserversAlive`](https://github.com/Valloric/ycmd/blob/master/ycmd/handlers.py#L315):
```python
Exception in thread Thread-1:
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/Users/zqb/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 323, in Keepalive
completer.ServerIsHealthy()
AttributeError: 'NoneType' object has no …
```
> [READY] Filter completers set to None in GetLoadedFiletypeCompleters

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/rust/testdata/docs.rs
I've updated `racerd` (https://github.com/jwilm/racerd/commit/e4731aaa5af6f972ae49ed84a7f570ad4ac5f4e5) to include the docs in its response, so we can now easily add this to ycmd.
Are there any docs which I should also update with this change when if it can be merged?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/628)
> Add GetDoc command for rust completer

- ci/travis/travis_install.linux.sh
- ci/travis/travis_install.sh
Our Linux builds on Travis are failing because the latest version of TSServer (2.0.6) is not working with Node.js 0.12 or older (see issue https://github.com/Microsoft/TypeScript/issues/11840) and the pre-installed version of Node.js on Travis is 0.10.36. [The TSServer issue is fixed upstream](https://github.com/Microsoft/TypeScript/pull/11845) but we can't wait for TypeScript 2.1 to be released. We have two options here:
- pin the version of TypeScript to the last working version (2.0.3);
- use a newer version of Node.js.
I went for the second solution as [support for the current version of Node.js on Travis will be dropped very soon](https://github.com/nodejs/LTS).
I removed the shell debugging option `set -v`  because when this option is enabled, the build is failing while running the …
> [READY] Use Node.js v4 LTS on Linux Travis

- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/typescript/event_notification_test.py
- ycmd/tests/typescript/testdata/buffer_unload/imported.ts
- ycmd/tests/typescript/testdata/buffer_unload/main.ts
Closes #541.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/542)
> [READY] Remove unloaded_buffer parameter

- ycmd/completers/all/identifier_completer.py
- ycmd/tests/identifier_completer_test.py
I was looking at the `identifier_completer` and its tests and I something do not adds up: from implementation of `_PreviousIdentifier` it seems that we are looking for the whole identifier before the cursor but there is a test that expects the function to return the identifier under the cursor. I think that the test is wrong also because for the identifier under the cursor we have a separate function `AddIdentifierUnderCursor`. Moreover the `PreviousIdentifier_ColumnInMiddleStillWholeIdent_test` test is passing because in the `_PreviousIdentifier` function we wrap the buffer; so in the test we first check for the previous identifier before the cursor, we don't find it because it ends after the `column` and then we check the previous line but since the buffer has only one line we check it …
> [READY] Avoid to wrap around when searching for previous identifier

- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/client_test.py
- ycmd/utils.py
This PR suppresses the `ResourceWarning` exceptions we get when running our tests on Python 3. For example:
``` sh
/home/travis/build/Valloric/ycmd/ycmd/completers/javascript/tern_completer.py:314: ResourceWarning: unclosed file <_io.BufferedWriter name=7>
self._server_handle = None
```
They are caused by setting to `None` a process handle while its standard piped streams are still open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/635)
> [READY] Fix warnings when resetting process handle

- ycmd/completers/all/identifier_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/identifier_completer_test.py
- ycmd/tests/testdata/basic.tags
Looking at the coverage of the Python layer of ycmd I noticed that one of the least tested file was the `identifier_completer.py` file. I understand that this file is actually just a thin wrapper around the cpp class (conversion to/from ycm_core data structure) so is understandable that is not 100% tested, but one big section that was not tested is the tag insertion: before inserting the file paths into an array and passing it to the cpp class we filter some paths based on the last update time of the file. So I extracted that section of the function as a generator and unit tested that function. I've marked this as WIP because I'm adding also a test that actually exercise the feature end-to-end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> [READY] Extract filtering of tags as a generator

- .gitignore
- TESTS.md
- build.py
- ci/travis/travis_install.linux.sh
- codecov.yml
- run_tests.py
This PR adds support for sending c++ coverage data (via gcov) to codecov.
The basic approach is to just enable building with gcov via the `-coverage` flag, and to tell `codecov` to ignore the `tests` and `BoostParts` directories.
Please excuse the insane number of commits, it was a big old slog to get this to actually work. I will squash when we're happy with it.
I've pulled out some highlights of what's included in this change:
I merged a change from my fork to add `--build-dir` to `build.py`. While I find this generally useful (as it reduces the rebuild time when developing and updating ycmd, without having to go through the full instructions), but it is also required here so that we keep the gcov data files around for `codecov` to pick them up. 
This could really have been a separate …
> [READY] Coverage for c++ code

- ycmd/completers/cpp/flags.py
- ycmd/handlers.py
This fixes new errors detected by the last version of `pycodestyle` (2.2.0), which is a dependency of `flake8`:
```
C:\projects\ycmd\ycmd\handlers.py:244:1: E305 expected 2 blank lines after class or function definition, found 1
C:\projects\ycmd\ycmd\completers\cpp\flags.py:374:1: E305 expected 2 blank lines after class or function definition, found 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/644)
> [READY] Fix flake8 errors

- ycmd/extra_conf_store.py
- ycmd/tests/extra_conf_store_test.py
- ycmd/tests/misc_handlers_test.py
- ycmd/tests/testdata/extra_conf/erroneous_extra_conf.py
- ycmd/tests/testdata/extra_conf/global_extra_conf.py
ycmd crashes when an error occurs while calling the `YcmCorePreload`, `VimLeave`, and `Shutdown` methods from the global extra conf file because these calls don't happen through a request but before starting the HTTP server (`YcmCorePreload`) or after stopping it (`VimLeave` and `Shutdown`). We need to catch these errors.
I added tests that cover all the `extra_conf_store` module except the `CallGlobalExtraConfYcmCorePreloadIfExists` and `Shutdown` functions which are covered by the shutdown tests.
Fixes #569.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/645)
> [READY] Catch exceptions from global extra conf

- .travis.yml
- TESTS.md
- ci/appveyor/appveyor_install.bat
- test_requirements.txt
Since we added C++ coverage with PR #636, our coverage reports are stuck with the following message:
```
Waiting for CI to finish and reports to complete processing. Please review commit coverage with caution, it may change.
```
This is caused by one of our Travis build (Linux, Python 3.3) that fails to upload coverage to codecov with this Python encoding error:
```
Error: 'latin-1' codec can't encode character '\u2013' in position 14079665: ordinal not in range(256)
```
I've contacted codecov support about this error and they suggested to use the bash uploader instead of the Python one.
Since the bash uploader cannot be used on AppVeyor, we still need `codecov` but not as a test dependency so we remove it from `test_requirements.txt` and install it directly in the AppVeyor script.
--- …
> [READY] Use codecov bash uploader on Travis

- ycmd/extra_conf_store.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/extra_conf_store_test.py
When the extra conf file is already loaded as a module and we attempt to force load it, instead of reusing the module, we reload it and lose its current state. This makes impossible to share variables between the `YcmCorePreload`, `VimLeave`, and `Shutdown` methods of the same global extra conf file.
For now, this PR only adds tests to show the issue. Once the builds have failed, I'll update it with one possible fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/651)
> [READY] Do not reload extra conf file

- .travis.yml
- ci/travis/travis_script.sh
- test_requirements.txt
See issue https://github.com/Valloric/ycmd/issues/660. This reverts PR #570 and adds a version requirement to Flake8 for Python 2.6 and 3.3. Once this is merged, I'll prepare a similar PR for YCM repository.
Fixes #660.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/665)
> [READY] Do not disable Flake8 on Python 2.6 Travis but restrict its version

- cpp/ycm/CMakeLists.txt
- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Fixes #659 
It turns out that only the libclang in Xcode 8 can handle the `@import Foundation;` syntax correctly.
It means the ycmd should be built  by `install.py --clang-completer --system-libclang`. 
Besides, I got to remove some tweaks in `CMakeLists.txt` and `flags.py` for the system's libclang to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/667)
> Support objc import module

- build.py
I was looking at the CMake config and noticed the `USE_DEV_FLAGS` option which i'd never seen before.
It seems a useful thing for devs (enables `-Wall -Wextra -Werror`), so enabling it with `--enable-debug` seems a solid move.
Tested by adding `int x;` in a random method and observing following build failure:
```
Bens-MBP:build ben$ ninja
[2/4] Building CXX object ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o
FAILED: ycm/CMakeFiles/ycm_core.dir/Candidate.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DBOOST_THREAD_DONT_USE_CHRONO -DUSE_CLANG_COMPLETER -DYCMD_CORE_VERSION=25 -Dycm_core_EXPORTS -I/Users/ben/.vim/bundle/YouCompleteMe-Clean/third_party/ycmd/cpp/ycm -I/Users/ben/.vim/bundle/YouCompleteMe-Clean/third_party/ycmd/cpp/ycm/ClangComp …
```
> [RFC] Enable dev flags when --enable-debug is supplied

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
In PR https://github.com/Valloric/ycmd/issues/643, we added a regular expression with a capturing group for JavaScript (and TypeScript) identifiers. Unfortunately, this makes [`re.findall` returns matches of this group instead of the whole pattern](https://docs.python.org/2/library/re.html#re.findall). Since this function is used in `ExtractIdentifiersFromText`, it breaks the extraction of identifiers in JS and TS files. We fix the issue by replacing the `(...)` pattern with `(:?...)`.
Added a test that fails without the fix:
```
AssertionError: ['var', 'foo', 'require', 'bar'] != ['v', 'f', 'r', 'b']
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/684)
> [READY] Use non-capturing group in JavaScript identifier regex

- cpp/BoostParts/CMakeLists.txt
- cpp/CMakeLists.txt
- cpp/ycm/tests/CMakeLists.txt
This suppresses the warnings raised while compiling Boost and gtest with MSVC. It also fixes the `MS_WIN64` redefinition warnings on 64-bit (this macro is already defined in Python headers).
These changes reduce the number of warnings from 310 to 3 on 32-bit and from 403 to 23 on 64-bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/685)
> [READY] Suppress MSVC warnings from third-party libraries

- cpp/ycm/ClangCompleter/CompilationDatabase.cpp
- cpp/ycm/ClangCompleter/CompilationDatabase.h
- cpp/ycm/ycm_core.cpp
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/__init__.py
- ycmd/tests/clang/debug_info_test.py
- ycmd/tests/clang/flags_test.py
Alternative implementation to : https://github.com/Valloric/ycmd/pull/679
See #679 for explanation and rationale.
Fixes: https://github.com/Valloric/ycmd/issues/489
Fixes: https://github.com/Valloric/YouCompleteMe/issues/2310 (sort of)
Fixes: https://github.com/Valloric/ycmd/issues/26
Fixes: https://github.com/Valloric/YouCompleteMe/issues/1981
Fixes: https://github.com/Valloric/YouCompleteMe/issues/1623 (sort of)
Fixes: https://github.com/Valloric/YouCompleteMe/issues/1622
Partly implements: https://github.com/Valloric/YouCompleteMe/issues/927
Fixes: https://github.com/Valloric/YouCompleteMe/issues/664
Fixes: https://github.com/Valloric/YouCompleteMe/issues/487
Fixes (discussion on): https://github.com/Valloric/YouCompleteMe/issues/174
This implementation is almost identical to the …
> [READY] Automatically load a compilation database if found

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
In `completers/cpp/flags.py`, `UserIncludePaths` expect `self.FlagsForFile` to return a `list`. But it return `None` when there's no flags available, causing `TypeError` and flickering in vim.
This PR changes three `return None` to `return []` in `FlagsForFile`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/682)
> Fix Type Error in Flags.FlagsForFile@completers/cpp/flags.py

- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/handlers.py
- ycmd/responses.py
- ycmd/tests/__init__.py
- ycmd/tests/clang/debug_info_test.py
- ycmd/tests/client_test.py
- ycmd/tests/cs/debug_info_test.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/go/debug_info_test.py
- ycmd/tests/go/go_completer_test.py
- ycmd/tests/javascript/debug_info_test.py
- ycmd/tests/misc_handlers_test.py
- ycmd/tests/python/debug_info_test.py
- ycmd/tests/rust/debug_info_test.py
- ycmd/tests/typescript/debug_info_test.py
Currently, the data returned by the `debug_info` handler is a block of text. This makes it difficult for clients to retrieve a specific information on the server (e.g. the path of the logfiles, the process identifier of a sub-server, etc.) or to customize the way it is displayed to the user.
We improve this by returning a dictionary instead of a string. Its structure is fully explained in [the new `debug_info` API documentation](http://micbou.github.io/ycmd/#path--debug_info).
There are two important changes on its content:
- add information on the Python interpreter used to start the ycmd server: its path and its version.
- move information on the `.ycm_extra_conf.py` file (its path and if it is loaded or not) from the Clang completer to ycmd itself since it is not supposed to be …
> [READY][API] Return debugging information as a dictionary instead of a string

- cpp/ycm/IdentifierUtils.cpp
This way I can have autocompletion in haskell using CTags.
This works with tools like ``hasktags`` that can generate the ``language:Haskell`` field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/693)
> Add haskell ctag support

- cpp/ycm/CMakeLists.txt
Use Xcode's libclang because it's always newer than Xcode command line tool's libclang
The current libclang in Xcode command line tool is too old.
Switch to libclang in Xcode 8 can fix this error.
**Actual**
```bash
./install.py --clang-completer --system-libclang
```
will output
```
Undefined symbols for architecture x86_64:
"_clang_parseTranslationUnit2FullArgv", referenced from:
YouCompleteMe::TranslationUnit::TranslationUnit(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<UnsavedFile, std::__1::allocator<UnsavedFile> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, …
```
> Use Xcode's libclang

- test_requirements.txt
Last version of psutil (5.0.1) is broken on Python 3.6 and Windows 64-bit. See issue https://github.com/giampaolo/psutil/issues/951. We exclude it from our test requirements. This fixes the builds with `arch=64` and `python=36` on AppVeyor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/695)
> [READY] Exclude psutil 5.0.1 from test requirements

- cpp/ycm/CandidateRepository.cpp
- cpp/ycm/CandidateRepository.h
I was looking at the coverage data and saw that this member function was not covered, so I checked and I found out that we actually never use it, so why keep it?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/708)
> Remove GetCandidatesForStrings taking CompletionData

- third_party/tern_runtime/package.json
Bumping to version 0.21.0
https://github.com/ternjs/tern/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/709)
> Ternjs version updated to package.json

- ycmd/tests/typescript/subcommands_test.py
TypeScript 2.2 improved the behavior of the `GoToType` subcommand. It now jumps to the class name instead of the `Class` keyword when the cursor is on an object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/712)
> [READY] Update GoToType test for TypeScript completer

- build.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/typescript_completer_test.py
On Debian-based distributions, `node` is installed by default as `nodejs`. See issue https://github.com/Valloric/YouCompleteMe/issues/2532. We fix that by looking for `nodejs` before `node`. We also need to change how we start the `tsserver` script because it contains the line `#!/usr/bin/env node` at the top.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/711)
> [READY] Fix finding node on Debian-based distributions

- .travis.yml
- ci/travis/travis_install.osx.sh
- ci/travis/travis_install.sh
Even if [Ubuntu 14.04 (Trusty) on Travis is still in beta](https://docs.travis-ci.com/user/trusty-ci-environment/), we should migrate to this version since it's closer to the versions that we support (16.04 and later). We should also stop using C♯ as the language to run our builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/713)
> [READY] Migrate to Ubuntu 14.04 and set language to generic on Travis

- ycmd/tests/client_test.py
OmniSharp server takes sometimes longer than 5 seconds to be ready on Travis so we increase the timeout to 10 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/715)
> [READY] Fix shutdown tests flakiness on Travis

- README.md
fixes "ERROR: msbuild or xbuild is required to build Omnisharp." when
calling ./build.py --all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/714)
> add xbuild to dependencies

- appveyor.yml
- build.py
- ci/appveyor/appveyor_build.bat
- run_tests.py
[Visual Studio 2017 (MSVC 15) was released this week](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes) and AppVeyor just added support for it.
MSVC 11 support was dropped in PR #701 so we remove it from our build script.
Closes #656.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/717)
> [READY] Add MSVC 15 support

- cpp/ycm/ClangCompleter/TranslationUnitStore.cpp
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/LetterNodeListMap.h
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/tests/LetterNode_test.cpp
- cpp/ycm/ycm_core.cpp
This is a continuation of #701. These changes will not be trivial and will need to be discussed before proceeding. At this moment only `std::hash` is working. The other two boost components will be discussed after agreeing that this hash implementation is fine.
~~Use `regex_search` and related from `std` namespace.~~
As it stands for now the regex part is the hardest to replce, so, in order not to make this PR big and drag it out, regex component will be in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/705)
> [READY] Switch from boost to std for hashes, arrays and regexes

- CONTRIBUTING.md
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/hmac_plugin.py
- ycmd/tests/client_test.py
- ycmd/utils.py
PR #722 was supposed to fix the issue where python-future imports any `test.py` file from the Python path. Unfortunately, it now happens on Python 3 instead of Python 2. See https://github.com/Valloric/YouCompleteMe/issues/2577 and https://github.com/PythonCharmers/python-future/issues/268 for an explanation. To avoid that, we reproduce the `urllib` compatibility fix from python-future in `ycmd/utils.py` but only for `urljoin` and `urlparse` since we don't need the other functions. We then import `urljoin` and `urlparse` from `ycmd.utils` instead of `future.moves.urllib.parse`.
Once this is merged, we'll do the same in YCM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/724 …
> [READY] Do not import urljoin and urlparse from python-future

- cpp/ycm/CMakeLists.txt
CLANG_MAJOR_VERSION and CLANG_MINOR_VERSION are not set and can't be used on the line 315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/725)
> Fix build with custom PATH_TO_LLVM_ROOT on Unix

- cpp/ycm/Utils.cpp
- cpp/ycm/tests/IdentifierUtils_test.cpp
- cpp/ycm/tests/testdata/directory.tags/.gitignore
In `IdentifierUtils.cpp` call to `ReadUtf8File()` is wrapped in a `try/catch` block, but `boost::filesystem::path`, on its own, never throws and never checks anything.
Instead there are methods like `boost::filesystem::is_regular_file(Path)` and `bost::filesystem::is_empty(Path)` that can be used to make sanity checks. `is_empty()` can throw `basic_filesystem_error` exception, as explained in the comment.
As an added bonus, the `catch` block is now reachable and should be covered with the new tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/726)
> [READY] Tag file reading sanity checks

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/diagnostics_test.py
YCMD already uses the TypeScript [tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)) for code completion. This change just implements diagnostic information (i.e. it shows compiler errors) similar to how it's implemented for C#.
Related: https://github.com/Valloric/YouCompleteMe/issues/2442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/718)
> Implement diagnostic information for TypeScript

- ycmd/tests/testdata/uni¢𐍈d€.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
`imp.load_source` raises a `UnicodeEncodeError` exception on Python 2 when loading a file whose path contains non-ASCII characters. See http://bugs.python.org/issue9425. Handle this case by reading the file and executing its content into a new module.
Fixes #727.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/728)
> [READY] Handle unicode pathname when loading source on Python 2

- cpp/ycm/ClangCompleter/CompletionData.h
Just like @oblitum  pointed out in [#701(comment)](https://github.com/Valloric/ycmd/pull/701#issuecomment-285920780), in `CompletionData.cpp` the `IdentifierEndsWith()` function is called only from function `RemoveTrailingParens()` and both functions are in unnamed namespace, so neither should have declaration in `CompletionData.h`.
@oblitum, in his comment, mentions that he had noticed more odd changes in that PR. While this commit fixes the change he explicitely mentioned I would like to wait and see if he has to add anything else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/732)
> Remove IdentifierEndsWith() declaration

- cpp/ycm/tests/ClangCompleter/ClangCompleter_test.cpp
Two `ASSERT` instead of `EXPECT` are necessary, the others are meaningful in case someone extends the tests somehow later on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/733)
> Make failing tests not lead to segmentation fault

- cpp/ycm/ClangCompleter/ClangUtils.cpp
- cpp/ycm/ClangCompleter/ClangUtils.h
According to the history of the file these functions are there since the file has been moved into the ycmd directory but right now they are not used, so I don't see a valid reason to keep them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/737)
> [READY] Remove unused functions in ClangUtils

- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/Utils.cpp
- cpp/ycm/Utils.h
The final piece in boost to std transition. Continuation of #705.
To make this work on linux with gcc `ReadUtf8File()` had to be changed to return a string vector. Otherwise no matches were ever found. Seems like a gcc bug.
That being said tests on linux are stll failing. On OSX on the other hand tests are all passing. The tests that are failing are:
- IdentifierCompleterTest.TagsEndToEndWorks
- IdentifierUtilsTest.ExtractIdentifiersFromTagsFileWorks
Even though the tests are failing on linux, reading the `basic.tags` file results in the expected behaviour (i.e. tags are provided for completion).
Note:
This leaves only boost::filesystem and boost::python. So `update_boost.py` should be updated, as well as some parts of `CMakeLists.txt` that mention boost threads that are no longer in use. …
> [READY] Remove Boost.Regex in favour of std variant

- cpp/ycm/Candidate.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/Result.h
According to the coverage and the build we never use the empty ctor of `Result` and its implementation is actually the same as the ctor taking one parameter with `false` as its parameter, so I didn's see a reason to maintain both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/739)
> [READY] Remove unused `Result` empty constructor

- cpp/ycm/CMakeLists.txt
We currently rename `libclang.so` because, for some reason, the linker looks for `libclang.so.x` instead of `libclang.so.x.y` when loading `ycm_core.so` (though we are explicitly linking it to `libclang.so.x.y`). The issue is that we are renaming it in the Clang distribution while we should rename it inside ycmd folder. In addition, we should create a symlink instead because we don't know if the linker will still look for `libclang.so.x` in future versions (this wasn't the case for prior versions of Clang). Finally, we should extract the version from the library filename to stay compatible with previous versions of Clang.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/744)
> [READY] Create a symlink instead of renaming libclang

- ycmd/completers/all/identifier_completer.py
- ycmd/identifier_utils.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/identifier_utils_test.py
When `collect_identifiers_from_comments_and_strings` is `0`, we are ignoring identifiers inside comments and strings from different languages. This is incorrect because we may ignore identifiers from comments that are not actual comments in the current working language. For instance, the `include` identifier will be ignored in the following C++ code:
```cpp
#include <iostream>
```
because we assume it's inside a Python-style comment.
The solution is to ignore identifiers from comments and strings according to filetype similarly to what we do to extract identifiers. For now, I've added support to the languages for which ycmd provides semantic completion. We'll add more with time.
--- …
> [READY] Ignore identifiers from comments and strings by filetype

- ycmd/completers/all/identifier_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/identifier_completer_test.py
When `collect_identifiers_from_comments_and_strings` is `0`, we should also ignore identifiers from comments and strings on the `InsertLeave` and `CurrentIdentifierFinished` events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/745)
> [READY] Ignore identifiers from comments and strings on InsertLeave and CurrentIdentifierFinished events

- update_boost.py
Boost's `b2` utility allows for building in parallel, using more jobs in the same way `make` allows - by specifying `-j` and the number of cores.
This change uses the same method of figuring out the number of jobs as `build.py`.
While boost isn't updated often, this was one of the things I had to change while working on #741, because it was annoying to work with multiple rebuilds on one core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/748)
> [READY] Build boost in parallel

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
According to [latest specifications](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram), single character words (an obvious example is the `a` HTML tag) and words starting with a unicode character are valid CSS identifiers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/749)
> [READY] Improve CSS identifier regex

- cpp/ycm/ClangCompleter/ClangCompleter.h
- cpp/ycm/ClangCompleter/CompletionData.h
- cpp/ycm/ClangCompleter/Documentation.h
- cpp/ycm/ClangCompleter/Location.h
- cpp/ycm/ClangCompleter/TranslationUnit.h
- cpp/ycm/ClangCompleter/TranslationUnitStore.h
- cpp/ycm/tests/ClangCompleter/ClangCompleter_test.cpp
- cpp/ycm/tests/ClangCompleter/TranslationUnit_test.cpp
- cpp/ycm/tests/testdata/basic.cpp
While this won't make the clang completer coverage reach 100%, it should singnificantly improve it. These tests mostly deal with what happens when clang can't parse the TU, but also with testing all kinds of `GoTo` jumps.
What is left not covered are some partials and more than a few `==` operator overloads that are required for `boost::python`, but are not explicitly used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/751)
> [READY] Improve clang completer coverage

- ycmd/tests/client_test.py
OmniSharp server now takes about 15 seconds to be ready on Linux Travis. Increase timeout to 20 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/755)
> [READY] Increase timeout in shutdown tests

- .travis.yml
Our homu instance gets travis events through GitHub status events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/756)
> [READY] Removing unnecessary travis webhook

- ycmd/tests/client_test.py
- ycmd/tests/test_utils.py
20 seconds is not long enough for the C# server to be ready on Linux Travis. Increase timeout to 30 seconds. Rewrite `WaitUntilCompleterServerReady` to accept a timeout parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/757)
> [READY] Further increase timeout in tests

- examples/example_client.py
- ycmd/handlers.py
- ycmd/tests/misc_handlers_test.py
The `ready` endpoint currently accepts two parameters:
- `subserver`: return `True` if the subserver for the given filetype is ready;
- `include_subservers`: return `True` if the C# subserver is ready.
From this, it's obvious that we don't need the `include_subservers` parameter and that we should drop it in favor of `subserver`. We don't use this parameter anywhere in our code base and, AFAIK, no clients rely on it so we can safely remove it.
For consistency, we update the `healthy` endpoint by renaming its `include_subservers` parameter to `subserver` and extending it to any filetype. For the same reason as above, this shouldn't break anything.
Add tests for these two endpoints.
--- …
> [READY][API] Drop include_subservers parameter in healthy and ready endpoints

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Historically it hasn't been possible to use ycmd with iOS projects for 2 reasons:
1. Opensource libclang seems to be unable to build the system headers for th iOS platform. It's not known _why_ this is, but it is known that Apple patch clang in Xcode
2. ycmd's flag handling hasn't played well with the myriad switches that are needed to build using iOS system headers
The advice has always been to use `--system-libclang` in such environments. However, this only solves point 1.
For a completely unrelated reason I was today testing something which required using the iOS system headers (from `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk`) and found that even with Apple's libclang I wasn't able to compile even a simple c program.
The issue …
> [ACTUALLY READY] Allow compilation for iOS projects

- run_tests.py
The option replacing `--no-clang-completer` ends with a `s`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/764)
> [READY] Fix warning message when the --no-clang-completer option is specified

- build.py
As explained in #765, [the OmniSharpServer project file specifies version 4.0 of .NET Framework](https://github.com/OmniSharp/omnisharp-server/blob/e1902915c6790bcec00b8d551199c8a3537d33c9/OmniSharp/OmniSharp.csproj#L10) but recent versions of Visual Studio and Mono dropped this version; at least 4.5 is required.
Specifies this version through the `/property:TargetFrameworkVersion` flag in the build script.
Fixes https://github.com/Valloric/ycmd/issues/765.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/767)
> [READY] Specify .NET Framework 4.5

- test_requirements.txt
Reports from Codecov show that some lines of `ycmd/utils.py` are not covered while they should be. For instance, [the `_GetWindowsExecutable` function](https://codecov.io/gh/Valloric/ycmd/src/master/ycmd/utils.py#L218) is not covered but [we are testing it through the `FindExecutable` function](https://github.com/Valloric/ycmd/blob/1ebfbd4ca5bbfcb49817967dfc9fbc3f82312f66/ycmd/tests/utils_test.py#L512-L549). This can be confirmed by looking at the [AppVeyor uploads on Codecov](https://codecov.io/gh/Valloric/ycmd/commit/1ebfbd4ca5bbfcb49817967dfc9fbc3f82312f66/build). These reports contain the lines 218-230 for the `utils.py` file.
Codecov doesn't report these lines as covered because of [a change introduced in the version 4.4 of coverage.py](https://bitbucket.org/ned/coveragepy/issues/526/ …
> [READY] Require coverage.py package older than version 4.4

- cpp/ycm/tests/ClangCompleter/ClangCompleter_test.cpp
- cpp/ycm/tests/testdata/basic.cpp
This should cover the last non trivial and completely non covered function in C++ layer (and ycmd in general) that's not boost poilerplate code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/772)
> [READY] Clang completer - optional completion chunk test

- cpp/CMakeLists.txt
CentOS/RHEL users don't have a new enough compiler to build ycmd, but we can tell them the best way to get one, because we're nice like that.
See also https://github.com/Valloric/YouCompleteMe/wiki/Full-installation-on-CentOS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/775)
> [READY] Add some advice for CentOS/RHEL users

- cpp/ycm/benchmarks/IdentifierCompleter_bench.cpp
When running the `benchmark.py` script with the `--enable-debug` option on Linux, the compilation fails with the following error:
```
IdentifierCompleter_bench.cpp:26:39: error: unused parameter ‘state’ [-Werror=unused-parameter]
void SetUp( const benchmark::State& state ) {
^
```
This is fixed by removing the parameter name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/778)
> [READY] Fix unused variable in benchmark setup

- cpp/CMakeLists.txt
Shamefully, I actually only tested CentOS at home.
Tested this change at work on RH 6.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/779)
> [READY] Fix RHEL detection. It actually reports as RedHatEnterpriseServer

- cpp/ycm/CandidateRepository.cpp
This is an obvious memory leak given `CandidateRepository` destructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/780)
> [READY] Fix memory leak when clearing candidates

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Like `--sysroot=`, the `-include-pch` flag must be listed before `-include` because the latter is a prefix of the former and the `_MakeRelativePathsInFlagsAbsolute` function checks prefixes in the list order to extract paths.
Fixes https://github.com/Valloric/ycmd/issues/782.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/783)
> [READY] Fix -include-pch flag handling when converting relative paths to absolute

- ycmd/completers/rust/rust_completer.py
The `rust_src_path` option provided by the user may contain a `~` or an environment variable so we should expand it. See PR https://github.com/Valloric/YouCompleteMe/pull/2695.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/784)
> [READY] Expand Rust source path

- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
See https://docs.python.org/3/using/windows.html#embedded-distribution
In the embedded distribution, the Python standard library is provided as
a zip archive containing pre-compiled and optimized .pyc files.  This
means that looking for 'os.py' to determine the standard library path
doesn't work.
This patch supports locating the standard library path when an embedded
distribution is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/786)
> Support using Python embedded distribution.

- clang_includes/include/avx512fintrin.h
- cpp/ycm/CMakeLists.txt
[Clang 4.0.1 was just released](http://lists.llvm.org/pipermail/llvm-announce/2017-July/000074.html). We download the Debian 8 binaries on Linux as no other binaries are available for this platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/790)
> [READY] Update Clang to 4.0.1

- ycmd/bottle_utils.py
Fixes: #670
Currently ycmd is only working with bottle that comes with ycmd.
It is really an old version of bottle and ycmd is not compatible with
recent version.
A Debian package must use system-dependencies instead of third_party modules.
This patch is updating bottle and making ycmd to compatible with latest
bottle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/673)
> Update bottle to 0.12.13

- .travis.yml
- ci/travis/travis_install.linux.sh
- cpp/ycm/IdentifierUtils.cpp
Compiling with Clang 3.4 results in the following error:
```
cpp/ycm/IdentifierUtils.cpp:120:12: error: chosen constructor is explicit in copy-initialization
return {};
^~
/usr/include/c++/v1/map:838:14: note: constructor declared here
explicit map(const key_compare& __comp = key_compare())
^
1 error generated.
```
See issue https://github.com/Valloric/ycmd/issues/791.
As Valloric suggested, this PR adds a Linux build with Clang 3.4 on Travis. We are supposed to support Clang 3.3 but 3.4 is the oldest version available on Travis.
I'll update the PR with the fix once the Clang build failed.
Fixes #791.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/793)
> [READY] Fix compilation with Clang 3.4

- build.py
In a virtualenv, `sys.prefix` points to the virtualenv directory. Use `sys.real_prefix` instead.
Fixes #798.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/799)
> [READY] Fix virtualenv prefix in build script

- cpp/ycm/CMakeLists.txt
This PR simply add usual path to llvm lib on FreeBSD system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/804)
> add FreeBSD support for detetecting libclang

- build.py
If ycmd compilation is successful but installing a completer fails, we don't create the `PYTHON_USED_DURING_BUILDING` file. This can be an issue if the user gives up on the completer installation and the client uses the Python from this file to start ycmd (like YCM does). This could explain issue https://github.com/Valloric/YouCompleteMe/issues/2729.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/808)
> [READY] Write python used during build before installing completers

- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/Utils.cpp
- cpp/ycm/Utils.h
- cpp/ycm/tests/IdentifierUtils_test.cpp
- cpp/ycm/tests/Utils_test.cpp
- cpp/ycm/tests/testdata/basic.tags
When a language from a tags file is unknown, set the filetype to its name in lowercase. This allows the use of tags for custom languages.
Fixes #809.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/810)
> [READY] Support unknown languages from tags

- ycmd/tests/__init__.py
- ycmd/tests/clang/__init__.py
- ycmd/tests/clang/debug_info_test.py
- ycmd/tests/clang/diagnostics_test.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/extra_conf_store_test.py
- ycmd/tests/filename_completer_test.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/misc_handlers_test.py
- ycmd/tests/python/__init__.py
- ycmd/tests/python/user_defined_python_test.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/test_utils.py
[Dropping the `UserOption` function was mentioned some time ago](https://github.com/Valloric/ycmd/pull/699#issuecomment-277072790) in PR https://github.com/Valloric/ycmd/pull/699:
> This function updates an option and reverts it by replacing our ServerState instance with a new one, losing all references to the already initialized completers. In particular, this makes it impossible to stop a completer server (e.g. racerd) that was already started once this function is called.
We replace its usage with the `IsolatedYcmd` functions, which are extended with a parameter to customize options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/812)
> [READY] Replace UserOption with IsolatedYcmd

- ycmd/extra_conf_store.py
- ycmd/tests/extra_conf_store_test.py
- ycmd/tests/test_utils.py
When a `.ycm_extra_conf.py` file is found, ycmd determines if this file should be white/blacklisted by checking that its path matches one of the patterns from [the `extra_conf_globlist` option](https://github.com/Valloric/YouCompleteMe#the-gycm_extra_conf_globlist-option). This is done by converting the `.ycm_extra_conf.py` path and the patterns to absolute paths through [the `os.path.abspath` function](https://docs.python.org/2/library/os.path.html#os.path.abspath). However, this function doesn't resolve symbolic links. This means that if a pattern in `extra_conf_globlist` contains a symbolic link, any `.ycm_extra_conf.py` file that should be matched by this pattern if the symlink was resolved, won't be white/blacklisted.
This is fixed on UNIX by replacing `os.path.abspath` with [the …
> [READY] Resolve symlinks in extra conf glob pattern

- cpp/ycm/PythonSupport.h
- cpp/ycm/benchmarks/BenchUtils.cpp
- cpp/ycm/benchmarks/BenchUtils.h
- cpp/ycm/benchmarks/IdentifierCompleter_bench.cpp
- cpp/ycm/benchmarks/PythonSupport_bench.cpp
[The `CandidatesForQuery` method](https://github.com/Valloric/ycmd/blob/2575bdb8c83dd5ace3d6f3d72a3425fdf2c18f5e/cpp/ycm/IdentifierCompleter.h#L69) is not the only place where performance is critical. There is also [the `FilterAndSortCandidates` function](https://github.com/Valloric/ycmd/blob/2575bdb8c83dd5ace3d6f3d72a3425fdf2c18f5e/cpp/ycm/PythonSupport.h#L29) which is used in the Python layer to filter and sort candidates returned by completers other than the identifier one (while `CandidatesForQuery` is specific to the identifier completer). We should add benchmarks for this function too.
It would be great for these benchmarks to be based on real usage (e.g. case 1 or 2 from https://github.com/Valloric/YouCompleteMe/issues/2668). This could be done by storing the candidates in a file …
> [READY] Add FilterAndSortCandidates benchmarks

- README.md
- cpp/ycm/.ycm_extra_conf.py
- examples/.ycm_extra_conf.py
- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Since PR https://github.com/Valloric/ycmd/pull/680, all the infrastructure is here to convert any relative paths in the list of flags from the `.ycm_extra_conf.py` file to absolute ones. We just need to use the `_MakeRelativePathsInFlagsAbsolute` function.
This PR adds a new optional key `working_directory` to the dictionary returned by the `FlagsForFile` function in the `.ycm_extra_conf.py` file. This option allows specifying the working directory i.e. the directory for which the paths in the list of flags are relative to.
Update YCM's own `.ycm_extra_conf.py` file to reflect this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/795)
> [READY] Add an option to make relative paths in flags from extra conf absolute

- .gitignore
Since npm 5 (it would appear), npm is now writing a new file to our `tern_runtime` directory `package-lock.json`, which appears as an untracked file. 
The [purpose of the file](https://docs.npmjs.com/files/package-lock.json) seems to be to  lock the entire hierarchy of dependencies.
In theory, we _could_ commit this file and only update it when our dependencies dependencies (and their dependencies) update, but this just seems like a _lot_ of pointless admin.
So we just ignore the file and stick with what we have.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/821)
> [READY] Ignore package-lock.json.

- README.md
Used a single quote to close the markdown code instead of a back quote.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/823)
> [READY] Fix markdown code in README

- cpp/ycm/CMakeLists.txt
This PR simplifies the way we determine `PATH_TO_LLVM_ROOT` for Clang prebuilt binaries by using a glob pattern.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2756.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/820)
> [READY] Improve LLVM root path search for prebuilt binaries

- cpp/ycm/Utils.cpp
- cpp/ycm/Utils.h
This allows the compiler to inline these functions and thus gives a small performance boost as these functions are used a lot when filtering and sorting candidates.
Suggested by @puremourning in PR https://github.com/Valloric/ycmd/pull/810.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/822)
> [READY] Inline critical utility functions

- ycmd/completers/general/filename_completer.py
- ycmd/tests/filename_completer_test.py
There is no point in sorting header paths and removing duplicates by converting the list to a set in the filename completer since the paths are going through the `FilterAndSortCandidates` function even when the query is empty (thanks to PR #819).
Rewrite the filename completer tests to use the `contains_inanyorder` and `empty` matchers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/824)
> [READY] Do not sort header paths in filename completer

- run_tests.py
If a user has Python 2 and 3 installed on its system with flake8 and nose available in the PATH for both Pythons, `run_tests.py` may execute flake8 or nose from a different Python that the one used to run the script and build ycmd. For instance, if the script is executed in Python 3 but nose from Python 2 is found in the PATH, the following error occur when running the tests:
```
Failure: ImportError (dynamic module does not define init function (initycm_core)) ... ERROR
```
The solution is to run flake8 and nose as modules using `sys.executable` with [the `-m` option](https://docs.python.org/2.7/using/cmdline.html#cmdoption-m). Due to [a bug (feature?) in Python 2](http://bugs.python.org/issue2751), we need to specifically call the `__main__` function.
--- …
> [READY] Run flake8 and nose as modules

- ycmd/completers/completer.py
- ycmd/completers/completer_utils.py
- ycmd/default_settings.json
- ycmd/handlers.py
- ycmd/tests/clang/get_completions_test.py
Add the `max_num_candidates` option to limit the number of non-identifier candidates returned by ycmd. Its default value is set to 50 as this seems a good compromise between performance and the amount of candidates shown to the user (10 candidates like for identifiers would be too low).
Limiting the number of candidates does not only improve performance when sorting them (see PR #825) but also when sending the response to the client as the response is smaller and when clients are populating the completion menu since there are less candidates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/830)
> [READY] Add max_num_candidates option

- ycmd/completers/all/identifier_completer.py
- ycmd/identifier_utils.py
- ycmd/tests/identifier_completer_test.py
- ycmd/tests/identifier_utils_test.py
When `collect_identifiers_from_comments_and_strings` is `0`, we are replacing comments and strings with empty strings before extracting the identifiers. If one of these comments or strings span multiple lines, the current line number `line_num` may become invalid and, in that case, the identifier completer will fail to add the previous identifier on the `CurrentIdentifierFinished` event:
As you can see, the `test` identifier is properly extracted before the comment but not after.
Another issue with multiline comments and strings is that, when adding an identifier under the cursor on the `InsertLeave` event, we only remove comments and strings on the current line. This is incorrect if the current line is in the middle of a multiline comment or string:
The `test` identifier is extracted …
> [READY] Fix multiline comments and strings issues

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/get_completions_test.py
In Valloric/YouCompleteMe#2379 there was talk about enabling ycmd to check rust src path provided by rustup.
This allows users to have rust completion with zero ycmd configuration.
Tests are not included because tests themselves should behave differently based on how rustup was used and I'm not sure how to test that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/785)
> [READY] Let ycmd check rustup configured path as the last means to finding rust src path

- cpp/ycm/.ycm_extra_conf.py
This PR updates the list of flags defined in ycmd `.ycm_extra_conf.py` file by:
- adding Python include path using [`get_python_inc`](https://docs.python.org/3/distutils/apiref.html?highlight=get_python_inc#distutils.sysconfig.get_python_inc) so that it works on all platforms;
- adding Google benchmark include path;
- removing the `-std=c++11` flag on Windows because the standard library in recent versions of MSVC requires at least C++14;
- removing the comment about `-std=`: only the `-x` flag should be specified to distinguish C++ headers from C ones.
Tested on Ubuntu 16.04, macOS, and Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/833)
> [READY] Update ycmd extra conf

- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- ycmd/tests/clang/subcommands_test.py
The `GetType` subcommand from the Clang completer is supposed to return the canonical type of a symbol if it differs from its type. However, in some cases, both types are displayed even if identical. For instance, `GetType` on `bar` in the following code:
```c++
char *foo
auto bar = foo
```
returns `char * => char *` instead of simply `char *`.
This happens because Clang returns that the canonical type is different from the actual type even though they result in the same string. The solution is to only return the canonical type if the strings are different.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/835)
> [READY] Do not return canonical type if identical to type

- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
The changes needed for `--system-libclang` and `--system-boost` to work on Gentoo are:
- Always passing `-lboost_python` even on python3
- Looking in a ridiculous path (`/usr/lib/llvm/${MAJOR_VERSION}/lib{64,32}/`) to find libclang.so
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/837)
> [READY] Allow system boost and system libclang usage

- cpp/ycm/CMakeLists.txt
[`SYSTEM_IS_FREEBSD` is defined at the top of `cpp/CMakeLists.txt`](https://github.com/Valloric/ycmd/blob/fd32091dedaf57acce40edc2d7c08950cccfd9b7/cpp/CMakeLists.txt#L39).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/839)
> [READY] Use SYSTEM_IS_FREEBSD variable when downloading Clang binaries

- examples/example_client.py
- ycmd/tests/client_test.py
When running the shutdown tests on Windows, ycmd is unable to remove the options file that contains the HMAC key. This is because the file is kept open by the tests while the server is started and a file cannot be removed on Windows if another process is holding it open. We fix this by closing the options file as soon as possible.
Also, we don't need to manually flush the file as it is automatically flushed when closing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/841)
> [READY] Close options file before starting server

- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
Detecting that the distribution is Red Hat or CentOS by checking if the `/etc/redhat-release` file contains `Red Hat` (respectively `CentOS`) is more reliable than using `lsb_release` as this tool may not be available on a clean installation (e.g. CentOS 6.5).
Tested on CentOS 6.5 and 7.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/840)
> [READY] Improve Red Hat and CentOS detection

- ycmd/tests/rust/debug_info_test.py
Since PR https://github.com/Valloric/ycmd/pull/785, the Rust debug info test fails if the Rust sources have been downloaded with rustup on the machine running the tests. We should check that the Rust sources value is either `None` or a string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/850)
> [READY] Fix Rust debug info test when rustup is installed

- build.py
- run_tests.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/rust/rust_completer.py
It's more intuitive for users if completer options are named after the language and not after the semantic engine e.g. `--rust-completer` instead of `--racer-completer`. To preserve backward compatibility, we keep the old options but deprecate them by hiding them from the `--help` output. We don't rename `--clang-completer` since `clang` is really well known and an appropriate name to designate C-family languages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/851)
> [READY] Rename completer options

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
This is the yearly update to fix the latest macOS incompatibilities.
It seems with Xcode 9 (for reasons I really don't understand), having both the Xcode "command line tools" _and_ Xcode in your include paths leads to errors being raised in standard headers.
This change simply only adds a single set of system headers from a single toolchain on macOS.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2790
Fixes https://github.com/Valloric/ycmd/issues/844
Fixes https://github.com/Valloric/YouCompleteMe/issues/2536
This is a quicker and probably less contentious solution than https://github.com/Valloric/ycmd/pull/853
This is sort of equivalent to https://github.com/Valloric/ycmd/pull/854, but the implementation is simpler and has working tests.
Repro steps:
* with both Xcode and CLT …
> [READY] Only include one of the possible mac toolchains in the include paths

- ycmd/completers/completer_utils.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/general/filename_completer.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/subcommands_test.py
- ycmd/tests/clang/testdata/test-include/main.cpp
- ycmd/tests/filename_completer_test.py
- ycmd/tests/get_completions_test.py
This PR fixes the issue where completion is interrupted after inserting a non-identifier character in include statements. See issues https://github.com/Valloric/YouCompleteMe/issues/281 and https://github.com/Valloric/YouCompleteMe/issues/1553.
This is done by moving the include completion logic from the filename completer to the Clang one and by setting the start column to the right position thanks to PR https://github.com/Valloric/ycmd/pull/681. A benefit of moving the logic to the Clang completer is that `<C-Space>` now works in include statements.
Here's a demo before the changes:
and after:
You'll notice that no error is shown to the user after inserting the dot.
Fixes https://github.com/Valloric/YouCompleteMe/issues/281.
Fixes https://github.com/Valloric/YouCompleteMe/issues/1553. …
> [READY] Improve completion of include statements in C-family languages

- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/python/subcommands_test.py
Include [Jedi 0.11.0](https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0110-2017-09-20).
Update descriptions in `GoToReferences` test.
Use the new shutdown handler introduced in PR https://github.com/vheon/JediHTTP/pull/39 to stop JediHTTP.
Catch exception from shutdown request in semantic completers (when appropriate) so that cleaning up is done even if the request failed.
Fix `TypeError` exception trying to remove the `None` logfile when stopping the server with the `StopServer` subcommand then restarting it with `RestartServer`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/856)
> [READY] Update JediHTTP

- ycmd/extra_conf_store.py
- ycmd/tests/__init__.py
- ycmd/tests/clang/__init__.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/go/__init__.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/python/__init__.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/__init__.py
The `extra_conf_store` module being a singleton, its state is modified when loading or ignoring a `.ycm_extra_conf.py` file during an isolated test, which may affect other tests. To avoid that, we restore its state (more precisely [its singleton variables](https://github.com/Valloric/ycmd/blob/bfe0db9f707e08babdf96bdeadf14708db851163/ycmd/extra_conf_store.py#L43-L46)) at the end of each isolated test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/852)
> [READY] Restore extra_conf_store singleton after isolated tests

- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- ycmd/tests/clang/diagnostics_test.py
- ycmd/tests/clang/testdata/location_extent.cc
We currently use the following (convoluted) method to compute the location extent of a diagnostic i.e. the range of the identifier where the diagnostic occurred:
- obtain a range from [the `clang_getCursorExtent` function](https://clang.llvm.org/doxygen/group__CINDEX__CURSOR__SOURCE.html#ga79f6544534ab73c78a8494c4c0bc2840), which is supposed to contain our identifier;
- extract all the tokens from that range with [`clang_tokenize`](https://clang.llvm.org/doxygen/group__CINDEX__LEX.html#ga6b315a71102d4f6c95eb68894a3bda8a);
- find the token with the same starting position as the diagnostic;
- use the length of that token to get the ending position;
- compute the range.
Unfortunately, this doesn't always work as shown in issue https://github.com/Valloric/ycmd/issues/859, In that case, …
> [READY] Fix empty location extent after missing semicolon

- ycmd/completers/all/identifier_completer.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/general/filename_completer.py
- ycmd/completers/javascript/tern_completer.py
Latest version of Flake8 reports the following errors:
```
ycmd\completers\all\identifier_completer.py:126:7: E722 do not use bare except'
ycmd\completers\cpp\clang_completer.py:556:3: E722 do not use bare except'
ycmd\completers\general\filename_completer.py:149:3: E722 do not use bare except'
ycmd\completers\javascript\tern_completer.py:250:5: E722 do not use bare except'
```
We fix them by catching `Exception` and logging the exception when appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/863)
> [READY] Fix bare except statements

- build.py
When passing the `--build-dir` option to the build script, we delete the directory if it already exists. Not only this is dangerous (consider running the command `./build.py --build-dir /`), it also defeats the purpose of this option which is to do incremental builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/862)
> [READY] Do not delete build directory when running script with --build-dir

- ycmd/completers/completer_utils.py
The objc triggers are perfectly valid in objcpp, so use them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/865)
> Use objc triggers for objcpp

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/subcommands_test.py
TypeScript 2.6.1 introduced a bug in TSServer where NPM warnings are printed on stdout at startup:
```
npm WARN 2.6 No description
npm WARN 2.6 No repository field.
npm WARN 2.6 No license field.
```
See issue https://github.com/Microsoft/TypeScript/issues/19660. The TypeScript completer chokes on this output as it always expects a HTTP-like response from TSServer and assumes that the server died if not. Though it's a TSServer bug, we can handle it by catching the `ValueError` exception raised when parsing invalid headers and by interrupting the reader loop only if the server is not running.
Also, this new version of TypeScript returns an empty list when no definition is found. Update the `_GoToDefinition` and `_GoToType` functions accordingly.
Fixes …
> [READY] Support TypeScript 2.6.1

- cpp/ycm/CMakeLists.txt
When doing an incremental build on Windows, CMake will be stuck extracting libclang from the installer because 7-Zip asks the user if he want to overwrite existing files. We can avoid that by adding the `-y` option to the 7-Zip command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/870)
> [READY] Run 7-Zip in non-interactive mode

- ci/appveyor/appveyor_install.bat
- ci/travis/travis_install.sh
- run_tests.py
When running the tests locally with coverage enabled, nose will not include the files from subprocesses coverage in its own report and in the HTML report. This is fixed by adding the `--cover-inclusive` option and by specifying the `--ignore-files` option so that nose does not ignore the `__main__.py` file (files starting with a underscore are ignored by default). We also have to exclude the `ycmd/tests/python/testdata` directory because its base name starts with `test` (nose will collect tests in that directory) and it contains Python files.
Another improvement is that we enable subprocesses coverage on AppVeyor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/876)
> [READY] Improve coverage configuration

- ycmd/completers/javascript/tern_completer.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/javascript/debug_info_test.py
- ycmd/tests/javascript/event_notification_test.py
- ycmd/tests/javascript/get_completions_test.py
- ycmd/tests/javascript/subcommands_test.py
Contrarily to what the YCM docs say, issuing the `:YcmCompleter RestartServer` command to switch to a different JavaScript project doesn't work. The reason is that we don't set the working directory when starting the Tern server. Same issue if the user starts the client outside a project and then open a file in that project. It's even worse in that case because no warning will be displayed to the user.
I considered passing the `request_data` object when initializing the completer but that doesn't work because the request is not always available. I also considered adding support for multiple projects similarly to what the C# completer does but I felt it was too much work. Finally, I went for starting the server on the `FileReadyToParse` event.
--- …
> [READY] Allow switching to a different JavaScript project with RestartServer

- cpp/ycm/CMakeLists.txt
Added some code to download the clang+llvm-5.0.0-armv7a-linux-gnueabihf.tar.xz for ARM architecture systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/880)
> Added code to download LLVM armv7a binary on ARM systems

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/diagnostics_test.py
- ycmd/tests/cs/testdata/testy/ZeroColumnDiagnostic.cs
The OmniSharp server sometimes incorrectly returns diagnostics with a column number of 0 while lines and columns are supposed to be 1-indexed. This causes the following error:
```
File "C:\Users\micbou\projects\YouCompleteMe\third_party\ycmd\third_party\bottle\bottle.py", line 862, in _handle
return route.call(**args)
File "C:\Users\micbou\projects\YouCompleteMe\third_party\ycmd\third_party\bottle\bottle.py", line 1740, in wrapper
rv = callback(*a, **ka)
File "C:\Users\micbou\projects\YouCompleteMe\third_party\ycmd\ycmd\..\ycmd\watchdog_plugin.py", line 108, in wrapper
return callback( *args, **kwargs )
File "C:\Users\micbou\projects\YouCompleteMe\third_party\ycmd\ycmd\..\ycmd\hmac_plugin.py", line 70, in wrapper
body = callback( *args, **kwargs )
File …
```
> [READY] Handle zero column diagnostic from OmniSharp

- .travis.yml
- ci/travis/travis_install.sh
[The `xcode8` image on Travis is deprecated](https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce). Use the default image `xcode8.3` (corresponding to macOS 10.12.6). This image has the RVM bug mentioned in PR https://github.com/Valloric/YouCompleteMe/pull/2840 so we add the same workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/882)
> [READY] Use default macOS image on Travis

- build.py
The `build.py` script may fail to build the OmniSharp server because of MSBuild picking an invalid configuration (e.g. `Release|mac`). See issue https://github.com/Valloric/YouCompleteMe/issues/2845. This is fixed by setting the `Platform` property to `Any CPU` when building OmniSharp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/884)
> [READY] Specify Platform property when compiling OmniSharp

- ycmd/completers/javascript/tern_completer.py
- ycmd/tests/javascript/debug_info_test.py
- ycmd/tests/javascript/event_notification_test.py
Use the Client working directory instead of the home directory when no `.tern-project` file is found. If no working directory is given (no `working_dir` field in the request), we fall back to ycmd working directory. See issue https://github.com/Valloric/YouCompleteMe/issues/2857.
Once this is merged, we'll update YCM to always include the working directory in the request as done in PR https://github.com/Valloric/YouCompleteMe/pull/2827.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/886)
> [READY] Use current working directory in JavaScript completer

- clang_includes/include/avx512fintrin.h
- cpp/ycm/CMakeLists.txt
[Clang 5.0.1 has just been released](http://lists.llvm.org/pipermail/llvm-announce/2017-December/000076.html). No changes required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/889)
> [READY] Update Clang to 5.0.1

- cpp/ycm/CMakeLists.txt
$ ls -ld /usr/lib64/llvm/4/l*
drwxr-xr-x 3 root root  20K Dec 16 02:37 lib32
drwxr-xr-x 3 root root  20K Dec 16 02:37 lib64
drwxr-xr-x 2 root root 4.0K Dec 16 02:37 libexec
This results in GLOB finding the wrong library.
$ ./install.py --clang-completer --system-libclang
...
Using external libclang: /usr/lib64/llvm/4/lib32/libclang.so.4.0
...
/usr/lib64/llvm/4/lib32/libclang.so.4.0: error adding symbols: File in wrong format
FTR, I had to use --system-libclang because of libtinfo.so.5 issue (https://github.com/Valloric/YouCompleteMe/issues/778)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/891)
> Fix --system-libclang on Gentoo amd64, if llvm is compiled with ABI_X86="32 64"

- ycmd/responses.py
Just fixing two typos I noticed in the doc comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/895)
> Fix typos in documentation

- build.py
- cpp/ycm/CMakeLists.txt
- make_llvm_package.py
releases.llvm.org is under serious load and is causing CI to flake.
The LLVM people say that CI systems shouldn't continually download clang
from release.llvm.org. We normally wouldn't but the caches in our CI are
full and we seem to fail to cache the LLVM full download.
Instead, we just use a package (created by us) containing only libclang,
and download that from bintray (which is free for OSS usage). There is
some limit to the number of downloads etc., so we only enable this in CI, even if it is cached.
In theory, we could also suggest this to users who are struggling with the download, such as from behind certain national firewalls.
I selected bintray as the hosting as it is free for a limited amount of traffic for open source projects. The packages contain the libraries and the LLVM …
> [READY] Use our own packages of libclang to prevent CI flakes

- cpp/ycm/Candidate.h
- cpp/ycm/CandidateRepository.h
- cpp/ycm/ClangCompleter/ClangCompleter.h
- cpp/ycm/ClangCompleter/ClangHelpers.h
- cpp/ycm/ClangCompleter/CompilationDatabase.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/ClangCompleter/TranslationUnitStore.h
- cpp/ycm/IdentifierDatabase.h
- cpp/ycm/LetterNodeListMap.h
- cpp/ycm/PythonSupport.cpp
Instead of replacing all the `typedef`s with `using` in PR https://github.com/Valloric/ycmd/pull/894, we do that in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/898)
> [READY] Replace typedef with using

- cpp/ycm/Candidate.cpp
- cpp/ycm/ClangCompleter/CompilationDatabase.cpp
- cpp/ycm/ClangCompleter/Documentation.cpp
- cpp/ycm/ClangCompleter/Location.h
- cpp/ycm/ClangCompleter/Range.h
- cpp/ycm/LetterNodeListMap.h
- cpp/ycm/Result.cpp
- cpp/ycm/Result.h
Consistently use the following style for constructor initialization list:
```C++
Constructor( ... )
: var1( ... ),
var2( ... ),
...
varN( ... ) {
...
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/899)
> [READY] Make constructor style consistent

- build.py
The `eclipse.jdt.ls-workspace` folder is not used anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/906)
> [READY] Clean up build script

- ycmd/completers/language_server/language_server_completer.py
- ycmd/request_wrap.py
- ycmd/tests/java/get_completions_test.py
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/request_wrap_test.py
Resolving lots of completion items is very slow, so we only do that if
there are 100 or feweer completions.
Most unfortunately Visual Studio Code does some heuristics on completion
items, so that any overlap with existing code is replaced, rather than
appended. This happens to be how jdt.ls returns import completions.
It's common for there to be more than 100 suggestions when typing,
say 'import com.'. This leads to bad behaviour where the insertion ends
up being 'com.com.youcompletme...' which is clearly wrong.
To combad this, when we don't have a textEdit to apply, we detect any
overlap between the insertion_text and the existing text (up to the
completion location) and offset the start_codepoint by that much.
The overlap detection algorithm is efficient (see the link) and simpler
than …
> [READY] Calculate the start codepoint when we don't resolve items in LSC

- build.py
The link explaining why we are looking for a Python library with the `.lib` extension (and not a `.dll` one) on Windows is broken.
This PR can be merged without triggering zzbot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/907)
> [READY] Fix link about Windows dynamic library in build script

- README.md
Closes https://github.com/Valloric/ycmd/issues/242.
@Valloric We could add a link to the API docs in the repository description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/908)
> [READY] Mention API docs in README

- cpp/ycm/CMakeLists.txt
Change libclangsource to https to avoid some http hijack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/912)
> Download libclang and llvm from https 

- docs/index.html
- docs/openapi.yml
- update_api_docs.py
The website containing the API docs wasn't updated when merging PR https://github.com/Valloric/ycmd/pull/857 (the `/receive_messages` handler is missing). This PR fixes some typos, renames `openapi.yaml` to `openapi.yml`, and updates the website.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/911)
> [READY] Update API documentation

- cpp/ycm/CMakeLists.txt
create_symlink is UNIX specific[1], and it breaks the build
on Windows.
[1]: https://cmake.org/cmake/help/v3.9/manual/cmake.1.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/914)
> Do not try to symlink libclang on Windows

- .circleci/config.yml
- .circleci/install_dependencies.sh
- .gitmodules
- .travis.yml
- CONTRIBUTING.md
- README.md
- build.py
- ci/travis/travis_install.sh
- cpp/CMakeLists.txt
- examples/README.md
- examples/example_client.py
- run_tests.py
- test_requirements.txt
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/tests/server_utils_test.py
This drops support for python versions that have reached their end of life.
Python 2.6 has reached its end of life in 2013-10-29.
Python 3.3 has reached its end of life in 2017-09-29.
Reference: https://devguide.python.org/#status-of-python-branches
Besides dropping python version, this also does two more things:
- Updates waitress to version v1.1.0 - this protects us from [this vulnerability](https://www.djangoproject.com/weblog/2015/jan/13/security/).
- Removes the argparse submodule, because it has been a part of the system library since Python 2.7.
The pull request is tagged RFC because you might disagree with some things I've done, or we might decide to split this in more than one PR.
Once we're satisfied with the PR state, the commits will be squashed.
--- …
> [READY] Drop Python 2.6 and Python 3.3 support

- ycmd/tests/java/subcommands_test.py
The Java GoTo tests were always passing because the response was not a matcher object. Use the `has_entries` matcher and fix the class test by actually positioning the cursor on a class (and not on a constructor).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/916)
> [READY] Fix missing matcher in Java GoTo tests

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/testdata/driver_mode_cl/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/driver_mode_cl/driver_mode_cl.cpp
- ycmd/tests/clang/testdata/driver_mode_cl/driver_mode_cl_include/driver_mode_cl_include.h
Windows (cl) style flags are currently filtered and thus windows users are unable to use a `.ycm_extra_conf.py` such as this one:
```py
def FlagsForFile( filename ):
return { 'flags': [
'--driver-mode=cl',
'/c',
'/Zi',
'/nologo',
'/W3',
'/WX-',
'/O2',
'/GL',
'/Gm-',
'/EHsc',
'/MT',
'/GS',
'/fp:precise',
'/Zc:wchar_t',
'/Zc:forScope',
'/Zc:inline',
'/Gd',
'/TP',
'/wd4099',
'/Tp' ] }
```
If `--driver-mode=cl` is in flags, libclang gladly accepts these flags. This pull request checks for `--driver-mode=cl` before filtering the flags. U used the above `.ycm_extra_conf.py` to confirm if everything works. The resulting `:YcmDebugInfo`:
```
Printing YouCompleteMe debug information...
-- Client logfile: /tmp/ycm_rbjk7yrj.log
-- Server Python interpreter: /usr/sbin/python
-- Server Python version: …
```
> [READY] Enable windows style flags when --driver-mode=cl is found in flags

- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/CompletionData.cpp
- cpp/ycm/ClangCompleter/CompletionData.h
- cpp/ycm/ClangCompleter/Diagnostic.h
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/ycm_core.cpp
Enumeration classes are supposed to be safer (read: namespaced), so possible name clashes between different `enum`s are avoided. They also prevent the following:
```c++
#include <iostream>
enum class ec1 { A }; // ok
enum class ec2 { A }; // ok
enum e { A }; // ok
int main(void) {
// if ( ec1::A == ec2::A ) std::cout<<"Error - different enums.\n";
// if ( A == ec2::A ) std::cout<<"Error - different enums.\n";
// if ( ec1::A == 0 ) std::cout<<"Error - different types.\n;
if ( A == 0 ) std::cout<<"Okay, but considered unsafe.\n";
return 0;
}
```
Should I bump the `CORE_VERSION`?
NOTE:
I also urge everyone to check what our benchmarks say, because travis reported considerable performance hit compared to current master.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [READY] Use C++11 enum classes instead of plain enums

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_connection_test.py
If the client does not support message polling, or if for some reason
the message poll loop fails, we queue notifications forever without
consuming them. Currently there is no limit to the length of this queue,
which is the definition of a managed memory leak.
Instead we make the queue operate like a ring buffer, overwriting the
oldest message if it wraps. We keep up to a maximum 250 messages. This
number is somewhat arbitrary; we need it to be big enough to hold the
messages delivered reasonably by a server within one message poll
return/retry loop. If we see problems with this number, we can tweak it
easily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/923)
> Don't grow the notification queue forever [READY, NFC]

- docs/index.html
- docs/openapi.yml
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/subcommands_test.py
Add support for the [`formatting`](https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting) and [`rangeFormatting`](https://microsoft.github.io/language-server-protocol/specification#textDocument_rangeFormatting) requests to the language server completer through the new command `Format`. Update the API by adding two optional fields to the `run_completer_command` endpoint:
- `range`: the range to which the formatting is applied. If given, the `rangeFormatting` LSP endpoint is used; otherwise, the `formatting` one is called. This makes more sense than having a separate command for each LSP endpoint;
- `options`: a set of editor-related options for the current buffer. Available options are `tab_size` and `insert_spaces` which correspond to the options in …
> [READY] Add formatting support to language server completer

- build.py
- cpp/ycm/CMakeLists.txt
- run_tests.py
This output of the build on Travis is very large now and can make viewing test failures quite painful in its UI.
This change adds a `--quiet` option to the `build.py` and uses it in `run_tests.py`. It just suppresses stdout (using a temporary file) for the build commands.
We print the stdout on failure, so we can still see build error messages.
We don't suppress the benchmark output, as that is what the benchmark run is for.
As you can see in the example output it isn't perfect, but it might be better than nothing.
Example output:
```
bash-3.2$ ./run_tests.py
Running tests on Python 2.7.14
Running flake8
Generating ycmd build configuration...DONE
Compiling ycmd target: ycm_core...DONE
Compiling ycmd target: ycm_core_tests...DONE
Running ycmd tests...DONE
Building OmniSharp for C=Sharp …
```
> [READY] Add --quiet to the build as now the output is huge for --all mode 

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
`len( line_value )` returns a 0-based code point offset  (`len( '' ) = 0`) while `CodepointsToUTF16CodeUnits` expects a 1-based offset.
Added a test that fails without this change:
```
======================================================================
FAIL: ycmd.tests.language_server.language_server_completer_test.LanguageServerCompleter_GetCodeActions_CursorOnEmptyLine_test
----------------------------------------------------------------------
File "C:\Python36\lib\site-packages\nose\case.py", line 198, in runTest
self.test(*self.arg)
File "ycmd\tests\language_server\language_server_completer_test.py", line 446, in LanguageServerCompleter_GetCodeActions_CursorOnEmptyLine_test
'character': 0
AssertionError:
Expected: a dictionary containing {'end': a …
```
> [READY] Fix codepoint offset computation in code action

- ycmd/completers/completer_utils.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/diagnostics_test.py
While I was playing with the Java completer, I noticed that matches from asynchronous diagnostics are sometimes incorrectly displayed:
This is due to the file contents from the `/receive_messages` request not being up to date anymore when the language server are publishing new diagnostics. In the example above, when inserting the second `public String test;`, the diagnostic offsets are converted from UTF-16 to UTF-8 using the contents:
```java
package com.youcompleteme;
public class Test {
public String test;
}
```
instead of
```java
package com.youcompleteme;
public class Test {
public String test;
public String test;
}
```
The solution is to store new file contents in the `ServerFileState` object and use that contents (if available) when polling asynchronous diagnostics:
Added a test …
> [READY] Use file contents from server state if available when polling asynchronous diagnostics

- ycmd/completers/java/java_completer.py
Since `stderr` is redirected to a file in the Java completer, [it is necessarily set to `None`](https://docs.python.org/2.7/library/subprocess.html#subprocess.Popen.stderr) and thus can't be closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/932)
> [READY] Do not try to close stderr in Java completer

- run_tests.py
Running the tests with `USE_CLANG_COMPLETER=false ./run_tests.py --no-completers cfamily` raise the following error:
```
File "./run_tests.py", line 239, in <module>
Main()
File "./run_tests.py", line 227, in Main
parsed_args, nosetests_args = ParseArguments()
File "./run_tests.py", line 136, in ParseArguments
parsed_args.completers = FixupCompleters( parsed_args )
File "./run_tests.py", line 157, in FixupCompleters
completers.remove( 'cfamily' )
KeyError: 'cfamily'
```
Use `discard` instead of `remove` to remove an element from the set of completers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/934)
> [READY] Fix error removing cfamily element if not present

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
When using a compilation database, the flags generally end with `-c /path/to/file` where `/path/to/file` is the compiled file. Libclang chokes on this if we don't remove the path. We have some logic to handle that case where, in addition to several conditions, we detect that the flag is a path if it contains the `/` separator. However, this doesn't take care of the case where the flag is a Windows path with `\` as separators.
Fixes #937.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/938)
> [READY] Skip stray Windows paths in flags

- .circleci/install_dependencies.sh
- ci/travis/travis_install.sh
As discussed on Gitter some time ago, we should try to test for the oldest version of Python that we are supposed to support on Linux and macOS (e.g. RHEL 7 has Python 2.7.5 installed by default so if we test for Python 2.7.14, we are not sure it's going to work on that platform).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/940)
> [READY] Lower minimum Python version requirements on Travis and CircleCI

- build.py
- cpp/ycm/CMakeLists.txt
- update_clang.py
In PR https://github.com/Valloric/ycmd/pull/897, we discussed if we should download our libclang packages for users too and decided to wait until the next release of Clang. Since Clang 6.0.0 is probably going to be released this week, I think it's time to consider this. The numerous builds done since PR https://github.com/Valloric/ycmd/pull/897 have shown that Bintray is a reliable service so I am in favor of doing the switch. [I've uploaded the libclang packages to my Bintray account](https://bintray.com/micbou/libclang/libclang/5.0.1#files) and updated the `CMakeLists.txt` file accordingly.
This PR also includes several improvements to the `make_llvm_package.py` script (renamed `update_clang.py` for the occasion):
- automatically update the Clang headers in `clang_includes` and …
> [READY] Download libclang from Bintray

- build.py
This makes it easier to use build.py just to install (or add) additional
complters. In particular, this is useful for jdt.ls as install.py is the
only supported mechanism to update it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/945)
> Allow skipping building of ycm_core. [READY]

- ci/travis/travis_install.sh
In order to cover Python subprocesses, we add the following lines to [the `sitecustomize.py` file](https://docs.python.org/2/library/site.html):
```python
import coverage
coverage.process_startup()
```
This fails on Python 2.7.1 with the following error:
```
File "/home/travis/.pyenv/versions/2.7.1/lib/python2.7/site.py", line 500, in execsitecustomize
import sitecustomize
File "/home/travis/.pyenv/versions/2.7.1/lib/python2.7/site-packages/sitecustomize.py", line 1, in <module>
import coverage
File "/home/travis/.pyenv/versions/2.7.1/lib/python2.7/site-packages/coverage/__init__.py", line 13, in <module>
from coverage.control import Coverage, process_startup
File "/home/travis/.pyenv/versions/2.7.1/lib/python2.7/site-packages/coverage/control.py", line …
```
> [READY] Test against Python 2.7.2 on Travis

- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/clang/debug_info_test.py
I missed that the translation unit was added to the output of `:YcmDebugInfo` in PR https://github.com/Valloric/ycmd/pull/922, which is really neat. Nice job @puremourning. However, what's less nice is the underscore in the key, especially when there are none in the `compilation database path` key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/950)
> [READY] Rename "translation_unit" to "translation unit" in debug info output

- ycmd/completers/general/filename_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/extra_conf_store.py
- ycmd/tests/extra_conf_store_test.py
- ycmd/utils.py
This PR adds support for environment variables in the `extra_conf_globlist` and `global_ycm_extra_conf` options.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2944.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/951)
> [READY] Expand environment variables in extra conf options

- ycmd/request_wrap.py
- ycmd/tests/request_wrap_test.py
Like the query, we need to reset the prefix when setting the start column in the request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/954)
> [READY] Reset prefix when setting the start column

- run_tests.py
- ycmd/tests/test_utils.py
When writing new tests that use `@WithRetry` (such as those in `java/get_completions_test.py`), or when investigating failures, the output is huge and unmanageable. Normally you want to see the first error.
So we add a way to suppress the retry mechanism. This adds:
* `--no-retry` to `build.py`
* `YCM_TEST_NO_RETRY` environment variable for manually running `nostests` (e.g. in `pdb`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/956)
> [READY] Ability to turn off retries when writing new tests

- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/request_wrap.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/java/get_completions_test.py
- ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWidgetImpl.java
- ycmd/tests/request_wrap_test.py
- ycmd/utils.py
jdt.ls does not return anything useful for top-level completions,
presumably because with no query to work from it has no way to filter
the almost infinite set of possible suggestions.
However it does provide useful completion at the top level (including
automatic imports) when it is given the query string to work with. The
main drawback of this is that the filtering that gets applied is done by
whatever algorithm jdt.ls applies, not what ycmd applies. This can lead
to confusion and breaking the user's mental model of how ycmd completion
works.
Automatic imports are particularly useful for top-level completions,
which are (in general) forced by the user.
So as a compromise, we use the column_codepoint (i.e. including the
'query') when the user forces semantic completion and use the …
> [READY] Send the full query to the language server when forced

- ycmd/completers/completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/handlers.py
- ycmd/request_wrap.py
- ycmd/server_state.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/request_wrap_test.py
- ycmd/utils.py
After PR #957, we now have access to the `force_semantic` key consistently from `RequestWrap`. As commented by @micbou this makes `utils.ForceSemanticCompletion` pretty redundant.
This change is actually 3 commits which all make non-functional changes:
1. Remove `utils.ForceSemanticCompletion`
2. Simplify `cs_completer` a little (this is not the whole job, we need to remove `CompletionType`, but that is done by #958 
3. Refactor the `/completion` handler (in particular `ShouldUseFiletypeCompleter`) to use `force_semantic` from the `RequestWrap`, as previously the return was a tuple and it was all a bit messy.
If you want me to do 3 separate PRs for the  3 commits, just shout.
--- …
> [READY] Simplify force_semantic usage

- cpp/BoostParts/CMakeLists.txt
When building the `ycm_core_tests` target for the first time on Windows, we override the `BUILD_SHARED_LIBS` variable to dynamically link the `gmock` library. The Boost libraries are still statically built because they are compiled before the option is set. However, if we rebuild the `ycm_core_tests` target, `BUILD_SHARED_LIBS` is now set and CMake tries to build dynamic libraries of Boost which fails because the Python dynamic library cannot be found (which is expected since there is no `link_directories` directive to build Boost). To fix that, we need to force building Boost statically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/961)
> [READY] Fix ycm_core_tests incremental builds on Windows

- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/get_completions_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java
This implements the jdt.ls `java.edit.organizeImports` command as a new Java completer subcommand  `OrganizeImports`. Demo:
I switched the imports in `TestLauncher.java` to make the tests more interesting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/963)
> [READY] Add OrganizeImports command to Java completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/diagnostics_test.py
We are incorrectly using the current line to compute the column offset of diagnostics in the TypeScript completer. We should use the line where the diagnostic occurs instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/969)
> [READY] Fix TypeScript diagnostics

- ycmd/completers/completer_utils.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/completers/typescript/typescript_completer.py
With PR #958, we now store the lines of the current file in `request_data[ 'lines' ]`. This should be used where possible to avoid splitting the current file more than once. Since we often do `SplitLines( GetFileContents() )` in the code, I added a new function `GetFileLines` for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/970)
> [READY] Optimize lines splitting for current file

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/testdata/test.ts
Add the completion signature and docstring (if any) to the ` detailed_info` field in the TypeScript completer. Make the completion data more consistent with other completers. Here's the comparison before and after in Vim:
Fixes https://github.com/Valloric/YouCompleteMe/issues/1944.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/971)
> [READY] Improve TypeScript completion data

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/subcommands_test.py
This PR adds the `GoTo` and `GoToDeclaration` commands to the TypeScript completer in order to be consistent with other completers. These commands are identical to `GoToDefinition`.
Added a test to check the list of commands defined in the TypeScript completer and refactored all the subcommands tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/972)
> [READY] Add GoTo and GoToDeclaration commands to TypeScript completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/responses.py
- ycmd/tests/typescript/diagnostics_test.py
- ycmd/tests/typescript/subcommands_test.py
This is implemented similarly to the Clang completer i.e. the FixIts are stored in the diagnostics. Demo:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/976)
> [READY] Add FixIt command to TypeScript completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/typescript/subcommands_test.py
Like the Java `Format` command:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/977)
> [READY] Add Format command to TypeScript completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/testdata/imports.ts
A recent addition to TSServer:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/978)
> [READY] Add OrganizeImports command to TypeScript completer

- ycmd/completers/java/java_completer.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/java/subcommands_test.py
It may not always be possible to correctly identify the project
directory heuristically. We therefore allow the user to manually open a
"project directory" with a new 'OpenProject' command. This overrides our
heuristics until the server is restarted.
This is in conjunction with #981 to help with using more complex projects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/982)
> [RFC] Allow the user to manually specify a project path

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
Accepts Unicode characters in identifiers for TeX as well as numbers (except the first character). See issue https://github.com/Valloric/YouCompleteMe/issues/2670 and [this post on ycm-users]( https://groups.google.com/forum/#!searchin/ycm-users/tex%7Csort:date/ycm-users/lv5PK7nP0bI/SvGWT7TVAwAJ).
Fixes https://github.com/Valloric/YouCompleteMe/issues/2670.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/983)
> [READY] Improve TeX identifier regex

- ycmd/completers/typescript/typescript_completer.py
- ycmd/handlers.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/typescript/debug_info_test.py
- ycmd/utils.py
- ycmd/watchdog_plugin.py
This is more complicated than expected for a number of reasons:
- we need to send the `status` request to get the version;
- we can't just send the request when getting the debug info because we want to know the version even if TSServer crashed so we send the request immediately after the server started and store the result in a variable;
- we don't want the request to block;
- we need a lock for the variable because it can be accessed by multiple threads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/973)
> [READY] Add TSServer version to debug info

- ycmd/completers/java/java_completer.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/java/testdata/simple_maven_project/pom.xml
It's not uncommon for multi-layer projects to be defined with having
build.gradle, pom.xml and even .project in a hierarchy. This is
particularly common on larger (non-toy) projects.
To cater for this, we improve the java project detection heuristics to
first search for the "nearest" project file, then continue searching to
find the last in any chain of consecutive project files of the same
type. This allows for opening files within sub-projects to load the
top-most project as the project directory.
Example structure:
```
Project/
- build.gradle
- SubprojectA/
- build.gradle
- src/java/main/com/blah/blah/blah/suba/SubA.java
- SubprojectB/
- build.gradle
- src/java/main/com/blah/blah/blah/subb/SubB.java
```
If opening SubB.java, the project path should be `Project/` not `SubprojectB`.
--- …
> [READY] Improve java project detection heuristics

- ycmd/tests/clang/debug_info_test.py
Because a test is more meaningful if it's actually run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/998)
> [READY] Fix debug info unity test

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/diagnostics_test.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/testdata/test.ts
- ycmd/tests/typescript/testdata/unicode.ts
If available, add FixIts to the `extra_data` field of TypeScript completions. This allows automatic insertion of an import when selecting a completion:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/987)
> [READY] Support FixIts in TypeScript completions

- cpp/ycm/tests/Normalization_test.cpp
- cpp/ycm/tests/Word_test.cpp
There are only 822 elements in that array, not 878.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/989)
> [READY] Fix length of Word tests array

- cpp/ycm/tests/TestUtils.cpp
- cpp/ycm/tests/TestUtils.h
- cpp/ycm/tests/Word_test.cpp
This fixes the issue where recent versions of Clang would take forever to compile the `BreakIntoCharacters` tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/990)
> [READY] Use const char* instead of std::string in Word tests

- .gitignore
- build.py
- run_tests.py
- third_party/regex/README.md
- ycmd/completers/completer_utils.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/general/filename_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/identifier_utils.py
- ycmd/server_utils.py
- ycmd/tests/completer_utils_test.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/server_utils_test.py
- ycmd/utils.py
The `\w` pattern from the `re` module does not match Unicode characters with combining marks (e.g. `e` + acute accent). This causes identifiers that contains such characters to not be properly extracted from the buffer. The solution is to replace the `re` module with [regex](https://pypi.python.org/pypi/regex/). This module has a compiled component so we can't simply vendor it. Instead, we download it in the `build.py` script as a pip package and install it to `third_party/regex` in the `py2` folder for Python 2 and `py3` for Python 3. We use two folders because YCM is going to import this module and if it's running on a different version of Python than ycmd, this will fail. We need to fall back to the `re` module in that case.
--- …
> [READY] Replace re module with regex

- ycmd/tests/language_server/language_server_connection_test.py
- ycmd/tests/utils_test.py
codecov sometimes reports unexpected coverage changes for two code paths:
- the notifications queue being full in the language server completer;
- process not terminated after waiting for `x` seconds.
This happens because these two code paths may or may not be interpreted when running the tests. We fix that by using `pragma: no cover` in the first case and by adding a test that always covers the second case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/999)
> [READY] Fix unexpected coverage changes

- cpp/ycm/CodePoint.cpp
This one is enabled by default. If we want it disabled, we need to be explicit.
It actually caught a sneaky "`dead-code.DeadStore`".
There are tons of checks here and a lot of those are platform specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/997)
> [READY] Clang tidy - clang analyzer

- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- cpp/ycm/ClangCompleter/Documentation.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/Utils.cpp
- cpp/ycm/ycm_core.cpp
This is the first in the upcoming clang-tidy PR series.
Ycmd triggered two warning types - namespace comment and include order.
Besides those two, LLVM checks also include header include guards and "twine locals".
Twine locals is something like this:
```c++
static Twine Moo = Twine("bark") + "bah";
// becomes
static std::string Moo = (Twine("bark") + "bah").str();
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/991)
> [READY] Clang-tidy - LLVM style fix

- ycmd/tests/get_completions_test.py
Two tests in `get_completions_test.py` are not executed because their `IsolatedYcmd` decorator is not properly defined (parentheses are missing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1009)
> [READY] Fix get completions tests

- ycmd/tests/test_utils.py
The options passed to an isolated test are changing the state of the user options store (through [the `UpdateUserOptions` function](https://github.com/Valloric/ycmd/blob/2f87e12f7dae0c4ea6f7a83ed58daa62b83c3b63/ycmd/handlers.py#L336)). We need to restore the options at the end of each isolated test like we already do for the extra conf store.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1008)
> [READY] Restore options after isolated tests

- build.py
When pip is not available, the regex module cannot be installed but the script still continues since this module is not required. However, the absence of message or the `FAILED` message when `--quiet` is given may let the user thinks that the whole installation failed. We improve that by printing a warning if the regex module cannot be installed. When installation is successful:
```sh
$ ./build.py
...
Collecting regex==2018.02.21
Installing collected packages: regex
Successfully installed regex
$ ./build.py --quiet
...
Installing regex module...OK
```
When pip is not available:
```sh
$ ./build.py
...
/usr/bin/python: No module named pip
WARNING: pip is required to install the regex module.
Unicode will not be fully supported without this module.
$ ./build.py --quiet
...
Installing regex …
```
> [READY] Improve message when regex module installation fails

- cpp/ycm/CandidateRepository.h
- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/CodePoint.cpp
- cpp/ycm/CodePoint.h
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/Result.h
- cpp/ycm/Word.cpp
- Prohibits implicit cast to bool
- vector::empty() instead of vector::size() for checking empty vectors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/992)
> [READY] Clang-tidy - readability checks

- README.md
- build.py
See PR https://github.com/Valloric/YouCompleteMe/pull/2998. The same issue occurs when running the tests on Python 2.7.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1013)
> [READY] Increase Python 2 requirement to 2.7.1

- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/CodePoint.cpp
- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/IdentifierCompleter.h
- cpp/ycm/IdentifierDatabase.h
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/Word.cpp
- Implemented
- Use emplace_back instead of push_back
- Use = default; instead of {}; in constructors
- Remove useless std::move
- Some member initialisations
- Implemented by other checks
- Braces around blocks
- False positive
- Candidate.cpp:70:1: warning: constructor does not initialize these fields: text_is_lowercase_
- Weird mess in `ycm_core.cpp` caused by boost::python, clean with pybind11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/995)
> [READY] Clang-tidy - HICPP style fixes

- build.py
- cpp/ycm/Word.cpp
- docs/index.html
- docs/openapi.yml
- update_unicode.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/python/jedi_completer.py
Fix some errors reported by [the LGTM service](https://lgtm.com/projects/g/Valloric/ycmd/).
I removed the filename check in the Clang completer since a client should never send an empty string for the filename: an arbitrary unique string should be used for a non-existing file (in YCM, we use the current directory plus the buffer number). The reason is simple: if the client has several buffers with no filename then the server must be able to distinguish them. I updated the API docs to reflect this. If we really want to check that the filename is not the empty string, we should do that when validating the request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1012)
> [READY] Minor fixes from LGTM

- cpp/CMakeLists.txt
Compilation fails with a lot of these errors:
```
error C3688: invalid literal suffix '唷'; literal operator or literal operator template 'operator ""唷' not found
```
when the system local is Chinese on Windows. This is fixed by forcing MSVC to use UTF-8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1015)
> [READY] Force MSVC to treat source files as UTF-8 encoded

- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/include_cache.py
- ycmd/completers/general/filename_completer.py
- ycmd/tests/clang/include_cache_test.py
Since @davits said he won't be able to finish #873, I've updated his PR according to the review comments.
All credits go to @davits for actually doing all the work here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/919)
> [READY] Cache include paths

- build.py
[The `distutils.sysconfig` module](https://docs.python.org/3/distutils/apiref.html?highlight=distutils%20sysconfig#module-distutils.sysconfig) has been moved to a separate package on Debian-based distributions for Python 3. Use [`sysconfig`](https://docs.python.org/3/library/sysconfig.html) instead as suggested in [this Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893924).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1020)
> [READY] Use sysconfig instead of distutils.sysconfig

- .gitignore
- .gitmodules
- benchmark.py
- build.py
- run_tests.py
- third_party/regex/README.md
- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
It turns out that using pip to download and install the regex module in a specific folder is too much to ask. See issues https://github.com/Valloric/YouCompleteMe/issues/3001 and https://github.com/Valloric/ycmd/issues/1014. There is also the issue that pip is not always available. The default Python doesn't have pip on macOS and the `python-pip` or `python3-pip` packages must be installed on Ubuntu. We need a better solution.
This PR proposes to vendor the regex sources as a Git submodule and compile the module when running the `build.py` script. The [submodule](https://github.com/micbou/regex) is a clone of [the official repository](https://bitbucket.org/mrabarnett/mrab-regex) (which is a mercurial repository hosted on BitBucket) containing a `CMakeLists.txt` file to easily compile the …
> [READY] Bundle and compile the regex module

- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/testdata/test-include/main.cpp
A typo in the regex for include statements: mostly harmless because instead of not capturing the `("[^"]*|<[^>]*)` pattern, it's matching an optional colon before the quotes, e.g. `#include :"` is matched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1023)
> [READY] Fix regex used to complete include statement

- docs/index.html
- docs/openapi.yml
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/request_wrap.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/testdata/client_data/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/client_data/macro.cpp
- ycmd/tests/get_completions_test.py
- ycmd/tests/request_wrap_test.py
- ycmd/utils.py
We currently cache the compilation flags by file path but we should also cache them according to the `client_data` parameter given to the `FlagsForFile` function since this parameter may be used to change the list of flags. In other words, the `flags_for_file` variable should be indexed by the `( filename, client_data )` tuple. However, `client_data` is a dictionary and dictionaries are not hashable so they can't be used as part of dictionaries' keys. We need to introduce a new class `HashableDict` which is a dictionary wrapper implementing the `__hash__` method, and convert `client_data` to that class.
In addition, this PR simplifies the use of the `client_data` parameter in the `FlagsForFile` function by always passing the parameter as a dictionary. For instance, instead of having to …
> [READY] Cache flags by file and client data

- ycmd/tests/request_wrap_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
Users can change the values of the extra conf data by doing something like
```python
def FlagsForFile( filename, **kwargs ):
flags = kwargs[ 'client_data' ][ 'flags' ]  
flags.append( '-Wall' ) # Change the value of request_data[ 'extra_conf_data' ][ 'flags' ]
return { 'flags': flags }
```
in the `.ycm_extra_conf.py` file. This was already possible prior to PR https://github.com/Valloric/ycmd/pull/1010 but it's now a problem because cache is invalidated if extra conf data has changed. We prevent that by doing a deep copy when getting a value of a `HashableDict`'s key.
Also, implement the `__eq__` and `__ne__` methods in `HashableDict` as recommended by the official documentation on [`__hash__`](https://docs.python.org/2/reference/datamodel.html#object.__hash__)
> If a class does not …
> [READY] Prevent users from modifying extra conf data

- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/ClangHelpers.h
- cpp/ycm/ClangCompleter/TranslationUnitStore.cpp
- cpp/ycm/ClangCompleter/TranslationUnitStore.h
- cpp/ycm/PythonSupport.cpp
- Implemented:
- Const referrences instead of copying
- Also implemented by others:
- Useless std::move
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/993)
> [READY] Clang-tidy - performance checks

- ycmd/completers/cpp/flags.py
There's a useless `enumerate()` in our flags.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1034)
> [READY] Remove unused enumerate()

- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/subcommands_test.py
This should fix the unexpected coverage changes from codecov. Also, this may potentially fix the "handle is invalid" exception that (rarely) occurs on AppVeyor when running the Java tests.
Not adding a test for JediHTTP because of PR https://github.com/Valloric/ycmd/pull/1028.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1032)
> [READY] Add tests simulating completer's server shutdown timing out

- .clang-tidy
- .travis.yml
- build.py
- ci/travis/travis_install.sh
- ci/travis/travis_script.sh
- cpp/ycm/CMakeLists.txt
- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/CompilationDatabase.cpp
- cpp/ycm/ClangCompleter/CompilationDatabase.h
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/PythonSupport.h
After #991, #992, #993, #994, #995, #996 and #997 we finally have a set of clang-tidy checks we actually want to enable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1033)
> [READY] clang-tidy support take 2

- ycmd/completers/completer_utils.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/cuda/hook.py
- ycmd/identifier_utils.py
- ycmd/tests/clang/diagnostics_test.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/subcommands_test.py
- ycmd/tests/clang/testdata/cuda/basic.cu
- ycmd/tests/clang/testdata/cuda/completion_test.cu
- ycmd/tests/clang/testdata/cuda/cuda.h
- ycmd/tests/clang/testdata/cuda/fixit_test.cu
- ycmd/tests/clang/testdata/cuda/kernel_call.cu
- ycmd/tests/clang/testdata/general_fallback/.ycm_extra_conf.py
Solves Valloric/YouCompleteMe#1766.
With this patch,
- completion will work without having to change the filetype
- CUDA kernel launch syntax (`<<<...>>>`) and attributes (`__host__`, `__device__`, etc.) will be recognized correctly
I believe another patch in Valloric/YouCompleteMe is also needed to enable linting for CUDA files. (https://github.com/Valloric/YouCompleteMe/blob/68611cf851ccee29b6df1d481df466dee3d89d00/python/ycm/buffer.py#L30)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1031)
> Add CUDA support

- cpp/ycm/ClangCompleter/CompletionData.h
- cpp/ycm/ClangCompleter/Documentation.h
- cpp/ycm/ClangCompleter/Range.h
Clang-tidy fails to detect these for `struct`s. More importantly, if a constructor is declared as `Foo(){};`, even though it is no-op, it needs to be called upon object creation, but if it is declared as `Foo() = default;` then the standard calls it a constructor with a trivial ABI and the compiler is allowed to skip calling a trivial ABI constructor. This optimisation is present in all three compilers that we support.
If we want to have cang-tidy report these consistently, we have to ban `struct{int foo;};` in favour of `class{public: int foo;};`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1040)
> [READY] Use equals default on structs

- ycmd/tests/typescript/subcommands_test.py
[TypeScript 2.9.1](https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/) has improved the way FixIts are applied:
*TypeScript 2.8.4*
*TypeScript 2.9.1*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1048)
> [READY] Fix TypeScript FixIt subcommand test

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Assume an empty list of flags if `FlagsForFile` doesn't return anything or if the `flags` key is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1039)
> [READY] Handle FlagsForFile returning nothing

- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
Since the `regex` module has a compiled component, adding it to `sys.path` in YCM may lead to a segmentation fault if the version of Python that YCM is running on is different than the one used to compile the module (e.g. YCM running on Python 3.6 while the `regex` module is compiled for Python 3.5). Note that the crash only seems to happen on macOS.
This is most likely going to fix issue https://github.com/Valloric/YouCompleteMe/issues/3048.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1052)
> [READY] Add the regex module to sys.path in ycmd exclusively

- ycmd/completers/completer.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/responses.py
- ycmd/tests/clang/diagnostics_test.py
- ycmd/tests/clang/testdata/max_diagnostics.cc
- ycmd/tests/cs/diagnostics_test.py
- ycmd/tests/cs/testdata/testy/MaxDiagnostics.cs
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/typescript/__init__.py
- ycmd/tests/typescript/diagnostics_test.py
- ycmd/tests/typescript/event_notification_test.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/subcommands_test.py
See issue https://github.com/Valloric/YouCompleteMe/issues/2392.
If the number of diagnostics exceed the value of `max_diagnostics_to_display`, a diagnostic with the message "Maximum number of diagnostics exceeded." is added at the top of the current file to inform the user.
The language server completer didn't honor the `max_diagnostics_to_display` option. It now does.
Similarly to [the `-ferror-limit` Clang flag](https://clang.llvm.org/docs/UsersManual.html#cmdoption-ferror-limit), a value of `0` for `max_diagnostics_to_display` now means that the number of diagnostics is unlimited.
Closes https://github.com/Valloric/YouCompleteMe/issues/2392.
--- …
> [READY] Inform user if maximum number of diagnostics is exceeded

- ycmd/tests/shutdown_test.py
The `FromWatchdogWithSubservers` test sometimes fail on AppVeyor because the server may become inactive for more than 5 seconds (i.e. no requests are sent within 5 seconds) while waiting for the completer servers (in particular TSServer) to be ready. We prevent that by keeping the server alive in a separate thread until all sub-servers are up and running. This should make the test more robust but also slightly faster as this allow us to stop the server after a shorter time of inactivity (2 seconds instead of 5).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1054)
> [READY] Improve FromWatchdogWithSubservers test robustness

- cpp/ycm/CodePoint.h
As it stands now (on master), the `CodePoint::break_property_` is 4 bytes large, requiring one byte of padding before it and causing the whole class to require 7 bytes of padding at the end. If we change the type of the `enum class BreakProperty { ... }` to `enum class BreakProperty : uint8_t { ... } `, we save 3 bytes for the enum size, 1 byte of padding before the `break_property_` and 4 bytes of boundary alignment (which still leaves 3 bytes of boundary alignment) - leading to 8 bytes of saved memory per `CodePoint` instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1055)
> [READY] Set break_property_ type to uint8_t

- .ycm_extra_conf.py
- README.md
- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/testdata/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/client_data/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/driver_mode_cl/executable/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/driver_mode_cl/flag/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/general_fallback/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/noflags/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/test-include/.ycm_extra_conf.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/javascript/subcommands_test.py
Migrate the Clang completer from `FlagsForFile` to `Settings` in the extra conf file. We still support `FlagsForFile` for backward compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1057)
> [READY] Migrate the Clang completer to Settings in extra conf

- ycmd/completers/general/filename_completer.py
- ycmd/default_settings.json
- ycmd/tests/filename_completer_test.py
- ycmd/tests/test_utils.py
This PR adds the option `filepath_blacklist` to allow users to disable the filepath completer from triggering on the `/` character (and `\` on Windows) for a list of filetypes. This option works like [the `filetype_blacklist` option](https://github.com/Valloric/YouCompleteMe#the-gycm_filetype_blacklist-option) where keys are the filetypes for which the completer should be disabled and the values are unimportant. The special key `*` can be used to blacklist all filetypes. 
Contrarily to the `filetype_*` options, there is no `filepath_whitelist` counterpart as I don't really see the use case but nothing prevents us from adding it later.
The `html`, `jsx`, and `xml` filetypes are blacklisted by default as there are the ones mentioned in issues …
> [RFC] Add option to disable the filepath completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/debug_info_test.py
- ycmd/tests/typescript/typescript_completer_test.py
TSServer is currently started through node to handle the case where node is installed as nodejs on Debian-based distributions. However, this doesn't work when the TSServer executable is a shim (e.g. when using [nodenv](https://github.com/nodenv/nodenv) or [asdf-nodejs](https://github.com/asdf-vm/asdf-nodejs)). See issue https://github.com/Valloric/ycmd/issues/1050. We fix that by only starting TSServer with node if it contains the line `#!/usr/bin/env node`.
Fixes #1050.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1058)
> [READY] Use node only if tsserver is supposed to run through it

- .circleci/config.yml
- .circleci/install_dependencies.sh
Building the OmniSharp server with the latest version of Mono from Homebrew (5.12.0.226_1) fails with the following errors:
```
"/Users/distiller/project/third_party/OmniSharpServer/OmniSharp.sln" (default target) (1) ->
"/Users/distiller/project/third_party/OmniSharpServer/OmniSharp/OmniSharp.csproj" (default target) (2) ->
"/Users/distiller/project/third_party/OmniSharpServer/NRefactory/ICSharpCode.NRefactory.Cecil/ICSharpCode.NRefactory.Cecil.csproj" (default target) (4:2) ->
"/Users/distiller/project/third_party/OmniSharpServer/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj" (default target) (6:3) ->
(CoreCompile target) -> 
CSC : error CS7027: Error signing output with public key from file '../ICSharpCode.NRefactory.snk' -- mscoree.dll …
```
> [READY] Fix builds on CircleCI

- appveyor.yml
[Python 3.7 is available on AppVeyor](https://github.com/appveyor/ci/issues/2475).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1069)
> [READY] Test Python 3.7 on AppVeyor

- ycmd/tests/clang/testdata/get_doc/.ycm_extra_conf.py
Missed this `.ycm_extra_conf.py` in PR https://github.com/Valloric/ycmd/pull/1057.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1073)
> [READY] Update extra conf in test

- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- ycmd/tests/clang/subcommands_test.py
- ycmd/tests/clang/testdata/GetType_Clang_test.cc
Previously, GetType on a C++ member function would always show the text
"bound member function type".  This is because a cursor on an instance
method is of kind MemberRefExpr, which itself is a reference to a
declaration of a function that has a type.  Undoing that layer of
referencing will return a useful result.
We need to be careful though, as member variables also show up as
MemberRefExpr, and undoing the layer of ref on them will remove
cv-qualification.  Checking explicitly if the cursor is pointing to a
CXXMethod seems to work fine, but honestly the clang API seems a little
weird in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1081)
> GetType on C++ member functions should return their type.

- cpp/ycm/ClangCompleter/TranslationUnitStore.cpp
- cpp/ycm/ClangCompleter/TranslationUnitStore.h
Since specializations in `std` namespace are allowed only with used defined types, our specialization of `std::hash< std::vector< std::string > >` is undefined behaviour. The solution is to inline the hash function and thus avoid UB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1076)
> [READY] Don't specialize std::hash<std::vector<std::string>>>

- ycmd/completers/completer_utils.py
Add `.` as a semantic trigger for [the Julia language](https://julialang.org/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1078)
> [READY] Add semantic trigger for Julia

- build.py
- run_tests.py
When working on the C++ code, I often only need to run a subset of the C++ tests (I blame the guy who added all those Unicode tests). However, there is currently no easy way to do this without modifying the `build.py` script. This PR improves that by adding a new option `--core-tests` that run the C++ tests and optionally filter them if an argument is given, e.g.
```
./build.py --core-tests CandidateTest*
```
to build YCM and run all the candidate tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1085)
> [READY] Add --core-tests option to build script

- .gitmodules
- build.py
- ycmd/completers/go/go_completer.py
- ycmd/tests/go/go_completer_test.py
- ycmd/tests/server_utils_test.py
As discussed in issue #1097, switch the Gocode version to [mdempsky's fork](https://github.com/mdempsky/gocode). This requires moving the Gocode submodule to `third_party/go/src/github.com/mdempsky/gocode` and setting `GOPATH` to `third_party/go` when building Gocode. Do the same for Godef. This way, using [Manishearth's fork](https://github.com/Manishearth/godef) is not needed anymore.
The following changes to the Go completer are required with this new version of Gocode:
- the `status` endpoint has been removed so the server is now assumed to be healthy if it's running;
- the `null` response is returned when there are no completions.
Closes #1090.
Closes #1092.
Closes #1097.
--- …
> [READY] Update Go completer

- ycmd/completers/cpp/clang_completer.py
- ycmd/tests/clang/__init__.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/subcommands_test.py
Same as PR https://github.com/Valloric/ycmd/pull/966 but extended to all commands (not only the `GoTo*` ones) and with tests. Error messages are updated since they are not specific to completion.
Closes https://github.com/Valloric/ycmd/pull/966.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1088)
> [READY] Raise proper exception for commands when file is still being parsed in Clang completer

- .ycm_extra_conf.py
This PR improves ycmd's extra conf by adding the root directory to `sys.path` and by setting the interpreter path to the value stored in the `PYTHON_USED_DURING_BUILDING` file (if it exists). These two changes allow completion of the `ycm_core` module in the Python code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1101)
> [READY] Allow completion of the core library in Python code

- build.py
Fixes https://github.com/Valloric/YouCompleteMe/issues/3127.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1086)
> [READY] Check if Python headers are installed in build script

- ycmd/completers/language_server/language_server_protocol.py
As mentioned in [Completion Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)
```typescript
/**
* The kind of a completion entry.
*/
namespace CompletionItemKind {
export const Text = 1;
export const Method = 2;
export const Function = 3;
export const Constructor = 4;
export const Field = 5;
export const Variable = 6;
export const Class = 7;
export const Interface = 8;
export const Module = 9;
export const Property = 10;
export const Unit = 11;
export const Value = 12;
export const Enum = 13;
export const Keyword = 14;
export const Snippet = 15;
export const Color = 16;
export const File = 17;
export const Reference = 18;
export const Folder = 19;
export const EnumMember = 20;
export const Constant = 21;
export const Struct = 22;
export …
```
> Update to latest specs

- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/typescript/subcommands_test.py
- TSServer 3.1.1 GetType does error on keyword, except `class`.
- https://github.com/Microsoft/TypeScript/issues/27373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1112)
> [READY] Fix TSServer 3.1.1 test failures

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
As mentioned in [Hover Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover)
```
Response:
result: Hover | null
```
Current implementation was failing with None object has no _getitem_ method, with this patch it will provide more useful information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1110)
> GetHoverResponse should handle null response from server.

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/language_server/language_server_completer_test.py
Implemented necessary capability support for new completion item kinds as mentioned in the [Initialize Params/ClientCapabilities/TextDocumentClientCapabilities/completionItemKind](https://microsoft.github.io/language-server-protocol/specification#initialize)
```typescript
/**
* The completion item kind values the client supports. When this
* property exists the client also guarantees that it will
* handle values outside its set gracefully and falls back
* to a default value when unknown.
*
* If this property is not present the client only supports
* the completion items kinds from `Text` to `Reference` as defined in
* the initial version of the protocol.
*/
```
After the change java tests were getting stuck and timing out. Updating version of jdt.ls resolves that issue but found out that …
> Add necessary client capability support for new completion item kinds

- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/ycm_core.cpp
- No #include <pybind11/pybind11.h> in `ClangCompleter.cpp` and `IdentifierCompleter.cpp`.
- Releases GIL just before function call, instead of just after.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1115)
> [READY] Move GIL release to bindings

- .circleci/install_dependencies.sh
- .gitignore
- README.md
- build.py
- ci/appveyor/appveyor_install.bat
- ci/travis/travis_install.sh
- run_tests.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/server_utils_test.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/typescript_completer_test.py
Add the `--ts-completer` parameter to the `install.py` script to configure the TypeScript completer. This parameter installs a specific version of TypeScript in the third-party folder which is used by the completer. If not installed this way, the completer still looks for `tsserver` in the `PATH` to ensure backward compatibility. This change has several benefits:
- tests on the build bots can't be broken by a new version of TypeScript:
- users are on a known version of TSServer that is tested;
- users are not instructed to install TypeScript globally. See issue https://github.com/Valloric/YouCompleteMe/issues/3149.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1123)
> [READY] Install fixed version of TypeScript in third-party folder

- ycmd/tests/__init__.py
- ycmd/tests/clang/__init__.py
- ycmd/tests/cs/__init__.py
- ycmd/tests/python/__init__.py
- ycmd/tests/test_utils.py
- ycmd/utils.py
Some tests fail if a `.ycm_extra_conf.py` file is found outside the ycmd directory (e.g. YCM's `.ycm_extra_conf.py` file). We prevent that by mocking the `PathsToAllParentFolder` function so that it considers the `tests` folder as the root directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1087)
> [READY] Ignore extra conf files outside tests directory

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/language_server/language_server_protocol_test.py
- ycmd/utils.py
As specified in the [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)
```
Of the ASCII character set, the characters : / ? # [ ] @ are reserved for use as delimiters of the generic URI components and must be percent-encoded
```
But turns out, implementation in url2pathname doesn't respect that. This patch fixes its behaviour in lsp. Which was the reason all tests related with a filepath(allmost every test) in windows for clangd was failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1119)
> [READY] Fix UriToFilePath.

- .ycm_extra_conf.py
- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
See PR https://github.com/Valloric/YouCompleteMe/pull/3163.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1124)
> [READY] Only add the necessary directories to Python path

- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/Utils.cpp
- cpp/ycm/Utils.h
- cpp/ycm/tests/TestUtils.cpp
- cpp/ycm/tests/TestUtils.h
- cpp/ycm/tests/Utils_test.cpp
- ycmd/tests/clang/subcommands_test.py
The following error occurs when applying a FixIt in a C/C++ buffer that's not yet saved to disk:
```
RuntimeError: boost::filesystem::canonical: No such file or directory
```
This happens because `boost::filesystem::canonical` raises an exception if the file does not exist. We need our own implementation that works on non-existing files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1080)
> [READY] Replace Boost canonical function with our own implementation

- update_clangd.py
This patch adapts update_clang script to extract and bundle clangd binary. If you guys want I can actually merge this one with the existing update_clang script, but I think this is better for maintenance, if you guys decide to make clangd default only deleting the update_clang script would be enough instead of modifying the script and also getting new sha's etc. Also there is a version conflict since clangd focuses on release v7 whereas current libclang is lookign at v6 release. Would be great if @micbou can run the script and upload to bintray, so that we can spin up the CI for tests of clangd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1117)
> [READY] Add clangd uploader script.

- ycmd/utils.py
This patch removes the following warning:
```
/usr/share/nvim/runtime/third_party/ycmd/ycmd/utils.py:499: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
class HashableDict( collections.Mapping ):
```
This warning is originated from https://github.com/python/cpython/pull/5460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1134)
> Fix DeprecationWarning from classes in collections.abc

- ycmd/completers/completer_utils.py
- ycmd/server_state.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/javascript/debug_info_test.py
Use `importlib.import_module` to import the `hook.py` file of a completer instead of loading its source. In addition to simplify the code, this is needed if we want to package only the `.pyc` files since source files don't exist in that case.
Changes are required in the tests because of how mocking works (see [Where to patch](https://docs.python.org/3/library/unittest.mock.html#where-to-patch) in the Python docs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1138)
> [READY] Simplify completer hook mechanism

- cpp/ycm/CMakeLists.txt
If a user is on linux, and not using ARM or Aarch64, we currently assume the user is using x86.
Instead we should check if x86 is right and if not, fail with an error, telling the user to either compile libclang or use his system libclang.
Fixes Valloric/YouCompleteMe#3227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1130)
> [READY] Do not default to x86 for libclang download

- ycmd/default_settings.json
These options are only used in YCM. Now that PR https://github.com/Valloric/YouCompleteMe/pull/3243 is merged, we can safely remove them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1139)
> [READY] Remove unused options

- cpp/ycm/tests/IdentifierUtils_test.cpp
Currently the `IdentifierUtilsTest.ExtractIdentifiersFromTagsFileWorks` relies on the fact that you can compare `std::unordered_map` and its preserved order of insertion. This is not true for much faster hash tables like `absl::flat_hash_map`. Using `absl::flat_hash_map` yield between 15 and 20 percent better performance, but also breaks `IdentifierUtilsTest.ExtractIdentifiersFromTagsFileWorks` on current master.
This PR rewrites `IdentifierUtilsTest.ExtractIdentifiersFromTagsFileWorks` to not depend on ordering. If you pay attention, you'll see that now `"c"` is last in the test, but second in the tag file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1142)
> [READY] Do not rely on unordered_map ordering in tests

- cpp/ycm/CodePoint.cpp
- update_unicode.py
Introduce RawCodePointArray for FindCodePoint
to iterate of a continous array instead of
an array of structs.
This also allows the arrays in RawCodePointArray
to use char[] instead of const char* and thus
avoids 12MB of relocation data on linux.
This is another attempt of doing https://github.com/Valloric/ycmd/pull/1064.
Table summary from [Michel's comment](https://github.com/Valloric/ycmd/pull/1140#pullrequestreview-181520414)
<table>
<tr>
<th rowspan="2">Platform</th>
<th colspan="2">Compilation time (s)</th>
<th colspan="2">Library size (MB)</th>
</tr>
<tr>
<td>Before</td>
<td>After</td>
<td>Before</td>
<td>After</td>
</tr>
<tr>    
<td>Ubuntu 18.04 64-bit (GCC 7.3.0)</td>
<td>26.56</td>
<td>25.79</td>
<td>19.59</td>
<td>7.32</td>
</tr>
<tr>
<td>macOS 10.14 (Apple Clang 10.0.0)</td> …
> [READY] Use struct of arrays for static code_points object

- ycmd/tests/clangd/__init__.py
Use a `try/finally` block to stop Clangd in isolated tests so that the server is shut down even if the test fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1145)
> [READY] Properly stop Clangd in isolated tests

- build.py
Clangd is enabled by default when it is installed/configured. Currently,
clangd is a feature regression and breaking change for most users, By
including in --all, we are breaking users by default.
For now, remove it from --all and require that --clangd-complerter is
explicitly requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1149)
> [clangd] Don't include clangd in --all

- run_tests.py
The test framework uses requests to communicate with ycmd. When it was
moved to its own directory, we didn't update run_tests.py to include it
in PYTHONPATH used by nosetests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1148)
> [READY] Add the requests and Jedi modules to test PYTHONPATH

- ycmd/completers/completer.py
- ycmd/completers/python/python_completer.py
- ycmd/tests/python/get_completions_test.py
- ycmd/tests/python/testdata/basic.py
- ycmd/tests/test_utils.py
Computing the fields of all candidates (`extra_menu_info`, `detailed_info`, etc.) becomes a performance issue when Jedi returns a lot of completions. Instead, we should only compute the fields on the filtered candidates (at most 50 by default). The same strategy could be applied to other completers like the TypeScript and LSP ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1153)
> [READY] Only detail filtered candidates in Python completer

- README.md
[The exit codes 5 and 6 are inverted in the docs](https://github.com/Valloric/ycmd/blob/ed8d17c2e392458e197d90d6a9cba3dc94a7e0e9/ycmd/server_utils.py#L56-L59).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1160)
> [READY] Fix exit codes in documentation

- build.py
This allows builds to just update, say jdt.ls or clangd with
'./build.py --skip-build --no-regex --java-completer' and the like.
On some systems finding python and cmake can be a pain, requiring
specifying lots of arguments, so this simplifies and speeds up that use
case.
Replaces: https://github.com/Valloric/ycmd/pull/1163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1164)
> [READY] Don't find cmake and python if not needed

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
We only actually update the server settings when starting the server, so
only read them from the config when starting the server.
This incidentally fixes a bug in the clangd completer where settings
were always {} due to calling ServerReset (via _Reset()) immediately
prior to starting the server.
NOTE: LSP supports a didChangeConfiguration notification which we could
send should the settings change, but we don't currently so there is no
point repeatedly calling the user's Settings method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1167)
> [READY] Don't read LSP settings on every file parse

- ci/travis/travis_install.sh
Currently we test with python 2.7.4, because `pip` broke everything under the sun when version 10 came out. Back then what broke python 2.7.3 and earlier is [this bug](https://github.com/pypa/pip/issues/5231).
Since the bug is fixed, we can test 2.7.2 again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1176)
> [READY] Go back to testing on Python 2.7.2 on Travis-CI

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/__init__.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/clangd/testdata/basic.cpp
LSP supports a 'capabilities' machanism where servers and clients can
identify support for certain requests. This implements a general
mechanism for discovery of supported subcommands, and standardises the
commands supported by LSP-based completers (other than Java).
Clangd completer is updated to use the general mechanism, as its
capabilities response is correct.  Java completer is a little more
complicated, so is not migrated in this change.
This will make adding basic completers much easier in future.
As a (happy?) co-incidence, this adds `RefactorRename` support to clangd.
Strangely though, the one test I wrote shows up a bug in clangd. cc @kadircet 
```
ycmd: DEBUG: RX: Received message: b'{"id":"2","jsonrpc":"2.0","result":{"changes":{"file:///Users/ben/.vim/bundle/YouCompleteMe/thir …
```
> [READY] Determine simple subcommands automatically

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/language_server/language_server_completer_test.py
The change to only load settings on initialize was flawed. In the case
where UnknownExtraConf was thrown, the server was started, but the
initialize request was not sent. This essentially left the completer
deadlocked, waiting for an initialize response that would never arrive.
The solution is to revert to requesting the settings prior to starting
the server instance, but instead of doing it on every
OnFileReadyToParse, have that concrete StartServer methods do this.
This isn't ideal, but it does solve the problem. In future, the
SimpleLSPServer will make this better, but ultimately we should probably
change it so that concrete completers don't call SendInitialize at all,
and the base class decides when to start the server and send the init.
--- …
> [READY] Fix LSP server startup when UnknownExtraConf is thrown

- ycmd/server_utils.py
The `DIR_PACKAGES_REGEX` variable is not used since PR https://github.com/Valloric/ycmd/pull/578.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1170)
> [READY] Remove unused regex in server_utils

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
We always need to get the settings, start the server, then send the
initialize request. This change hoists that code into the base class,
reducing boilerplate required by concrete classes and overall
simplifying usage. By doing so, this also prevents a loop when starting
the clangd completer fails, implementing the approach taken by java
completer.
This is the next step in simplifying LSP completer creation.
This is a follow up to #1178.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1184)
> [READY] Simplify LSP completer API for starting server

- ycmd/completers/cpp/clangd_completer.py
- ycmd/tests/clangd/get_completions_test.py
- ycmd/tests/clangd/utilities_test.py
This PR brings the following changes to the Clangd completer:
- do not raise an exception when initializing the Clangd completer since this prevents ycmd from falling back to the libclang completer;
- never fall back to the third-party Clangd if the one specified in `clangd_binary_path` is not valid. The reason behind that change is that I think most users are going to be confused by such fallback since they'll think that the Clangd from `clangd_binary_path` is used while in fact it's not. I can revert this change if you disagree;
- expand environment variables and `~` in the path specified by the `clangd_binary_path` option;
- do not print in the logs that the Clangd library is outdated if the path does not point to an executable;
- cosmetic changes like capitalizing Clangd in comments …
> [READY] Improve Clangd completer initialization

- test_requirements.txt
`flake8-comprehensions` reports violation C408 for a dict construction that can't be rewritten with `{}` on the Python 3 build of CircleCI. See if this is caused by version 2.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1192)
> [READY] Freeze flake8-comprehensions version to 1.4.1

- ycmd/completers/cpp/clangd_completer.py
- ycmd/default_settings.json
- ycmd/tests/clang/__init__.py
- ycmd/tests/clangd/__init__.py
- ycmd/tests/clangd/get_completions_test.py
- ycmd/tests/clangd/utilities_test.py
- Makes `use_clangd` option binary.
- It is no longer needed to set `use_clangd = 'Always'` after setting `clangd_binary_path` if user doesn't have clangd binary in third party folder.
- Gets rid of redundant `GetThirdPartyClangd` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1191)
> [READY] Ease clangd_completer initialization

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
I've been running into https://github.com/Valloric/YouCompleteMe/issues/303, even though ycmd has a workaround for it. It looks like the issue is just that I'm writing ObjC++ and that change only affects C++.
So, this change makes `-x objective-c++` eligible, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1193)
> Fix system header search paths on macOS for Objective-C++, too.

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
This flag tells the compiler frontend (`gcc`/`clang`) where to look for the subprograms (`cpp`, `cc`, `cc1plus`, `as`, `ld` etc.). This flag is needed when bootstrapping a toolchain, so it is unlikely to be found in a custom extra conf, but it can appear in users' compilation databases. While it is not really an include flag, it behaves just like one.
Fixes Valloric/YouCompleteMe#3333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1197)
> [READY] Add -B to INCLUDE_FLAGS

- ycmd/completers/language_server/language_server_completer.py
Some servers (heinously) send null when they should omit keys in
message objects. This causes us to break because our "default" values
are not used when uding .get( v, "default ). dict.get returns the value
if the key _exists_. If the key exists and the value is None (null), you
get None back.
Use ( dict.get( v ) or "default" ), instead of dict.get( v, default ).
This returns "default" in the case of dict[ 'v' ] being "falsy".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1204)
> [READY] Ignore any null or empty values and use our defaults

- ycmd/completers/completer.py
- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/get_completions_test.py
- ycmd/tests/language_server/language_server_completer_test.py
ycmd is caching completions that are already filtered by Clangd if we send the cursor column (`column_codepoint`) to Clangd when `clangd_uses_ycmd_caching` is set to `1`,  This leads to unexpected results when triggering semantic completion in a middle of a word. Here's a demo of the issue:
No `foo` suggestion when deleting the `b` character. If we send the starting column (`start_codepoint`) instead:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1205)
> [READY] Improve cache in LSP completer

- ycmd/completers/language_server/language_server_protocol.py
- LSP `completionItemKind` has values 1 through 25
- Our `ITEM_KIND` is a python list that has `None` as element 0.
- `len( ITEM_KIND ) + 1 == 27`
- `list( range( 1, len( ITEM_KIND ) + 1 ) ) == [ 1 ... 26 ]`
- We shouldn't add 1, because `ITEM_KIND[0] is None`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1214)
> [READY] Fix off-by-one error in LSP Initialize request

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
This avoids having to add `'-verbose=log'` to the `clangd_args` option in addition to set the `log_level` option to `'debug'` to get maximum log verbosity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1213)
> [READY] Improve Clangd completer logging

- ycmd/completers/cpp/clangd_completer.py
- ycmd/tests/clangd/utilities_test.py
This change makes it possible to use a custom Clangd from the PATH by setting the `clangd_binary_path` option to `'clangd'` instead of having to specify an absolute path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1210)
> [READY] Search custom Clangd in PATH

- ycmd/completers/cpp/clangd_completer.py
Resetting the state at server start is unnecessary (it's already reset at completer initialization and at server shutdown) and even problematic as it prevents passing initialization options to Clangd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1220)
> [READY] Do not reset state at server start in Clangd completer

- run_tests.py
- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/simple_language_server_completer.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
Pull out the common tasks for a stdio-based languate server into
SimpleLSPCompleter, and make the Clangd completer inherit from this.
The simple language server completer attempts to minimize the amount of
work required to add a completer using LSP by automatically detecting
the supported subcommands and managing the server instance.
Now, you just need to:
- update build.py to build the server
- create the <ft> package (__init__.py, hook.py, ft_completer.py)
- write the hook and ShouldEnableFTCompleter
- derive a class from SimpleLSPCompleter and implement 3 methods:
- SupportedFileTypes
- GetServerName
- GetCommandLine
- (optional) GetCustomSubcommnds
- override any other methods on the LanguageServerCompleter API as
required
--- …
> [READY] Simplify creation of LSP clients

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/language_server/language_server_completer_test.py
This PR adds the `GoToType` and `GoToImplementation` commands to the LSP completer. They are respectively mapped to the [`textDocument/typeDefinition`](https://microsoft.github.io/language-server-protocol/specification#textDocument_typeDefinition) and [`textDocument/implementation`](https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation) LSP endpoints. It also updates the `GoToDeclaration` command to be mapped to the [`textDocument/declaration`](https://microsoft.github.io/language-server-protocol/specification#textDocument_declaration) endpoint if the LSP server supports it; otherwise, the command is mapped to [`textDocument/definition`](https://microsoft.github.io/language-server-protocol/specification#textDocument_definition) as before. Finally, …
> [READY] Support LSP declaration, typeDefinition, and implementation

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/debug_info_test.py
- ycmd/tests/java/debug_info_test.py
This is useful to check that we actually read the settings.
It's equivalent to listing the flags in the libclang completer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1223)
> [READY] Include settings in debug info for LSP

- .circleci/config.yml
- .circleci/install_dependencies.sh
- .travis.yml
- CONTRIBUTING.md
- README.md
- build.py
- ci/travis/travis_install.sh
- cpp/CMakeLists.txt
- examples/README.md
- examples/example_client.py
- ycmd/tests/utils_test.py
Python 3.4 reached end of life today (2019-03-16). Ubuntu 18.04 (what we officially support) has `python` pointing to Python 2.7 and `python3` pointing to Python 3.6.
Dropping Python 3.4 will allow us to use [abseil](https://github.com/abseil/abseil-cpp)'s flat hash maps and improve [benchmarks](https://gist.github.com/bstaletic/7d3e31db7fc8d40a12787fab09ff092f) by ~20% ~~except for `IdentifierCompleterFixture/CandidatesWithCommonPrefix/65536/10` (still an improvement, but a small one)~~. Turns out we can get ~20% in every benchmark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1207)
> [READY] Drop python 3.4

- ycmd/tests/clangd/__init__.py
[Extra confs are already ignored in `IsolatedApp`](https://github.com/Valloric/ycmd/blob/c04647006ba5b1d2dc3053a01e5a966515cf1f59/ycmd/tests/test_utils.py#L241).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1225)
> [READY] Do not ignore extra conf twice in Clangd tests

- ycmd/tests/java/__init__.py
- ycmd/tests/tern/__init__.py
The shared application is used when waiting for the server to be ready instead of the one passed to the `Start*CompleterServerInDirectory` functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1227)
> [READY] Use the right application in Java and Tern tests

- .gitmodules
- .ycm_extra_conf.py
- run_tests.py
- ycmd/server_utils.py
- ycmd/tests/python/get_completions_test.py
- ycmd/tests/python/testdata/numpy_docstring.py
[Jedi depends on numpydoc](https://github.com/davidhalter/jedi/blob/8d0c4d3cec4973a2722652bf33f093ac3f1f385a/jedi/evaluate/docstrings.py#L53) to get type hinting from docstrings written in [the Numpy format](https://numpydoc.readthedocs.io/en/latest/). We could tell users to install numpydoc for this use case but it's tricky because we need to tell them to install it for the Python used to build ycmd, not the Python that they are working on. This also defeats the purpose of bundling the Jedi and Parso dependencies in the first place since they could be installed separately as well.
Note that this docstring format is used by other projects than Numpy so we are not adding a dependency just for one Python module.
Fixes https://github.com/Valloric/YouCompleteMe/issues/3361.
---
This change …
> [READY] Add numpydoc to Jedi dependencies

- ycmd/completers/cpp/clangd_completer.py
- ycmd/tests/clangd/subcommands_test.py
Right now, clangd completer returns a string as a `GetType` response instead of `{ 'message': $STRING }`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1232)
> [READY] Clangd GetType response bugfix

- codecov.yml
- test_requirements.txt
There's still the problem with paths, but codecov has ["Fixing Paths"](https://docs.codecov.io/docs/fixing-paths) section in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1236)
> [READY] Allow newer coverage version

- .clang-tidy
- cpp/ycm/CodePoint.cpp
- `std::move()` for trivially copiable types is useless.
- `pybind11::object` should be allowed to be passed by vaue.
Fixes https://github.com/Valloric/YouCompleteMe/issues/3401
Fixes #1231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1246)
> [READY] Fix clang-tidy 8 warnings

- azure/lint.sh
- run_tests.py
Silencing the output of the build on CIs has the inconvenience that we can't check if the configuration is correct (which compiler, version of Python, etc.). We silenced it because the output was too long and forced us to download the logs to see which tests failed and how. See PR https://github.com/Valloric/ycmd/pull/924. This is no longer an issue on Azure as the length of the output doesn't seem to be limited and its UI makes it convenient to scroll through it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1248)
> [READY] Do not build quietly by default when running tests

- azure/linux/install_dependencies.sh
- build.py
Instead of running Ubuntu 16.04 default toolchains, this PR tries to use the oldest ones that we support. That means gcc-4.8 and clang-3.5 (we support 3.3, but it's too old and unavailable). This PR also installs the latest clang-tidy, so issues like https://github.com/Valloric/YouCompleteMe/issues/3401 won't come up again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1247)
> [READY] Set specific gcc, clang and clang-tidy versions in CI

- .mergify.yml
This allows adding a "Ship It!" label to the PR to allow mergify to
merge it even if the Reviewable is not happy, but assuming there is at
least 1 approving review and no outstanding blocking comments.
This allows maintainers to agree to merge something with essentially
only 1 LGTM, but without always automatically merging based on that. 2
LGTMs is still a good rule for a lot of things, but is cumbersome for
smaller or more urgent PRs.
I've already created the label on Valloric/ycmd repo. Will push this change to YouCompleteMe repo too later.
Tested on my fork:
Removing the label, it updates about 1 minute later to not be ticked (pass).
--- …
> Allow maintainer to manually merge

- ycmd/completers/go/go_completer.py
Rust completer renamed GetProjectDirectory to _GetProjectDirectory,
which I didn't notice when rebasing after merging the Rust completer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1257)
> [WIP] Go completer: find root go.mod

- .gitmodules
After building, it has the gopls binary in there, but the repo doesn't have a .gitignore.
So we ignore it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1265)
> [READY] Ignore dirty gopls repo

- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/default_settings.json
- ycmd/tests/clangd/get_completions_test.py
- ycmd/tests/java/java_completer_test.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/java/subcommands_test.py
jdt.ls workspace areas are mutable and written by the server. Putting them
underneath the ycmd installation, even in their own directory makes it
impossible to use a shared installation of ycmd. In order to allow that, we
expose another (hidden) option which moves the workspace root dirdectory
somewhere else, such as the user's home directory.
---
The 'config' directory is a bit of a misnomer. It is really a working area
for eclipse to store things that eclipse feels entitled to store,
that are not specific to a particular project or workspace.
Importantly, the server writes to this directory, which means that in order
to allow installations of ycmd on readonly filesystems (or shared
installations of ycmd), we have to make it somehow unique at least per user,
and possibly per ycmd …
> [READY] Support multi-user installation for Java

- .vimspector.json
This allows debugging of ycmd tests directly using vimspector. I use a
mapping which runs the test under the cursor, so one of the variables it
asks you for it "test" which is essentially arguments to nosetests.
NOTE: It doesn't work on windows, and it requires the use of a
virtualenv at the moment. This is mainly due to a limitation of
vimspector that it only has simple variable replacement in its config.
It's actually possible to set variables based on shell commands so if the use of venv is painful for anyone else who actually uses it I can improve that.
Demo:
To use:
- install Vimspector: https://puremourning.github.io/vimspector-web/. enable the `HUMAN` mappings (or the vs ones if you prefer. or write your own)
- install the python debugger `cd /path/to/vimspector; …
> [READY] Add vimspector config

- ycmd/tests/clangd/get_completions_test.py
This is so that the completion cache is cleared on each test, rather than repeatedly returning the wrong value from the cache.
SharedYcmd clears the cache for this exact reason, so adding WithRety _after_ SharedYcmd meant that the test just took longer to flake. Now it retries properly (maximally).
For the record: @WithRetry should always be the first decorator added, after any decorator that skips the test. So:
1. Skip decorators
2. Retry decorators
3. ycmd instance decorators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1269)
> Apply retry outside of SharedYcmd

- azure-pipelines.yml
- azure/windows/install_dependencies.bat
I think this _might_ work around the python 2.7 issue, but frankly I have no clue why it's an issue in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1270)
> [Ready] Fix azure python 2.7 on windows

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/rust/diagnostics_test.py
Clangd started populating diagnostic's code field with relevant information with https://reviews.llvm.org/D60822 and https://reviews.llvm.org/D58291. 
This patch aims to surface that information to ycmd users, as vscode does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1239)
> [READY] Print diagnostic code field

- README.md
It referred to Valloric/ycmd instead of ycm-core/ycmd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1278)
> [READY] Fixing Codecov badge to use the right link

- README.md
- ycmd/completers/go/go_completer.py
- ycmd/completers/language_server/generic_lsp_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/tests/language_server/generic_completer_test.py
Instead of being fairly dumb and making concrete LSP completer
implementation override the entire GetProjectRoot, provide a way for LSP
completers to specify a list of files that indicate the root of the
project and try to find at least one of those files.
Completers that need more control (ex. jdt.ls) can still override
GetProjectRoot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1279)
> [READY] Make GetProjectRoot more useful

- .clang-tidy
- cpp/pybind11/pybind11/attr.h
- cpp/pybind11/pybind11/cast.h
- cpp/pybind11/pybind11/detail/class.h
- cpp/pybind11/pybind11/detail/common.h
- cpp/pybind11/pybind11/detail/internals.h
- cpp/pybind11/pybind11/detail/typeid.h
- cpp/pybind11/pybind11/eigen.h
- cpp/pybind11/pybind11/embed.h
- cpp/pybind11/pybind11/functional.h
- cpp/pybind11/pybind11/iostream.h
- cpp/pybind11/pybind11/numpy.h
- cpp/pybind11/pybind11/pybind11.h
- cpp/pybind11/pybind11/pytypes.h
- cpp/pybind11/pybind11/stl.h
- cpp/pybind11/pybind11/stl_bind.h
- cpp/ycm/ClangCompleter/CompilationDatabase.cpp
- cpp/ycm/ClangCompleter/CompilationDatabase.h
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/PythonSupport.h
Reviewing by commits will be easier.
- First commit just makes ycmd pass `py::list` and `py::object` arguments by value, since they are only 8 bytes (actually `sizeof(PyObject*)`).
- Second commit updates pybind11 library to the latest release. The only change that concerns us is that `py::enum_`s are now considerably smaller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1285)
> [READY] Pybind11 update

- ycmd/completers/language_server/language_server_completer.py
Right now ycmd is using strings as LSP IDs. What's worse is that those strings are actually just `int()` instances passed through `str()`, making ycmd just work harder for no reason.
Let me justify the "no reason" part:
- Notifications don't have IDs and are therefore unaffected.
- Server-to-client requests just forward whatever the server set as the ID to `lsp.Reject()` and are therefore unaffected.
- Client-to-server requests allow the client to set a request ID and the server needs to reply with the exact same ID, so if ycmd sends a number, server can't respond with a string.
- So instead of doing `str( self._last_id )` to send the request and `str( message[ 'id' ] )`, we can just drop `str()` from these two.
Sending request IDs as strings, while conforming to JSON-RPC specification, …
> [READY] Use numbers for LSP request IDs

- .vimspector.json
- run_tests.py
- test_requirements.txt
The `--dump-path` option was there for this precise purpose, but until [now](https://github.com/puremourning/vimspector/pull/44) we couldn't use it in Vimspector. Now we can, so let's use it.
Had to move the building of the test completer, because npm spam broke the --dump-path output .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1294)
> [READY] Vimspector: Remove duplication of python path

- ycmd/completers/language_server/generic_lsp_completer.py
- ycmd/tests/language_server/generic_completer_test.py
This makes D language server return top level completions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1283)
> [READY] Use column_codepoint when forcing completion for GenericLSPCompleter

- .gitmodules
We forgot to update the regex module when it gained support for Unicode 12.0, so... here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1297)
> [READY] Update regex module

- ycmd/completers/cpp/clangd_completer.py
- ycmd/tests/clangd/utilities_test.py
The regex used to parse the clangd version only allows major numbers as
a single digit. Consequently, this results in a parsing failure for the
following version string:
```
clangd version 10.0.0 (https://github.com/llvm/llvm-project.git bd68a052f292b5df7c5717bd880d796ac7507fc0)
```
This diff changes the regex to allow for two digit major version
numbers, and changes the comparison from a string based comparison to a
tuple/int based comparison to ensure that 10.0.0 > 7.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1299)
> Don't consider clangd 10 out of date.

- ycmd/completers/language_server/language_server_protocol.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/handlers.py
- ycmd/tests/language_server/language_server_connection_test.py
- ycmd/utils.py
Send a more compact JSON to ycmd clients and to language complaters (LSP and TSServer). To my surprise, about 1/8 of the json-encoded string is unnecessary whitespace.
Reference: https://docs.python.org/3/library/json.html (search for "Compact encoding")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1295)
> [READY] Send compact JSON to language servers and clients

- README.md
complements https://github.com/ycm-core/YouCompleteMe/pull/3462
from there: 
> I was installing ycm on a new machine and looking at docs and found broken links to valloric.github.io. It looks like the repos moved from the valloric github account to ycm-core and github automatically redirects links in the repos but not to github pages sites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1300)
> valloric.github.io -> ycm-core.github.io

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/get_completions_test.py
- ycmd/tests/python/subcommands_test.py
This version of jedi correctly handles python's type hints and I think supports python 3.8.
Jedi now bundles [`typeshed`](https://github.com/python/typeshed) as a submodule, which might throw off some users. This is also why our tests sometimes end up in `typeshed/stdlib/2and3/builtins.pyi`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1302)
> [READY] Update jedi to 0.15.0 and parso to 0.5.0

- ycmd/completers/cpp/clangd_completer.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/clangd/testdata/GetDoc_Clang_test.cc
- ycmd/tests/clangd/testdata/docstring.h
Requires clangd 9.0.0, so half of the tests are commented out. However, since some users are already using clangd 9, we can already provide GetDoc for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1333)
> [READY] Add GetDoc for clangd completer

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/clangd/diagnostics_test.py
Forces clangd to reparse the file on every `BufferVisit` notification,
so diagnostics are updated to reflect changes in included headers.
Headers still need to be saved to disc because clangd isn't concerned
about dirty files in the TU's main file's preamble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1332)
> [READY] OnBufferVisit for clangd completer

- ycmd/completers/typescript/typescript_completer.py
- ycmd/completers/typescriptreact/hook.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/testdata/test.tsx
As suggested in https://github.com/ycm-core/YouCompleteMe/issues/3499, this is a pull request for adding support for .tsx files to YouCompleteMe. 
The text of that issue is copied below for convenience.
*******
Since vim has added [two new file types](https://github.com/vim/vim/issues/4830) for Javascript and Typescript files that use JSX syntax, files with extensions .jsx and .tsx now have the filetype "javascriptreact" and "typescriptreact" respectively.
Is it possible to enable the typescript auto completer for those filetypes as well by default? Right now when editing those files I get the error `No semantic completer exists for filetypes: ['typescriptreact']`.
My temporary workaround for now is to put the following line in my .vimrc:
au BufNewFile,BufRead *.tsx set …
> added support for typescriptreact (.tsx) files

- README.md
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/java/testdata/extra_confs/.ycm_extra_conf.py
fixes ycm-core/YouCompleteMe#3505
I also considered just letting every LSP completer do this kind of configuration. For that I'd like to check if and how are other LSP servers configured.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1339)
> Allow user configuration of Format subcommand for JDT completer

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/testdata/goto/child.py
- ycmd/tests/python/testdata/goto/parent.py
PR #1275 broke GoTo in python in more ways than one. See:
- https://github.com/ycm-core/YouCompleteMe/issues/3458
- https://github.com/ycm-core/ycmd/issues/1341
Changes in the behaviour:
- GoTo, GoToDefinition and GoToDeclaration now do what GoToType used to
do.
- We don't expose jedi's `goto_assignments` which can be useful, but we
do have GoToReferences that calls jedi's `usages()`.
- This means that `GoTo` on `self.x` will now jump to the definition
of the type of `x`, while `GoToReferences` will do what is expected.
- The `goto_usages` for this case returns "weird" locations, see #1341
for details.
There's a test for member function access that was broken before.
--- …
> [READY] Revert #1275

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/python/python_completer.py
- ycmd/tests/python/signature_help_test.py
- ycmd/tests/python/testdata/signature_help.py
We use the Jedi API [`call_signatures`](https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Script.call_signatures) for this.
We require some code to:
* Generate a signature string that makes sense to users (the call_signatures returns just the [metadata](https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.CallSignature)). 
* Some stuff to work out what that means for parameters in terms of offsets (in bytes) into the resulting string
* Working out the active signature and parameter (using [index](https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.CallSignature.index))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/134 …
> Python: implement signature help

- ycmd/completers/java/java_completer.py
- ycmd/tests/java/signature_help_test.py
- ycmd/tests/java/testdata/extra_confs/simple_extra_conf_project/src/SignatureHelp.java
This is the basic LSP support, but we augment the trigger characters with `,` to match what clangd and python do. Makes YCM more consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1345)
> Java: Implement and test signature help

- ycmd/completers/go/go_completer.py
- ycmd/tests/go/debug_info_test.py
- ycmd/tests/go/diagnostics_test.py
- ycmd/tests/go/get_completions_test.py
- ycmd/tests/go/go_module/td/test.go
- ycmd/tests/go/subcommands_test.py
Attempt 2, it passed tests in my fork.
- We're using `DefaultSettings()` to set `hoverKind` to `Structured`, beecause gopls is inconsistent with hover formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1351)
> [READY] Implement GetDoc for gopls

- docs/index.html
- docs/openapi.yml
- ycmd/completers/completer.py
- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/handlers.py
- ycmd/request_wrap.py
- ycmd/responses.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/clangd/testdata/FixIt_Clang_cpp11.cpp
- ycmd/tests/rust/subcommands_test.py
When making an `executeCommand` request, a LSP server might in exchange
send a series of "things", which we expect to be `applyEdit` requests.
We then store those requests in a list until the LSP server responds to
the original `executeCommand` and finally let the specific LSP completer
implementation figure out what to do with those unconsumed `applyEdit`s.
This allows ycmd to forward an incomplete `codeAction` from clangd to a
client in order to save time computing expensive `codeActions`.
The exchange should look like this:
- A client makes a `FixIt` request.
- ycmd makes a `codeAction` request to clangd.
- clangd responds with a mix of resolved and unresolved code actions.
- ycmd transforms resolved code actions in `FixIts` and forwards
unresolved ones.
- A client lets a user choose a …
> [READY] Implement `applyEdit` to allow incomplete `FixIts`

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/utilities_test.py
- ycmd/tests/go/diagnostics_test.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/rust/diagnostics_test.py
Seems like the original LSP implementation forgot about
/detailed_diagnostic. Later, clangd completer implemented locally what
works for all LSP completers.
This commit moves the code from ClangdCompleter to
LanguageServerCompleter and adds a few tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1355)
> [READY] Implement /detailed_diagnostic for LSP servers

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/java/get_completions_test.py
- ycmd/tests/language_server/generic_completer_test.py
- ycmd/tests/language_server/language_server_completer_test.py
A server may not be a `completionProvider`, in which case we shouldn't
send `textDocument/completion` requests.
In the current state of the PR, `_is_completion_provider` can only be set to `True` after server responded to `initialize` request. That's why we can just test `if self._is_completion_provider` in `ComputeCandidatesInner`, making the `self._ServerIsInitialized()` check redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1348)
> [READY] Respect completion capability of LSP servers

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/completers/language_server/simple_language_server_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/tests/java/java_completer_test.py
We can finally move all the FixIt LSP mess into the `LanguageServerCompleter`. It should even work for `GenericLSPCompleter`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1354)
> [READY] Make LSP codeActions generic

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
4chan server can return `'result':null` which is ok by the protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1360)
> [READY] Properly handle textDocument/completions null response

- cpp/CMakeLists.txt
Arch now uses python3.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1362)
> Add detection for python 3.8 and 3.9

- .gitmodules
- azure-pipelines.yml
- azure/linux/install_dependencies.sh
- ycmd/user_options_store.py
Python deprecated accessing abstract collections through `collections` module in favour of `collections.abc`. Frozendict was never fixed, but ycmd has had `HashableDict` for a while which is also an immutable dictionary and a more robust\* one than `frozendict`. Thus the fix for the broken `frozendict` dependency is to just use our own `HashableDict` even for user options.
\* `frozendict.__getitem__()` returned values by reference, so it was still possible to mutate the dictionary. `HashableDict.__getitem__()` calls `deepcopy()` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1367)
> [READY] Remove frozendict

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/go/go_module/td/signature_help.go
- ycmd/tests/go/signature_help_test.py
Ycmd couldn't cope with the following:
- `result:null` - happens with gopls on `non_existent_func(`
- `result:{'signature':[]}` - i.e. no parameters; happens with gopls for every function that has no parameters.
Both of those are valid responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1370)
> [READY] Make textDocument/sigantureHelp response handling more robust

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/typescript/subcommands_test.py
This is the only thing that typescript-language-server could do and we couldn't.
There's also a removed `try` and `catch` statement, since the exception is impossible to trigger as far as I can tell and isn't covered by tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1372)
> [READY] GoToImplementation for TSServer

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/go/subcommands_test.py
The `GetType` response from clangd, in the current master, takes two lines. This causes "hit <Enter> to continue" message in vim, which can be annoying.
The first line is `Declared in namespace foo` and the second is something like `struct Foo{}`.
After some discussion with @maximebl, we thought the most readable way of putting all the information on the same line is `struct Foo{}; Declared in namespace foo.`
RFC because popups are an options, even though I haven't been too fond of that idea so far, though I can be convinced that they might be better.
&nbsp;
The other change in this PR is actually a bug fix - the `GetDoc` response should have been using the detailed info response, not the message response. This goes for clangd as well as gopls. Feel free to tell me that this should be in …
> [RFC] Clangd GetType format

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
All LSP completers were already using the exact same `_RestartSever()`, so this PR moves it into the base class.
When `GetType` and/or `GetDoc` is defined for an LSP completer, it is automatically discovered in the base class, so we don't have to repeat it everywhere in the `GetCustomSubcommands`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1369)
> [READY] Simplify LSP completer subcommand discovery

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/language_server/language_server_completer_test.py
As discussed on gitter, this implements `documentChanges` because some servers ignore thte capabilities and always send `WorkspaceEdits` containing versioned `documentChanges`. Speaking of "versioned", we are just ignoring the versions, which seemed to work for typescript-language-server and rust-analyzer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1368)
> [READY] Implement WorkspaceClientCapabilities.workspaceEdit.documentChanges

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/language_server/language_server_completer_test.py
Instead of reporting `No hover information.` we can actually report `No diagnostic/type information available.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1371)
> [READY] User-friendly clangd hover errors

- ycmd/completers/completer_utils.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/testdata/test.tsx
Fixes #1377 
The pull reequest that added typescriptreact support did not add the default semantic completion triggers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1378)
> [READY] Add typescriptreact default semantic triggers

- ycmd/completers/typescript/typescript_completer.py
@bstaletic as discussed
this pull request is related to a problem that occurred on a bigger project
where on initial tsserver go to def load it would take up to more then 10 seconds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1376)
> increased timeout since some bigger projects seemed to hit the timeout

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/subcommands_test.py
Just what the title says. There are two things I need to point out. 
There *is* a [`/formatRange`](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Abstractions/OmniSharpEndpoints.cs#L12) request, but it is only concerned with the end codepoint. Without the start codepoint, ranged formatting request seems completely broken. https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Abstractions/Models/v1/Format/FormatRangeRequest.cs
The `/codeformat` request formats the entire file and has no format options: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Abstractions/Models/v1/CodeFormat/CodeFormatRequest.cs
--- …
> [READY] Implement `Format` subcommand for the C# completer

- build.py
I run YouCompleteMe on Windows at work. I frequently run into issues with the CMake detection logic in `build.py`. 
In these cases CMake is always installed, in `%PATH%`, and callable from `cmd.exe`:
``` bash
> where python
{ Prints path to cmake.exe }
> cmake --version
{ Prints CMake version }
> build.py
ERROR: Unable to find executable 'cmake'. CMake is required to build ycmd
```
I usually work around this issue temporarily by hard-coding the problematic line:
```patch
-return FindExecutableOrDie( 'cmake' , 'CMake is required to build ycmd' )
+return '''C:\Program Files\CMake\bin\cmake.exe'''
```
It would be nice to have an argument where the CMake executable can be quickly specified. Any thoughts on adding such an argument?
Here is a simple patch... I'm happy to change anything.
--- …
> Feature Request: Add build.py CMake executable location argument

- ycmd/completers/completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/python/python_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/cs/signature_help_test.py
- ycmd/tests/python/get_completions_test.py
- ycmd/tests/python/signature_help_test.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/signature_help_test.py
Fixes https://github.com/ycm-core/YouCompleteMe/issues/3570
During the review of signature help we changed so that
signature_triggers was None when disabled. This was fixed for LSP, but
this broke all other implementations which assume they can just set the
triggers manually.
Fixed by making signature_triggers private (_signature_triggers) and
adding a public method to set them. This keeps the logic in individual
completers simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1384)
> [READY] Fix disable signature help

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/subcommands_test.py
Fixes #1385 
Returning `{ 'detailed_info': None }` and `{ 'message': None }` causes problems for clients, including YCM. Instead, we should raise an exception and tell the user that there's no type info/docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1386)
> [READY] Raise exception on empty C# /typelookup

- ycmd/completers/all/identifier_completer.py
- ycmd/completers/completer_utils.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/tests/bindings/cpp_bindings_general_test.py
- ycmd/tests/bindings/cpp_bindings_vectors_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
Pybind can handle being passed either `bytes` or `str`, so we don't need to convert before calling a C++ API from python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1387)
> [READY] Drop `ToCppStringCompatible()`

- cpp/ycm/CandidateRepository.h
- cpp/ycm/Character.h
- cpp/ycm/CodePoint.cpp
- cpp/ycm/CodePoint.h
- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/IdentifierDatabase.h
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/Result.h
- cpp/ycm/Utils.cpp
- cpp/ycm/Utils.h
- cpp/ycm/Word.cpp
- cpp/ycm/benchmarks/IdentifierCompleter_bench.cpp
- cpp/ycm/tests/IdentifierUtils_test.cpp
- Gets rid of a few warnings, like:
- `-Wdeprecated`
- `-Wweak-vtables`
- `-Wsign-conversion`
- `-Wextra-semi`
- Removes unused code
- Avoids `operator==` on hash maps, since not all implementaitons have
the operator defined. This brings us a little closer to using flat
hash maps.
- Removes the deprecated (C++11) and removed (C++17)
`std::binary_function`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1388)
> [READY] Minor pre-C++17 cleanup

- ycmd/completers/cpp/flags.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/java/conftest.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/java/testdata/multiple_projects/.ycm_extra_conf.py
- ycmd/tests/java/testdata/multiple_projects/src/core/.classpath
- ycmd/tests/java/testdata/multiple_projects/src/core/.project
- ycmd/tests/java/testdata/multiple_projects/src/core/java/com/puremourning/widget/core/Utils.java
- ycmd/tests/java/testdata/multiple_projects/src/input/.classpath
- ycmd/tests/java/testdata/multiple_projects/src/input/.project
- ycmd/tests/java/testdata/multiple_projects/src/input/java/com/puremourning/widget/input/InputApp.java
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/utils.py
Store all settings returned from the Settings function
Allow extra conf to supply project directory. This is useful at least
for java with complex workspaces containing multiple .project files
For the output in debug info, we _could_ change to show all settings,
but for now, let's keep it as it was before.
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1381)
> [READY] Support user-specified project directory in LSP servers

- ycmd/utils.py
Currently this utility only works because of side-effects. During tests,
pytest does its magic and loads `importlib.machinery`. During the normal
use, there's no pytest, but jedi creates the same side-effect.
As a result, `LoadPythonModule()` only needs to get a reference to
`importlib` to work.
import ycmd
ycmd.utils
The above snippet raises an `AttributeError` and looks just like
`LoadPythonModule`. Instead the correct snippet would be
import ycmd.utils
ycmd.utils
The tests are missing because, considering the side-effects, it is
impossible to write one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1398)
> [READY] Make LoadPythonModule self-contained

- .ycm_extra_conf.py
- run_tests.py
- ycmd/server_utils.py
Removing python-future from the extra conf was missed in the python2
support drop pull request.
Numpydoc is now appended to the sys.path to allow python to find the
system-wide numpydoc instead. This is because we're unlikely to update
numpydoc as the v0.9.0+ depend on sphinx and that would be rather insane
to keep around as a submodule.
This way, for users that have a newer numpydoc and use the new features of it, we allow jedi to use that new numpydoc, but for other users the bundled version still works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1396)
> [READY] Clean up python's sys path

- README.md
Unless I am mistaken, #1381 didn't document `project_directory`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1404)
> [READY] Document #1381

- azure-pipelines.yml
- azure/lint.sh
- azure/linux/install_dependencies.sh
- build.py
- pytest.ini
- run_tests.py
- valgrind.suppressions
- ycmd/tests/shutdown_test.py
Python 3.8 is finally nice enough to not get in the way of running valgrind with `PYMALLOC=malloc`. The question is what should we run through valgrind? Here are the options:
- `ycm_core_tests`, which embeds the python interpreter. Currently valgrind detects [a leak in pybind](https://github.com/pybind/pybind11/pull/2020)
- `ycm_benchmarks`, same comment as the above.
- nose tests? I haven't tried this, but valgrind will detect [another leak in pybind](https://github.com/pybind/pybind11/pull/2024)
- Some combination of the above?
Currently the CI is running only a single benchmark, from `ycm_benchmarks` binary.
CI is also complaining about a missing `libsqlite3-dev` package. We probably should fix it, even though the tests aren't broken.
--- …
> [READY] Run valgrind in CI

- azure-pipelines.yml
- azure/linux/install_dependencies.sh
- valgrind.suppressions
Use latest macOS and linux images and drop testing on VS2015.
The macOS and Windows changes are made because azure is dropping VS2015 and macos 10.13 images. Linux was just convenient.
There's also a bump to clang 3.9 and that's because Ubuntu 18.04 doesn't ship clang older than that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1406)
> [READY] Update CI images

- azure/linux/install_dependencies.sh
CI started failing due to not being able to find `libsqlite-dev` ; looks like we need an `apt-get update` first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1409)
> [READY] Make sure we have the latest apt info

- ycmd/completers/language_server/generic_lsp_completer.py
- ycmd/tests/language_server/generic_completer_test.py
Since people seem to be actually using the generic LSP completer, it is high time we fixed the way we format the hover response. It would be nice if we could just forget about the deprecated MarkedString, but even among the 4 officially supported LSP servers, we're exercising every possible hover response. Hints of what I think of `interface Hover` is perhaps visible in one of the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1414)
> [READY] Improve hover formatting for the GenericLSPCompleter

- requirements.txt
- test_requirements.txt
Also adds `requirements.txt` so that we can get alerts for runtime dependencies too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1412)
> [READY] Update psutil to silence github alert

- ycmd/completers/completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/typescript/typescript_completer.py
We can actually use `threading.Lock` everywhere.
Where possible, we avoid taking and releasing the lock multiple times, by introducing `Foo()` and `FooNoLock()`, where the former takes a lock and calls the latter. The `LanguageServerCompleter` shutdown procedure is complex enough that we can't avoid multiple locks, so two places where this `FooNoLock()` thing isn't possible are:
- `_RestartServer()` in `LanguageServerCompleter`.
- `StartServer()` in `JavaCompleter` when it throws a `LanguageServerConnectionTimeout`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1411)
> [READY] Use non-reentrant locks everywhere

- build.py
- requirements.txt
- valgrind.suppressions
Because some users really don't. Seems like we can't even touch anything remotely related to pip without getting bug reports...
This means that we won't always be able to compile watchdog's fsevents extension module.
This won't affect Windows and Linux users, but on macOS, without fsevents, watchdog will fall back to the slower kqueue API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1422)
> [READY] Do not assume that users have setuptools available

- .gitignore
- build.py
If `GOBIN` environment variable is not set, `build.py --go-completer` will not install `gopls` to `third_party/go/bin`.
Please help me to review this PR, thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1427)
> Make sure gopls installed in bin folder

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/testdata/GetDoc.py
This was causing GetDoc to look like strange "---" to be printed for
without any actual documentation. This was way worse/more noticable with
auto-hover.
It seems that Jedi can return whitespace entries in the list, so we just
strip them and ignore any empty lines.
Example: ![example](https://files.gitter.im/Valloric/ycmd/FvBl/Screenshot-2020-04-30-at-20.14.08.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1431)
> [READY] Don't return whitespace-only lines in GetDoc

- JAVA_SUPPORT.md
- cpp/CMakeLists.txt
- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- docs/openapi.yml
- update_omnisharp.py
- ycmd/completers/completer.py
- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/identifier_utils.py
- ycmd/request_wrap.py
- ycmd/tests/clangd/utilities_test.py
- ycmd/tests/java/debug_info_test.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/java/testdata/simple_gradle_project/src/main/java/com/test/TestWidgetImpl.java
- ycmd/tests/java/testdata/simple_gradle_project/src/test/java/com/test/AppTest.java
- ycmd/tests/java/testdata/simple_maven_project/src/main/java/com/test/TestWidgetImpl.java
- ycmd/tests/java/testdata/simple_maven_project/src/test/java/com/test/AppTest.java
- ycmd/tests/tern/get_completions_test.py
- ycmd/tests/typescript/testdata/signatures.ts
- ycmd/utils.py
Hi,
a bunch of typo fixes mostly found by `codespell` after I stumbled manually over some. The first commit bundles most of them in documentation and code comments, so they shouldn't have an impact.
The second changes a function name, so technically an internal API break.
The third is still documentation, but it looks like a json scheme which might or might not be used to verify instances which would need to be fixed as well (or are finally valid now).
Note that while these change `docs/openapi.yml` I have not regenerated the html files as the README advises as I have no working `npm` setup and don't particular fancy one for this right now.
(You may squash, edit & discard to your hearts content – I do not claim copyright ownership for typo fixes.)
--- …
> Various typo fixes

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/testdata/goto/nested_import/importer.py
- ycmd/tests/python/testdata/goto/nested_import/to_import.py
- ycmd/tests/python/testdata/goto/requirements.txt
Fixes https://github.com/ycm-core/ycmd/issues/1432
I've left it to `jedi` to work out where the project directory is using [get_default_project](https://github.com/davidhalter/jedi/blob/d16355fcf25db57dd0e6e4566ce1312274792f3e/jedi/api/project.py#L365). This relies on the presence of certain files or directories to correctly identify the project root, so it's not foolproof but should work for the majority of cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1437)
> Fix python GOTO from nested modules

- ycmd/responses.py
This addresses the ycmd side of https://github.com/ycm-core/YouCompleteMe/issues/3662
My concern is whether or not this is a subtle API break. Is it possible that some other ycmd client, at this point, depends on `Location` holding the "real" path?
Note that we're changing [`realpath`](https://docs.python.org/3/library/os.path.html#os.path.normpath) to [`abspath`](https://docs.python.org/3/library/os.path.html#os.path.abspath). Neither of those are [`normpath`](https://docs.python.org/3/library/os.path.html#os.path.normpath).
I'm not sure if `os.path.realpath()` is supposed to behave like ycm-core/YouCompleteMe#3662 describes, even on Winblows.
@puremourning Please test the complete solution, outlined in the bug report.
--- …
> [READY] Use `os.path.abspath` in ycmd.responses.Location

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/subcommands_test.py
Resolving code actions is annoying.
1. ycmd sends `textDocument/codeAction` request
2. A LSP server responds with at least one code action that requires an
`executeCommand` request to be resolved.
3. After sending an `executeCommand` request, the server is supposed to
send N server-to-client requests to "explain" the code action.
4. The server finally responds to the `executeCommand` request.
We assume that, in step 3, the server would send a single `applyEdit`
request. This turned out to be a false assumption in some cases.
Specifically, it's possible that a server sends a `window/showMessage`
notification and then respond to `executeCommand`. (Looking at you, clangd!)
This pull request takes into account this possibility.
--- …
> [READY] Allow "empty" responses after an `executeCommand` request

- ycmd/completers/python/python_completer.py
- ycmd/responses.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/testdata/rename/one.py
- ycmd/tests/python/testdata/rename/two.py
- ycmd/utils.py
Uses Jedi's [Script.rename](https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Script.rename) API.
To work out the chunks, we take the "new code" and the "old code" from Jedi and use `difflib` to diff them. The [get_opcodes()](https://docs.python.org/3.5/library/difflib.html#difflib.SequenceMatcher.get_opcodes) function returns exactly what we need to generate our chunks and apply them in the editor. 
The only remaining snag is to convert character offsets to 1-based line/column byte offsets. This is easy enough with the following algorithm:
* Pre-compute the character offsets of all `\n` characters in the text
* Given a character offset, scan the list of line offsets (TODO: This can be optimised, as it's necessarily a sorted list) until you find the newline at the end of the …
> [READY] Add RefactorRename support for python

- build.py
This fixes the check when running `install.py` in YCM, or when running
from a different dir.
Before this change you _always_ received the warning when running install.py from YCM's directory. Now it works properly, using the absoute path to the check script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1459)
> [READY] Use full path to check java version

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
According to my testing, this works. Latest rust-analyzer exercises its freedom to use offsets, instead of strings and it also omits `activeSignature` when there's only one.
No tests, because [the missing `rustfmt`](https://rust-lang.github.io/rustup-components-history/) is preventing us from upgrading to the newer nightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1464)
> [READY] Support signature parameter offsets in LSP signatureHelp responses

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/rust/subcommands_test.py
The LSP has been clarified since we first implemented codeActions. It's
clear now from the spec that we shoud supply a range that corresponds to
the cursor position (or visual selection). The diagnostics supplied
should be those that overlap this position/range.
Where there is no visual seletion we have no choice but to supply an
(arbitrary) range which is the cursor position to the cursor position +
1 unicode character. It's not clear if that's strictly correct but
realistically it matches what editors like Vim actually do/show (a range
of 1 char).
Historically ycmd has provided FixIts for any diagnostics on the current
line. We retain that behaviour when there are no diagnostics that
overlap the actual cursor position - if so, we find any diagnostics that
overlap the line of cursor …
> [READY] Supply code action ranges according to cursor position

- build.py
One commit fixes the java version parsing problem when `JAVA_TOOL_OPTIONS` is defined and the other fixes gopls installation when `GOROOT` is defined. The fix is the same in both cases - `new_env.pop( $VAR, None )`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1472)
> [READY] Small fixes to build.py

- build.py
Passing `-A` flag to CMake, in combination with `-G Ninja` errors with:
```
CMake Error at CMakeLists.txt:26 (project):
Generator
Ninja
does not support platform specification, but platform
x64
was specified.
```
Fixes #1467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1475)
> [READY] Do not set architecture on Windows when using Ninja

- docs/index.html
- docs/openapi.yml
- ycmd/completers/completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/default_settings.json
- ycmd/handlers.py
- ycmd/responses.py
- ycmd/tests/go/get_completions_test.py
- ycmd/tests/java/get_completions_test.py
- ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/MethodsWithDocumentation.java
- ycmd/tests/rust/get_completions_test.py
- ycmd/tests/test_utils.py
Again, opening this for thoughts while testing.
Previously we would do completion/resolve for every matching completion candidate up front. This was also embarrassingly serial. For 100 candidates, we'd do 100 synchronous resolve requests. This can lead to timeouts.
This leads to unusable performance on the Godot server (because for some reason there are a lot of candidates and they take a _long_ time to resolve serially).
So we implement an endpoint to resolve a completion item on-demand, and change the resolve behaviour so that we only ever resolve 10 candidates up-front.
The approach is to add a `'resolve'` key to the `extra_data` dictionary which is an ID telling the client that this item needs to be resolved to fill in the extra data documentation. If this key is not present, resolve …
> [READY] Resolve completion items on demand rather than upfront

- test_requirements.txt
- valgrind.suppressions
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/go/get_completions_test.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/java/get_completions_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWithDocumentation.java
- ycmd/tests/test_utils.py
This is actually needed to make YCM test stable but makes sense to do same in server. The reason that we're seeing flakes in the "Resolve" tests in the YCM tests suite is that we're editing the "MathodsWithDocumentation.java" class _while_ asking jdt.ls to use the class in that file to return documentation. I think what's happening is that the _change_ to the file makes it unparseable, and jdt.ls drops parts of the AST (or something).
Anyway, I found that if we use a class file which is _not_ being edited and/or requesting completion _within_ it, we get stable responses for the completionItem/resolve. So let's do that. 
It also means we can run those tests on Windows.
Incidentally, there is another valigridn error that popped up. None of our code has changed, so suppressed it.
Tests give …
> [READY] Make test reliable - use a file that's not changing to get the docs

- .ycm_extra_conf.py
Remove unused  `import os` in [.ycm_extra_conf.py](../blob/master/.ycm_extra_conf.py)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1466)
> Remove unused import

- README.md
- ycmd/completers/language_server/generic_lsp_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/generic_completer_test.py
In the scenario where we are starting the server then connecting to it
over TCP, it makes sense to use an unused local port, rather than
requiring the user hard-code one in their configuration.
This change allows the Generic LSP config to set 'port' to '*' in which
case an unused local port is selected and used. The selected port is
made available to the 'cmdline' as '${port}'.
This is needed to support the new PHP completer in a better way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1482)
> [READY] Support generating a port when connecting to LS over TCP

- .gitignore
- build.py
- third_party/tsserver/package.json
- ycmd/completers/typescript/typescript_completer.py
NPM 7 broke the way we used to install TSserver so, now we install it just like Tern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1494)
> [READY] Use package.json to install tsserver

- ycmd/completers/completer_utils.py
- ycmd/tests/completer_utils_test.py
It's almost a shame to remove something with 10x more tests than code, but it's not used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1503)
> [READY] Remove completer_utils._MatchesSematicTrigger

- third_party/tsserver/package.json
- ycmd/tests/javascript/diagnostics_test.py
Time to upgrade, according to one YCM user. Expectedly, tests had to be modified - in javascript mode one diagnostics is now missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1512)
> [READY] Upgrade to tsserver 4.1.2

- .gitmodules
This version drops python2 support and stops depending on pathtools. It should put an end to "I can't access `git://` from my network" complaints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1517)
> [READY] Update watchdog

- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/IdentifierCompleter.h
- cpp/ycm/tests/IdentifierCompleter_test.cpp
- ycmd/completers/all/identifier_completer.py
- ycmd/completers/cpp/flags.py
With this PR we can avoid some additional copies. The changes in the
python files allow pybind to preallocate `StringVector` objects.
NOTE: We are now moving the contents of `StringVector` objects once we
call into `ycm_core.so`. This doesn't make stuff blow up, but python
code should be aware that `StringVector` objects are mutable, just like
python lists.
A really ugly part of this PR is the use of mutable l-value references
to move data. This makes the code harder to reason about, but the reason
for it is that pybind11 doesn't support r-value reference parameters.
A possible solution would be:
```c++
template <typename T>
using force_rvalue_to_lvalue_conversion = std::conditional_t<std::is_rvalue_reference<T>, T&, T>;
template <typename Return, typename... Args>
constexpr auto …
```
> [READY] Optimize IdentifierCompleter

- build.py
- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
- cpp/ycm/benchmarks/CMakeLists.txt
- cpp/ycm/tests/CMakeLists.txt
Cmake deprecated support for cmake2 and RHEL7 has cmake 3.14 available.
Besides that, the `FindPythonLibs.cmake` is also replaced with `FindPython3.cmake`, because the former is also deprecated.
With cmake3, it's possible to not use `CMAKE_CXX_FLAGS` global variable and stick to target based commands. This is what I've done for the most part. The only file that doesn't fit this is the top level `cpp/CMakeLists.txt`.
One thing to note, regarding `target_whatever()` are all the `PUBLIC`/`INTERFACE`/`PRIVATE` modifiers. Here's what they mean:
- `PRIVATE` - the dependency is "local" to the specified target. Targets that depend on this target don't have the specified dependency.
- `INTERFACE` - the specified dependency is not directly applied to the specified target. However, targets that …
> [READY] Refactor cmake files and require cmake 3.14

- cpp/ycm/PythonSupport.cpp
- cpp/ycm/PythonSupport.h
- cpp/ycm/benchmarks/PythonSupport_bench.cpp
Using the raw C API allows access to objects internals without checking
for errors. This is fine, because ycmd already checks everything
necessary. Plus, pybind11 can easily fall back to generic
implementations - for example, `len()` is `PyObject_Len()`, even if we
know that the object is `PyListObject*`. The C API, thus, allows us to
exploit the knowledge of types that pybind11 doesn't have.
And yes, I understand that this might be a controversial pull request. The performance improvements are from 3% to 10%, depending on the specific benchmark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1515)
> [READY] Use raw CPython API in PythonSupport.cpp

- README.md
Since I notice we are using #include<filesystem> which is boost independent, but requires updated compilers as per the c++ compiler support info [here](https://en.cppreference.com/w/cpp/compiler_support)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1527)
> Update compiler requirements README.md

- ycmd/__main__.py
- ycmd/wsgi_server.py
If stdin and/or stdout is redirected by the shell, `sys.stdin` and `sys.stdout` will be `None` and `print()` won't work. The `sys.stdin` part is easy, because we never redirect it. However, we attempt to redirect `sys.stdout` to our log file. Python thinks that succeeds and then we're left with no way to check if we're allowed to call `print()` in `wsgi_server.py`. A workaround is to check if `sys.stdout` is `None` and skip the pointless redirection - `print()` will fail anyway.
Fixes #1525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1534)
> [RFC] Do not touch stdin/stdout when they are redirected by the shell  

- ycmd/completers/cs/cs_completer.py
I have just remembered that we've had a user with a broken `/etc/hosts` and so he couldn't resolve `localhost`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1537)
> [READY] Avoid 'localhost' in C# URLs

- cpp/ycm/CodePoint.cpp
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/Utils.h
- cpp/ycm/ycm_core.cpp
Nothing too special. Most noteworthy changes are in `IdentifierUtils.cpp`:
1. Remove unused `StringCompare` class.
2. Remove pairs from `LANG_TO_FILETYPE` where the value is just a lowercase version of the key - that's covered by the fallback branch.
3. To avoid the constructor at global scope, `LANG_TO_FILETYPE`'s type is now `array<pair<string_view, string_view>, N>` and is `constexpr`.
3.1. As a result, `FindWithDefault` had to be rewritten to work with `unordered_map::find` and `std::find`. Damn you libclang completer.
4. The main loop in `IdentifierUtils.cpp` is changed to use iterators instead of indices, which helps with warnings. Also, it allows us to use `std::default_searcher()` which means we don't have to use magic `index + 9` to skip over `"language:"`.
5. The rest are just …
> [READY] Clean up C++ warnings

- cpp/ycm/Character.cpp
- cpp/ycm/Character.h
- cpp/ycm/tests/CharacterRepository_test.cpp
- cpp/ycm/tests/Character_test.cpp
- cpp/ycm/tests/Normalization_test.cpp
- cpp/ycm/tests/Word_test.cpp
The assumption does hold for regular use, but tests don't always go
through `BreakCodePointsIntoCharacters()` and therefore need
`NormalizeInput()`.
Turns out this wasn't that hard. In normal use, after taking an array of identifiers, the following happens:
1. The identifier is broken into its constituent code points.
2. The array of code points is then transformed into an array of normalized strings, where each string represents a "character" (nitpick: technically a grapheme cluster).
3. Finally, we construct a `Character` from each of those strings.
4. To do this and correctly do the matching we want, we need to decompose the `Character`'s into normalized (according to Normalization Form D) code points. Note: These code points could be different than the ones we have started with, even …
> [READY] Assume input of Character constructor is normalized

- .gitmodules
- requirements.txt
- ycmd/__main__.py
- ycmd/handlers.py
- ycmd/wsgi_server.py
I'll make some more benchmarks tomorrow, but even if there's no difference between waitress and the standard library, dropping an external dependency would be nice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1509)
> [READY] Drop waitress in favour of the standard library

- cpp/CMakeLists.txt
Should fix the warning reported in https://github.com/abseil/abseil-cpp/issues/930
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1552)
> [READY] Update Abseil dependency to avoid a warning on macOS

- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/Utils.h
Three small changes:
1. `GetValueElseInsert` now uses `try_emplace` instead of `insert`. This has two benefits:
1.1. We're not constructing a `pair<K,V>` before moving it into the map. The arguments are passed directly to placement `new`, so there are fewer copies.
1.2. We can `std::move()` the key as well, because `try_emplace` is nice enough not to move before checking that the key is actually not in the map already.
2. `Result` now has padding bytes at the end. That means we can potentially reclaim the padding bytes for `other_object` in `ResultAnd<T>` with `[[no_unique_address]]`.
2.1. To actually see the benefits of this, `vector<ResultAnd<size_t>>` in `PythonSupport.cpp` was changed to `vector<ResultAnd<uint32_t>>`. The size of `ResultAnd<uint32_t>` drops from 48 bytes to 40 bytes. …
> [READY] More C++17 niceties

- ycmd/completers/language_server/language_server_completer.py
Before this commit, we were passing 0-based columns into
`CodepointOffsetToByteOffset` in LSP completer, when constructing the
`/signature_help` response.
That's clearly a violation of `CodepointOffsetToByteOffset`'s API, which
expects 1-based input. The solution is to adjust the offsets on input,
by adding 1, then subtract one from the return value so that we still
return 0-based offsets, as promised in ycmd's API.
This should be our side of https://github.com/ycm-core/YouCompleteMe/issues/3870.
The other part is in https://github.com/phpactor/phpactor/issues/1235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1554)
> [READY] Fix wrong offset when calculating parameter offsets in /signature_help

- .mergify.yml
> approved-reviews-by | list of string | The list of GitHub user or team login that approved the pull request. Team logins are prefixed with the @ character and must belong to the repository organization. This only matches reviewers with admin, write or maintain permission on the repository.
-- | -- | --
Previoulsy we were requiring only that reviewable was happy. Now we require that, but also 2x approving reviews (which are restricted to admin, write, maintain) users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1560)
> Require maintainer approval for merging

- .github/workflows/ci.yml
- .mergify.yml
Like I reported earlier, GHA doesn't seem to register test failures on linux and mac. I intentionally changed a dummy test to `assert False`. Let's see what's going on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1563)
> [READY] Make sure Linux/macOS CI can fail and run tests with --no-parallel to avoid flakes

- build.py
At some point this broke, and we ended up with:
```
nothing to commit, working tree clean
ben@BenMBP YouCompleteMe-Clean % ./install.py --quiet --ninja --all
Generating ycmd build configuration...
OK
Compiling ycmd target: ycm_core...
OK
Building regex module...
OK
Building watchdog module...
OK
Installing Omnisharp for C# support...OK
Building gopls for go completion...
OK
Setting up Tern for JavaScript completion...
OK
Installing rust-analyzer for Rust support...OK
Installing jdt.ls for Java support...OK
Setting up TSserver for TypeScript completion...
OK
Setting up Clangd completer...OK
ben@BenMBP YouCompleteMe-Clean % ./install.py --quiet --ninja --all
```
This fixes it:
```
ben@BenMBP ycmd % ./build.py --all --quiet --ninja
Generating ycmd build configuration...OK
Compiling ycmd …
```
> Fix quiet printing on a single line

- .ycm_extra_conf.py
- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/IdentifierDatabase.h
- cpp/ycm/Repository.h
Instead of checking for `__CYGWIN__`, I decided to `try_compile()` `absl/base/policy_checks.h` to know if Abseil can be used.
The preprocessor blocks seem to have a lot of repetition. Not sure where to draw the line between readability and smaller diffs.
The `-DYCM_ABSEIL_SUPPORTED` in the extra conf is debatable. If someone on cygwin decides to edit ycmd's code, there will be errors. If we remove the flag from the extra conf, *we* will see `YouCompleteMe::HashMap` as an alias of `std::unordered_map` instead of `absl::flat_hash_map`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1557)
> [READY] Do not use Abseil on unsupported environments

- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
Abseil produces ~40'000 lines of warnings when ycmd is compiled on Windows. This should silence them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1566)
> [READY] Silence MSVC warnings

- .github/workflows/ci.yml
Previously the site-packages path was hardcoded, with python version
like 3.6.13 or 3.9.4.
To make this more robust, we ask the interpreter what's the path to
site-packages - `sysconfig.get_path('purelib')`.
Note: I have no idea if the path substitution works, considering yaml is describing bash/batch which is doing command substitution which is calling python, redi... Let's see what CI has to say.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1571)
> [READY?] Make codecov setup more robust

- .github/workflows/ci.yml
- build.py
- cpp/ycm/tests/CMakeLists.txt
- run_tests.py
This pull request sets `-q` by default for pytest and `--gtest_brief` for core tests.
Also, I made the `--valgrind` flag respect `--quiet`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1570)
> [READY] Make CI tests quiet

- third_party/generic_server/client/package-lock.json
- third_party/generic_server/package.json
- third_party/generic_server/server/package-lock.json
- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Previously the "platform" didn't include the standard library, so we
always ended up using the standard library from the "toolchain". As of
12.5 the platform includes a copy of the standard library which leads to
2 incompatible ones being included. This leads to lots of errors.
Solution is to only use one or t'other, preferring the platform one.
Tested this with/without clangd on Xcode 12.0.5 and Xcode 12.5 - passes.
Tested iOS project with Xcode 12.0.5 and 12.5 - works with libclang, fails with clangd (but confirmed this is the case irrespective of these changes, so much be a clangd problem)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1569)
> [READY] Fix Standard library includes with Xcode 12.5

- build.py
Remove the boost options from build.py, and those that get passed to cmake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1573)
> Remove boost remnants.

- docs/index.html
- docs/openapi.yml
A few questions:
1. Do we want to document the subserver query, since we don't document it for `/healthy`? The comment says `/healthy` doesn't document `subserver` query because it's only intended for testing.
2. Can `/ready` ever return 500? I don't think so.
Thanks to @theli-ua for pointing out the bug in the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1576)
> [READY] Document /ready request

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/typescript/typescript_completer.py
Python's `threading` deprecated some identifiers in favour of snake_case
alternatives. One example is
`threading.Event.isSet()` -> `threading.event.is_set()`
Hopefully, this will make us ready for python 3.10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1592)
> [READY] Avoid deprecated threading function names

- cpp/ycm/ClangCompleter/Location.h
- cpp/ycm/ClangCompleter/UnsavedFile.h
dunno if this is desired or not but here it is-- default initializers are redundant for `std::string`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1542)
> Fix compiler warnings from -Wreadability-redundant-string-init

- .github/workflows/ci.yml
- .mergify.yml
- TESTS.md
- benchmark.py
- build.py
- run_tests.py
- ycmd/tests/cs/testdata/testy-multiple-solutions/solution-named-like-folder/not-testy/testy.csproj
- ycmd/tests/cs/testdata/testy-multiple-solutions/solution-named-like-folder/testy/testy.csproj
- ycmd/tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/extra-conf-abs/testy/testy.csproj
- ycmd/tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/extra-conf-bad/testy/testy.csproj
- ycmd/tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/extra-conf-rel/testy/testy.csproj
- ycmd/tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/testy/testy.csproj
- ycmd/tests/cs/testdata/testy/testy.csproj
- ycmd/tests/cs/testdata/неприличное слово/a project.csproj
Now that VS 2022 is released, ycmd should be buildable on Windows without requiring installing old versions of the build tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1608)
> Support MSVC 17 (Visual Studio 2022)

- third_party/tsserver/package.json
- ycmd/tests/javascriptreact/get_completions_test.py
- ycmd/tests/typescript/subcommands_test.py
Just a quick update. Noteworthy changes:
1. Completion items get detailed info in javascriptreact now.
2. The project-wide rename command in a `.ts` file didn't get applied to `.tsx` file. Possibly we need a better `tsconfig.json`, instead of just `{}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1612)
> [READY] Upgrade to typescript 4.5

- .github/workflows/ci.yml
- build.py
- cpp/ycm/CMakeLists.txt
Sorry for the 2-in-one:
1. Cache the dependency downlaods in CI to avoid Lombok and other crap failing to download all the time
2. Support for Apple arm64 natively
I tested this on my arm Mac and both libclang and clangd work out of the box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1613)
> Support Apple Silicon (and cache CI dependencies)

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/clangd/testdata/call_hierarchy.cc
- ycmd/tests/go/go_module/call_hierarchy.go
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/language_server/language_server_completer_test.py
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/typescript/subcommands_test.py
It works by returning a GoToResponse and it retrieves, not the whole call stack, but just the list off immediate callers.
Comments a very much needed, even if they are "WTF, who would want to use that implementation?!"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1607)
> [READY] Call hierarchy support for LSP and typescript

- ycmd/identifier_utils.py
Racket is a descendant of Scheme, and AFAIK hasn't changed the identifier rules any.
Without this change, either YCMD will use the default regex, or Vim will apply Scheme highlighting and `lispwords` values and the like rather than those set by the `vim-racket` plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1616)
> Use Scheme identifier regex for Racket

- cpp/CMakeLists.txt
We require Python 3.6+, but we're checking for 3.6 up to 3.10, which is
apparently interpreted as up to and including 3.10, but not 3.10.1.
Anyway, we have no "maximum" supported Python version, so we should just
check for a minimum of 3.6.
Fixes #1617
Incidentally, the 'version range' check we were doing is not actually
supported in our minimum cmake version (3.14). It was added in 3.19
according to the cmake docs, so this change also fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1618)
> [READY] Don't set a maximum Python version required

- cpp/ycm/CMakeLists.txt
- ycmd/tests/__init__.py
- ycmd/tests/clang/comment_strip_test.py
tested with `otool -l ycm_core.cpython-39-darwin.so|grep -A3 LC_RPATH`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1622)
> Fix rpath to libclang archive on mac

- .ycm_extra_conf.py
- README.md
- ycmd/completers/language_server/generic_lsp_completer.py
- ycmd/server_state.py
This allows, for example users to use python language server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1641)
> Allow generic/LSP completers to override built-in completers

- tox.ini
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
Minimal support for the workspace folders configuration, as some servers require this.
For now we simply return a single folder, as today.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1644)
> Workspace folders minimal

- cpp/ycm/CMakeLists.txt
Changed the hashes, they now match the archives they are hashed from.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1636)
> Swapped the FreeBSD 13 archive hashes

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1646)
> fix build.py for Solaris OS - add lib/64 to search paths (fix #1645)

- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- ycmd/tests/clang/diagnostics_test.py
Sometimes libclang returns invalid ranges causing ycm in trouble.
No log is recorded (both of ycmd and ycm) for this inconvenice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1633)
> Fix annoying popups when editing incomplete macros

- benchmark.py
- build.py
- run_tests.py
- Remove --msvc arg on other platforms than windows
- Default the value of msvc to the latest found
eg, trying it on on one of my windows VMs that has MSVC 2022 (=17)
```
--msvc {15,16,17}     Choose the Microsoft Visual Studio version (default: 17).
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1626)
> Try to infer the latest MSVC version on windows like CMake Does

- build.py
CMAKE_BUILD_TYPE should be Release but it seems a problem under windows that with ninja generator, where cmake has pre-defined CMAKE_BUILD_TYPE and it passes by the setting line in cpp\CMakeLists.txt. Specify it manually, so it compiles and links correctly with release runtime.
Verified "/O2" instead of "/Od" in cl.exe commandline. Tested on a Windows 10 22H2 machine and VS2019 installation.
TODO I didn't have time to test it with "MSYS Makefiles" or "MINGW Makefiles" generator on windows. We can add this fix if we need it as well.
Fixes #1678.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1679)
> Specify CMAKE_BUILD_TYPE manually for ninja generator

- .github/workflows/ci.yml
- cpp/ycm/benchmarks/CMakeLists.txt
Our records indicate that some of your organization’s workflow files are still referencing the macos-10.15 runner image. This image has been fully unsupported since 2022-12-01 and will be completely removed by 2023-03-31.
What you need to do
Workflows using the macos-10.15 YAML workflow label should be updated to macos-latest, macos-12, or macos-11. You can always get up-to-date information on our tools by reading about the [software](https://app.github.media/e/er?s=88570519&lid=3455&elqTrackId=20a1f0dfddfb4f279a143758449644bb&elq=80ef062d847e4addbbafffe8e5e487cb&elqaid=3113&elqat=1) in GitHub Actions runner images. Please contact [GitHub Support](https://app.github.media/e/er?s=88570519&lid=3338&elqTrackId=109f1ab4edb9447baf91e5e0d5dcb9c1&elq=80ef062d847e4addbbafffe8e5e487cb&elqaid=3113&e …
> Use macos 12 in CI

- build.py
The jdt-language-server package seems to got moved from snapshots to milestones.
Using the URL is no longer available, which causes the build.py script to throw "HTTP Error 404: Not Found".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1682)
> Fix URL of eclipse.jdt.ls

- ycmd/tests/go/diagnostics_test.py
Go1.20 changes diagnostics message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1686)
> Fix gopls test with Go1.20

- cpp/ycm/CMakeLists.txt
Should I add a comment in CMakeLists.txt for the suppression?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1705)
> Suppress -Wbidi-chars on newer GCC's

- .github/workflows/ci.yml
Disables setup-go caching.
Upgrades setup-java for Unix-like runs, which was simply missed previously.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1709)
> More CI fixes

- ycmd/completers/language_server/language_server_completer.py
Another one of those "be vscode plox" things.
Servers seem to expect things like
```json
{
"capabilities": {
"whateverProvider": {}
}
}
```
to mean that the server is really a provider of whatever. Earliest offender is the swift server being a code action provider.
Please take extra care wen reviewing this thing.
Unresolved things:
1. Are we correctly handling `textDocumentSync`?
2. Type hierarchy needs to get the same treatment once #1704 is accepted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1707)
> Handle empty object capabilities as truthy where applicable

- .ycm_extra_conf.py
- build.py
- ycmd/completers/cs/solutiondetection.py
- ycmd/completers/typescript/typescript_completer.py
- Update of jedi
- f-string flake8 fixes
- Our extra conf no longer uses distutils.
CI is still not ready for python 3.12. Stay tuned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1712)
> Python 3.12 compatibility fixes

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/subcommands_test.py
After dropping the functional stuff from #1713 , the only things left are two `ServerIsReady()` checks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1714)
> Minor clangd completer fixes

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/clangd/diagnostics_test.py
- ycmd/tests/go/diagnostics_test.py
- ycmd/tests/java/diagnostics_test.py
- ycmd/tests/rust/diagnostics_test.py
Like I mentioned in gitter, we are missing `kind` in the `/detailed_diagnostic` response.
I am being lazy, so letting CI tell me if any tests are broken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1720)
> [READY] Add diag kind to /detailed_diagnostic response

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/debug_info_test.py
Fixes the `g:ycm_roslyn_binary_path` only being used in prechecks, and the actual server always being started from the `ycmd/third_party` directory.
Also fixes the `:YcmDebugInfo` printing the directory containing default OmniSharp executable (and not the executable file itself); now prints full command with arguments used to start the server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1721)
> Fix g:ycm_roslyn_binary_path being ignored

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/test_utils.py
When the language_server_completer is first constructed, it's usually a FileReadyToParse callback. But at that time, we can't actually parse anything because we haven't done the initialization exchange with the server, so we queue this up for later.
The way this was implemenented was to register a "on file ready to parse" callback to update the server with the file contents at the time the completer was constructed. In practice, as the completer is usually constructed via a file ready to pase event, this actually happens immediately and we then shunt the request into "OnInitializeComplete" handlers, which are fired when the initialize exchange happens.
Why don't we just put something directly in OnInitializeComplete handlers? Well because in the constructor, we don't have the request_data …
> Only parse the initial file the first time it's opened

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/javascriptreact/get_completions_test.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/subcommands_test.py
Fixes #1675
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1716)
> Display tsserver tags from docstrings in GetDoc and extra_menu_info

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/cs/testdata/testy/Empty.cs
- ycmd/tests/cs/testdata/testy/testy.csproj
Implements `GoToDocumentOutline` in the `CsCompleter` to support `YCMFindSymbolInDocument` functionality for `cs` projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1723)
> CsCompleter: Implement GoToDocumentOutline.

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/cs/testdata/testy/SingleEntity.cs
- ycmd/tests/cs/testdata/testy/testy.csproj
All other semantic completers return a list only when more than one item is in the list. Otherwise return that one item.
WIP because I can't be bothered to set up C# on my machine. I will be using CI for that instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1724)
> [READY] Make C# completer consistent with other completers regarding GoToDocumentOutline

- ycmd/completers/cs/cs_completer.py
This does lose a bit of context, but not much. Methods still have their signatures visible and variables are... well... variables.
The idea is, if a client wants to later do filtering and sorting of symbols, we should not be doing that on the whole line, which might be left padded with tabs and have other punctuation. We already had a report that this does not work well. It almost works if a client `strip()`s the description before using it at all.
LSP completer instead uses `extra_data` to supply identifier name and kind, but omnisharp-roslyn does not provide us with a symbol kind and thus we can only put `ref[ 'Text' ]` in the description.
@teasp00n was the user who pointed out the problems with using the whole line for filtering.
- - - …
> [RFC] Do not use a full line as description for symbol search

- cpp/CMakeLists.txt
- cpp/ycm/benchmarks/CMakeLists.txt
- cpp/ycm/tests/CMakeLists.txt
This should be enough to fix ycm-core/YouCompleteMe#4212
@Jaywalker, would you mind double checking my choice of abseil commit?
@puremourning Abseil's cmake is warning about this:
https://github.com/abseil/abseil-cpp/blob/lts_2023_08_02/CMakeLists.txt#L73-L78
We should figure out how to set that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1725)
> Update abseil to the latest LTS.

- ycmd/tests/go/get_completions_test.py
Latest go version changes how diagnostics look, so we need to change the tests. Opted for matching with a regex, so the test can work with older versions of go as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1735)
> [READY] Fixing tests for go v1.22.0

- ycmd/completers/language_server/language_server_completer.py
Previously, ycmd would not update the LSP server with the current file state after RestartServer subcommand had been issued. This causes some stale diagnostics to linger.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1730)
> Update the server with current file state after a restart

- README.md
- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/clangd/debug_info_test.py
- ycmd/tests/go/__init__.py
- ycmd/tests/go/debug_info_test.py
- ycmd/tests/go/go_module/thing.go
- ycmd/tests/go/go_module_2/go.mod
- ycmd/tests/go/go_module_2/main.go
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/java/debug_info_test.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/java/testdata/simple_gradle_project/gradle/wrapper/gradle-wrapper.properties
- ycmd/tests/language_server/generic_completer_test.py
- ycmd/tests/rust/debug_info_test.py
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/shutdown_test.py
Perhaps it's finally time to add this capability...
There are a couple missing pieces:
1. So far, this does not take into account the extra confs.
2. Clangd completer does not have GetProjectRootFiles() implemented, but also clangd does not want to listen to this notification. I guess it knows better than us?
3. Java completer also does not have GetProjectRootFiles() implemented, but actually wants this notification.
4. Do we need `_project_directory` *and* `_server_workspace_dirs`?
5. Tests... after we figure out the answers to the above!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1731)
> [READY] Add support for didChangeWorkspaceFolders

- ycmd/completers/cs/cs_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/clangd/diagnostics_test.py
- ycmd/tests/clangd/testdata/diag_ranges/compile_flags.txt
- ycmd/tests/clangd/testdata/diag_ranges/detailed_diagnostic.cc
- ycmd/tests/language_server/language_server_completer_test.py
Users are more likely to be interested in errors than warnings in /detailed_diagnostic responses. That means we need to sort the diagnostics before finding the one nearest to the cursor.
For LSP completers, that's easy as the severity is numerical. For Omnisharp-roslyn and TSServer, the severity is a word and we can't just say `sort( key = severity )`.
Since LSP severity was convenient for comparison, I have opted for sorting C# and TS diags by the equivalent LSP severity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1728)
> Sort diagnostics according to severity for detailed diag responses

- .gitmodules
- requirements.txt
- run_tests.py
- ycmd/__main__.py
- ycmd/handlers.py
- ycmd/hmac_plugin.py
- ycmd/tests/misc_handlers_test.py
- ycmd/tests/test_utils.py
- ycmd/web_plumbing.py
Turns out ycmd needs a tiny part of the whole framework specification from PEP 3333.
Note that this does not fully conform to the specification, but it mostly does.
Currently we are only handling POST and GET requests.
Support for middleware is limited. Inspired by Bottle plugins API, but only `plugin.__call__` and `app.install` are implemented.
Error handling is also limited. Application needs to replace the default error handler that *will* handle all errors.
However, this just about fits ycmd's needs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1736)
> [READY] Drop bottle in favour of a tiny hand-rolled "framework"

- cpp/CMakeLists.txt
Update of abseil allows ycmd to be compiled on FreeBSD.
Reported and tested by @nerozero
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1747)
> [READY] Update Abseil to latest LTS

- .github/workflows/ci.yml
- .mergify.yml
- run_tests.py
- test_requirements.txt
- valgrind.suppressions
- ycmd/tests/bindings/cpp_bindings_raises_exception_test.py
I'm not sure if we want to merge this immediately, or wait for october, so that we can actually drop python 3.8.
Quick summary:
- Switch to ubuntu 24.04
- Switch to macos 14
- Switch to python 3.9
- Install mono-complete
- Redo valgrind
- Update actions
- Use python 3.13 in valgrind run
- Workaround for cgi module being removed
- Fix bindings test in newer python
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1746)
> [READY]General CI updates

- build.py
According to https://github.com/microsoft/vswhere/issues/22, `vswhere.exe` only finds full Visual Studio IDE instances. To find a naked Build Tools instance, one needs to explicitly add `-products 'Microsoft.VisualStudio.Product.BuildTools'` to the call, but that won't find IDE instances in turn.
The PR adds the second form as a fallback to support users who only have Build Tools installed without the full IDE.
```shell
> ./install.py --skip-build --verbose
Calling C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -latest -property installationVersion
vswhere returned nothing usable: ""
Retrying vswhere for Build Tools
Calling C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -latest -property installationVersion
-products …
```
> Fix vswhere for Build Tools

- build.py
- ycmd/tests/go/subcommands_test.py
As mentioned in #1756, this time we expect the tests to fail until https://github.com/golang/go/issues/68904 gets fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1758)
> [READY] CI Gopls fix - with ExpectedFailure

- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/rust/subcommands_test.py
So...
We advertise that we can handle CodeActions that are either missing an edit or a command (or both).
The server chooses whether it supports either of the two. If it does, it advertises itself as a "code action resolve provider".
For servers that are code action resolve providers:
- If either edit or command is missing, we need to try resolving the code action via codeAction/resolve.
- Unless we actually got a LSP Command, in which case codeAction/resove is skipped.
- After resolving it that way we have a CodeAction in one of these forms:
- A LSP Command
- A LSP CodeAction with only an edit.
- A LSP CodeAction with only a command.
- A LSP CodeAction with both an edit and a command.
- Edits are WorkspaceEdits and can easily be converted into ycmd FixIts.
- Commands are to be executed, …
> [READY] Add support codeAction/resolve requests

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
I'm not too happy about this.
Omnisharp LSP assumes clients support this.
We *could*, but it comes at the cost of manually flattening the hierarchy. That's what this pull request does.
Alternatives include:
- Implementing this, but not advetising the capability. That way, servers that assume client support for it work, but those that don't won't have a performance impact.
- Leave this mess out of the `LanguageServerCompleter` class and only add this hack into the LSP Omnisharp completer. This was done in #1752
EDIT: Switched to the first alternative, as discussed in gitter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1757)
> [READY] Add support for DocumentSymbol in document outline requests

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/generic_completer_test.py
- ycmd/tests/rust/subcommands_test.py
Some languages name the project description file after the root directory.
I.e. `foo/foo.csproj` and `foo/foo.sln` in case of C#.
This accommodates those language servers.
This is the last part needed for users to be able to use Omnisharp-Roslyn through `GenericLanguageServer`.
We should still get #1752 working, if for no other reason, then not to drag ancient omnisharp version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1759)
> [READY] LSP: Allow globs in GetProjectRootFiles

- build.py
- test_requirements.txt
Two things:
1. Make regex optional with `--no-regex`/`--regex`
2. Move `BuildRegexModule()` to the end.
Both done as a way to allow ycmd to work even if regex does not compile on some system.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1764)
> Make building regex module optional

- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/rust/subcommands_test.py
A TestCase.subTest() context manager will swallow exceptions, so applying @WithRetry on the entire test does not work. Instead, it needs to be applied on whatever the subTest is doing.
I have not run the tests manually. I'm hoping CI will be merciful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1773)
> [READY] Correct where WithRetry decorator is applied
