- CONTRIBUTING.md
- TESTS.md
Update developer documentation for test suite
Add a readme (TESTS.md) with instructions on running the test suite.
Reference the readme from CONTRIBUTING.md.
> Update developer documentation for test suite

- cpp/ycm/CMakeLists.txt
Hi guys,
This pull request addresses https://github.com/Valloric/YouCompleteMe/issues/1112. Not sure
if this already fixed, but I have met this recently
> Fix install failure on FreeBSD

- ycmd/handlers.py
I was looking in the code and say that TODO.
> rename variables from UPPER_CASE to _lower_case

- .gitmodules
- build.py
- run_tests.sh
- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/hook.py
- ycmd/completers/go/tests/gocode_completer_test.py
- ycmd/completers/go/tests/testdata/gocode_output_offset_121.json
- ycmd/completers/go/tests/testdata/gocode_output_offset_215.json
- ycmd/completers/go/tests/testdata/gocode_output_offset_292.json
- ycmd/completers/go/tests/testdata/test.go
- ycmd/default_settings.json
- ycmd/tests/get_completions_test.py
- ycmd/tests/testdata/test.go
Add Completer for semantic Golang completion using gocode. Fixes #52. 
Sorry in advance for my style mistakes, I have not written python in a long time!
A couple questions:
* should gocode be installed automatically by build.py or can it just be found on the path?
* I don't *think* I need to override ShouldUseNowInner - or am I missing something?
Thanks for YCM, it's awesome!
> Add Gocode support using Completer API

- ycmd/__main__.py
- ycmd/completers/all/identifier_completer.py
- ycmd/default_settings.json
> Allow to specify max number of identifier canditates in options

- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/tests/gocode_completer_test.py
- ycmd/completers/go/tests/testdata/dontpanic.go
- ycmd/completers/go/tests/testdata/gocode_dontpanic_output_offset_10.json
Fixes Valloric/YouCompleteMe/issues/1465
> Handle case where gocode panics gracefully

- ycmd/tests/get_completions_test.py
Someone forgot a print. It happens.
CLA signed.
> Remove print statement

- .travis.yml
- ycmd/completers/typescript/hook.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/testdata/test.ts
- ycmd/tests/testdata/tsconfig.json
TypeScript completion support.
> Add TSServer completer

- ycmd/completers/completer_utils.py
> Add semantic trigger for typescript

- ycmd/completers/typescript/typescript_completer.py
- ycmd/utils.py
cc @icholy 
On Windows, TSServer executable is a `.cmd` file but `find_executable` works only for `.exe` files so we need our own implementation of the `find_executable` function. This new function tries to find executable with `.exe`, `.bat` and `.cmd` extensions on Windows. Its behavior should be identical to `find_executable` on others platforms.
This fix is not enough. We also need to set the [`universal_newlines` option](https://docs.python.org/2/library/subprocess.html#subprocess.Popen) to `True` (certainly because TSServer only accept `\n` for newlines) and to redirect `stderr` to `stdout` (not sure why but this is caused by the `creationflags = CREATE_NO_WINDOW` option in `utils.SafePopen`) when starting TSServer.
I also added a log when the binary is not found and formatted a 80+ …
> Fix TypeScript completer on Windows

- ycmd/tests/get_completions_test.py
I saw a TODO and I did it. I signed the CLA.
> Use CompletionEntryMatcher instead of building responses data

- ycmd/completers/typescript/typescript_completer.py
* Fix bug with notification handling
* More detailed completion
* Prevent concurrent requests to tsserver
> Improve TypeScript completer

- ycmd/utils.py
See PR Valloric/YouCompleteMe#1563.
CLA signed.
> Set stdin to PIPE on Windows only when necessary

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/testy/FixItTestCase.cs
- ycmd/tests/testdata/testy/testy.csproj
Implement https://github.com/Valloric/ycmd/pull/167 for C#.
> Implement FixIt for C#

- README.md
TypeScript 1.5 was finally released. I've been using this completer on a daily basis without any issues.
> Note TypeScript support in README

- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/tests/flags_test.py
Fix issue Valloric/YouCompleteMe#1637.
> Add -imacros to the list of include flags

- CONTRIBUTING.md
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/gocode_completer.py
See PR Valloric/YouCompleteMe#1642.
> [Windows support] Update install script references

- README.md
Because badges have rights too (and it looks better).
> Use SVG Travis badge instead of PNG

- ycmd/completers/general/filename_completer.py
With this PR, paths can be completed using the `\` separator on Windows.
I also simplified and refactored the regular expression used to match a path.
Fix 5 tests (5 failures) on Windows (listed in the commit message).
> [Windows support] Add backslash trigger to complete path on Windows

- README.md
- appveyor.yml
@Valloric You can create an AppVeyor account or we can use mine. I will update the badge accordingly.
> [Windows support] Add AppVeyor configuration

- build.py
- cpp/ycm/Candidate.h
- cpp/ycm/CandidateRepository.h
- cpp/ycm/ClangCompleter/ClangCompleter.h
- cpp/ycm/ClangCompleter/TranslationUnit.h
- cpp/ycm/DLLDefines.h
- cpp/ycm/IdentifierCompleter.h
- cpp/ycm/IdentifierUtils.h
- cpp/ycm/LetterNodeListMap.h
- cpp/ycm/Utils.h
- cpp/ycm/tests/CMakeLists.txt
Needed changes to successfully build ycm_core_tests and run it on Windows.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/227)
> [Windows support] Fix ycm_core_tests build

- ycmd/completers/completer_utils.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/general/filename_completer.py
- ycmd/tests/subcommands_test.py
- ycmd/tests/testdata/test-include/.ycm_extra_conf.py
- ycmd/tests/testdata/test-include/main.cpp
Added GoToInclude sub-command for c family languages.
Changed logic to use paths specified with -iquote flag only for quoted includes. (https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html)
Added unit tests for new functionality.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/244)
> Added GoTo include file functionality

- README.md
Closes #257
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/258)
> Fix ycmd-users link

- ycmd/completers/completer_utils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/260)
> Add semantic trigger for rust

- ycmd/completers/typescript/typescript_completer.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/265)
> Enable TSServer log file

- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/tests/flags_test.py
This superseeds #262 and follows received suggestions of using regex and adding specific tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/266)
> Fix language detection

- ycmd/completers/cs/cs_completer.py
Following comment in PR #288.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/290)
> Add a comment about localhost in the C♯ completer

- ci/appveyor/appveyor_install.bat
This PR does two things:
- manually exit the batch script if an error is encountered after important commands;
- update `get-pip.py` script URL. See PR Valloric/YouCompleteMe#1929.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/316)
> [READY] Improve AppVeyor configuration

- ycmd/completers/cs/cs_completer.py
This PR adds locks to C♯ completer. One in `GetSolutionCompleter` to prevent multiple creation of the same solution completer and another in `StartServer` to prevent multiple starts of the OmniSharp server for the same solution.
Both locks are needed because if one is used for `GetSolutionCompleter` and none for `StartServer`, `StartServer` may be called by two threads inside the same `CsharpSolutionCompleter` object. Conversely (none for `GetSolutionCompleter` and one for `StartServer`), two distincts `CsharpSolutionCompleter` objects using the same solution may be created by two threads and each object will start its own server.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/315)
> [READY] Prevent (for good) multiple starts of OmniSharp server for same solution

- ycmd/completers/completer_utils.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/322)
> Add groovy semantic trigger

- README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/330)
> Update emacs-ycmd part in README

- README.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/331)
> Sublime package now has support for all YCM languages

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
supports kebab case
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/320)
> improve perl6 identifier completions

- CONTRIBUTING.md
- DEV_SETUP.md
- TESTS.md
- Vagrantfile
- vagrant_bootstrap.sh
Should make our lives easier, especially since we'll want to easily switch between Python 2 and 3 for local dev and test running.
Fixes #273.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/334)
> [READY] Adding vagrant setup for ycmd development

- .gitmodules
- README.md
- build.py
- ycmd/completers/go/gocode_completer.py
- ycmd/completers/go/tests/gocode_completer_test.py
- ycmd/default_settings.json
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/go/testdata/goto.go
- ycmd/tests/go/testdata/win.go
fixes #333
Unfinished; I need to add the submodule (this currently works with a `godef_binary_path`), however for that rogpeppe/godef#24 must merge first (if not I can point it to my fork).
I also need to add a test.
Still, ready for incremental review; cc @Valloric
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/340)
> Support GoTo for Go using `godef`

- examples/example_client.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/348)
> [READY] Do not remove interpreter line in example_client

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/subcommands_test.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/350)
> TypeScript: Add GoToOccurences and GoToReferrences subcommands

- .gitignore
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/356)
> [READY] Ignore vagrant directory

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
Fix issue Valloric/YouCompleteMe#1974.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/368)
> [READY] Add -include-pch flag to the list of include flags

- run_tests.py
- ycmd/completers/all/identifier_completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/test_utils.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
These tests cover lines that aren't being covered by other tests.
Also includes minor refactoring & bug fixes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/374)
> [READY] More tests for functions in utils.py

- test_requirements.txt
- ycmd/tests/bottle_utils_test.py
- ycmd/tests/hmac_utils_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/utils_test.py
This way, we have the same list of tests on all configurations.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/382)
> [READY] Use decorator to skip conditional tests

- ycmd/user_options_store.py
Should fix #395.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/397)
> [READY] Use ReadFile in DefaultOptions

- build.py
Do not attempt to build on Windows if the `ycmd` server is up (more precisely, if `ycm_core` is in use) because the compilation will fail during linking with the following error:
```
LINK : fatal error LNK1104: cannot open file '<path_to_ycmd_folder>\ycm_core.pyd'
```
We check this by trying to open the `ycm_core` file in append mode.
Discussed in issue Valloric/YouCompleteMe#1891 and PR Valloric/YouCompleteMe#1922.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/399)
> [READY] Avoid LNK 1104 error when compiling on Windows

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/testdata/test.ts
I've added GoTo tests. In order to get the `Could not find definition` error I had to change the logic.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/403)
> [READY] Goto typescript tests

- ycmd/completers/python/jedi_completer.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/402)
> [READY] b64encode the JediHTTP HMAC secret only when passing it

- ycmd/completers/rust/rust_completer.py
cc @puremourning
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/408)
> [READY] Rust completer debug info uses unicode host

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/testdata/test.ts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/414)
> Remove extra whitespace from typescript signatures

- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/420)
> Exchange call to open with OpenForStdHandle in completers

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/441)
> Fix small broken link in README

- ycmd/completers/completer.py
- ycmd/tests/get_completions_test.py
Add tests for cache completion and clean up CompletionsCache class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/442)
> [READY] Add tests for cache completion

- ycmd/tests/hmac_utils_test.py
The file should now have 100% test coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/449)
> More tests for hmac_utils

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/subcommands_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/458)
> TypeScript: Add GoToType command

- .travis.yml
- README.md
- appveyor.yml
- ci/appveyor/appveyor_install.bat
- ci/travis/travis_install.sh
- codecov.yml
- test_requirements.txt
- ycmd/completers/completer.py
- ycmd/tests/test_utils.py
- ycmd/tests/utils_test.py
For now this will enable only coverage for the python layer for every build that we make. I will add coverage for the C++ layer later on (I still didn't try it). Just for reference coverage went up to 86.60%.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/524)
> [READY] Switch to Codecov for coverage

- DEV_SETUP.md
For some reason, the characters in the examples were not the correct ascii chars, so you can't copy/paste them. Replaced them with the correct incantations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/529)
> [READY] Fix strange characters in DEV_SETUP.md

- cpp/ycm/IdentifierUtils.cpp
Fixes Valloric/YouCompleteMe#2228.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/539)
> Add Elixir support for tag file reading.

- build.py
- third_party/tern_runtime/package.json
Closes #543.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/544)
> [READY] Bump Tern version to 0.19.0

- build.py
We fairly frequently get issues raised due to build errors and we often have to ask for the full log, invocation, etc. I think this might be exacerbated by the way failures are presented like a python backtrace.
So I thought to catch the failure and print some weasel words about reading CONTRIBUTING.md and that it almost certainly isn't a bug.
The output looks like this:
```
FAILED: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DBOOST_THREAD_DONT_USE_CHRONO -DUSE_CLANG_COMPLETER -DYCMD_CORE_VERSION=24 -Dycm_core_EXPORTS -I/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm -I/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/ClangCompleter -isystem /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/BoostParts …
```
> [READY] Catch build errors and point to CONTRIBUTING.md

- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/get_completions_test.py
For each iteration in the `_ReaderLoop` method (run in a separate thread), we try to read lines from the TSServer stdout. This is working fine while the TSServer is running because `readline` wait for any output from the process. However, when the process is down, `readline` returns an empty string, which leads to an infinite loop with no interruption in `_ReaderLoop` where we catch and log the `RuntimeError` exception from `_ReadMessage`. This results in high cpu usage (full usage of one core) and a crazy disk space usage from the stderr logfile.
We prevent this by using an [event](https://docs.python.org/2/library/threading.html#event-objects) that is true when the server is running, false otherwise. We wait for this event to be true at each iteration in the `_ReaderLoop` method. If we …
> [READY] Fix infinite loop leading to high cpu and disk space usage in TypeScript completer

- ycmd/completers/typescript/hook.py
- ycmd/completers/typescript/typescript_completer.py
This way is more consistent with other completers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/557)
> [READY] Don't initialize the TypeScript completer if TSServer isn't found

- ycmd/handlers.py
- ycmd/tests/misc_handlers_test.py
See discussion [here](https://github.com/Valloric/YouCompleteMe/issues/624).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/560)
> [READY] Increase MEMFILE_MAX to 10MB

- ycmd/tests/client_test.py
- ycmd/tests/shutdown_test.py
I was feeling guilty for leaving out the C♯ completer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/566)
> [READY] Add C# completer to shutdown tests

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/598)
> Add VSCode youcompleteme

- ycmd/server_utils.py
- ycmd/tests/server_utils_test.py
See issue https://github.com/Valloric/YouCompleteMe/issues/2387 and the commit message.
Fixes https://github.com/Valloric/YouCompleteMe/issues/2387.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/625)
> [READY] Ignore virtualenv library path when searching the standard library path in sys.path 

- build.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/python/jedi_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/client_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
Fixes Valloric/YouCompleteMe#2395.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/629)
> [READY] Create temporary files in a secure manner

- build.py
Inspired by PR https://github.com/Valloric/YouCompleteMe/pull/2351.
When a command fails in the `build.py` script, a `CalledProcessError` exception is raised and the script exits with a Python traceback like this one:
```sh
File "*/third_party/ycmd/build.py", line 371, in BuildYcmdLib
subprocess.check_call( build_command )
File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_core', '--', '-j', '1']' returned non-zero exit status 2
```
This output is not helpful to understand why the build failed.
With this PR, we now catch these exceptions and exit the script with the status code returned by the failed command or with an appropriate …
> [READY] Catch CalledProcessError exceptions in build script

- ycmd/completers/all/identifier_completer.py
- ycmd/request_wrap.py
I've noticed that the same snippet was found in more than one place so I think it deserves a name even though I'm not certain on the name itself but a more suitable didn't came to mind. I think next I'm going to tackle the `TODO` in `request_wrap.py` 👍
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/631)
> [READY] Add 'first_filetype' to RequestWrap

- third_party/tern_runtime/package.json
Closes #638.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/639)
> Bump Tern to version 0.20

- ycmd/completers/all/identifier_completer.py
- ycmd/tests/get_completions_test.py
- ycmd/tests/identifier_completer_test.py
I continued to look at the coverage for this file and I added more tests for it. I've also make private all the methods used only in this class that are not part of the Completer interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/640)
> [READY] Additional test for the identifier completer

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
Fixes https://github.com/Valloric/YouCompleteMe/issues/2438.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/643)
> [READY] Add regex for JavaScript and TypeScript identifiers

- appveyor.yml
This is the follow up of https://github.com/Valloric/ycmd/pull/686#issuecomment-271075945.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/687)
> Update Python version in CI environments to 3.6

- cpp/ycm/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/698)
> Fetch correct clang package for AArch64.

- .travis.yml
- ci/appveyor/appveyor_install.bat
- ci/travis/travis_install.sh
- ycmd/handlers.py
- ycmd/tests/rust/__init__.py
- ycmd/tests/rust/get_completions_test.py
- ycmd/tests/test_utils.py
- ycmd/user_options_store.py
Fixes `GetCompletions_NoCompletionsFound` test and updates Travis and AppVeyor configurations by using `rustup` to install `rustc` and `cargo`.
Closes #676.
Closes #689.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/699)
> [READY] Update racerd to 0.3.3

- README.md
Please add gycm Geany plugin and my branch of GNU nano.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/704)
> Add Geany and GNU nano clients to readme

- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/720)
> Add MSYS2 support

- cpp/ycm/IdentifierCompleter.h
- cpp/ycm/tests/IdentifierCompleter_test.cpp
- cpp/ycm/tests/IdentifierUtils_test.cpp
- cpp/ycm/tests/testdata/invalid_tag_file_format.tags
The idea of these tests is to get 100% test coverage for `IdentifierUtils.cpp`, `IdentifierCompleter.cpp` and every file having any function called from these two files (for example `IdentifierDatabase.cpp`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/730)
> [WIP] Tests for IdentifierCompleter, IdentifierDatabase and IdentifierUtils

- README.md
No one saw that we forgot to update it in 2016.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/734)
> [READY] Update copyright years

- ycmd/tests/python/get_completions_test.py
This new version of JediHTTP includes [Jedi 0.10.2](https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst#0102-2017-04-05).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/735)
> [READY] Update JediHTTP

- cpp/ycm/CMakeLists.txt
... and it was bothering me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/738)
> Explicitly was misspelled

- build.py
fix #752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/753)
> fix build error for godef

- build.py
On some distributions, the Python dynamic library can be found in the `lib64` folder of the base Python installation instead of `lib`. These distributions may not patch the `get_python_lib` function to return the right folder and thus our build script is unable to find the Python library. To fix that, we reproduce what the `get_python_lib` function does except that we look for both directories: `lib` and `lib64`.
Closes #747.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/754)
> [READY] Search the Python library in lib64 folder in addition to lib

- cpp/ycm/CMakeLists.txt
Haiku got no rt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/802)
> Haiku build fix

- ycmd/completers/cpp/flags.py
- ycmd/tests/clang/flags_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/877)
> Add include flag '-idirafter' and tests.

- api/README.md
- api/swagger.yaml
So about 2 years ago, I wrote this documentation for the API. It's been up on http://puremourning.github.io/ycmd-1 for that time and I know at least a few people have found it useful. I have used it myself on occasion, though the code is still strictly the only true documentation :)
As I happened to just be updating it for the `working_dir` addition, I realised that the best way to keep it up to date in the future would be to get it in to the main repo.
So here it is, largely unchanged since 2 years ago, and therefore missing some recent changes, but hopefully some docs are better than no docs and we can update it incrementally.
It uses:
* swagger v2.0, which was current when I wrote it. There's now a swagger v4.0 or something, which seems completely different. the useful parts are: …
> [READY] Add swagger API documentation

- cpp/ycm/Candidate.cpp
- cpp/ycm/CandidateRepository.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/LetterNodeListMap.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/tests/ClangCompleter/TranslationUnit_test.cpp
[That's what our God recommends](http://www.stroustrup.com/bs_faq2.html#null).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/900)
> [READY] Replace NULL with nullptr

- README.md
The CircleCI badge is not pointing to the right branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/902)
> [READY] Fix CircleCI badge

- README.md
Alternate client for Sublime Text 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/903)
> Add Sublime Text 3 client, sublime-ycmd.

- cpp/ycm/Candidate.cpp
- cpp/ycm/CandidateRepository.cpp
- cpp/ycm/ClangCompleter/ClangCompleter.cpp
- cpp/ycm/ClangCompleter/ClangHelpers.cpp
- cpp/ycm/ClangCompleter/ClangUtils.cpp
- cpp/ycm/ClangCompleter/CompilationDatabase.cpp
- cpp/ycm/ClangCompleter/CompletionData.cpp
- cpp/ycm/ClangCompleter/TranslationUnit.cpp
- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/LetterNode.cpp
- cpp/ycm/LetterNodeListMap.cpp
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/Result.cpp
- cpp/ycm/Utils.h
- cpp/ycm/benchmarks/IdentifierCompleter_bench.cpp
- cpp/ycm/benchmarks/PythonSupport_bench.cpp
- cpp/ycm/tests/TestUtils.cpp
This makes sure there are no more
```c++
if ( condition )
statement;
```
Instead the style should now be:
```c++
if ( condition ) {
statement1;
} else if (condition ) {
statement2;
} else {
statement3;
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/909)
> [READY] Fix one-liner style

- cpp/ycm/tests/IdentifierCompleter_test.cpp
- cpp/ycm/tests/TestUtils.cpp
- cpp/ycm/tests/TestUtils.h
Replace `StringVector` function with initializer lists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/913)
> [READY] Use initializer lists for vectors in tests

- ycmd/tests/java/diagnostics_test.py
Couldn't endure such typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/917)
> [READY] Fix typos in Java tests

- ycmd/tests/java/subcommands_test.py
We don't need to isolate these tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/962)
> [READY] Do not isolate Java subcommand tests

- .circleci/install_dependencies.sh
- .travis.yml
- build.py
The build system [Ninja](https://ninja-build.org/) is supposed to be faster for incremental builds but this project is too small to notice a difference (a few seconds at best). Also, this is the second time a user has an issue with it because the `ninja` executable on the PATH is not the build system but another software. See https://github.com/Valloric/YouCompleteMe/issues/2941#issuecomment-372259295 (the first time was reported on Gitter). For these reasons, I am proposing to completely remove support for this build system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/955)
> [READY] Disable Ninja auto-detection

- ycmd/identifier_utils.py
- ycmd/tests/identifier_utils_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/964)
>  scheme identifier 

- ycmd/tests/bindings/__init__.py
- ycmd/tests/bindings/cpp_bindings_general_test.py
- ycmd/tests/bindings/cpp_bindings_raises_exception_test.py
- ycmd/tests/bindings/cpp_bindings_vectors_test.py
- ycmd/tests/bindings/testdata/foo.c
These tests test the behaviour of the classes, functions etc. exposed to the python layer from ycm_core.so. The purpose is of testing this is that pull requests such as #925 don't surprise us with bug that are difficult to debug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/942)
> [READY] C++ <-> Python bindings tests

- .circleci/config.yml
- .circleci/install_dependencies.sh
- ci/travis/travis_install.sh
See PR https://github.com/Valloric/YouCompleteMe/pull/2986.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1001)
> [READY] Fix Python 2 builds on Travis and CircleCI

- cpp/ycm/IdentifierCompleter.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1019)
> [READY] Fix assignment operator signature in IdentifierCompleter class

- README.md
- appveyor.yml
- cpp/ycm/CandidateRepository.cpp
- cpp/ycm/CandidateRepository.h
- cpp/ycm/CharacterRepository.cpp
- cpp/ycm/CharacterRepository.h
- cpp/ycm/CodePoint.h
- cpp/ycm/CodePointRepository.cpp
- cpp/ycm/CodePointRepository.h
Add the list of supported compilers to the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1041)
> [READY] Remove all traces of MSVC 12

- cpp/CMakeLists.txt
Detect python 3.7 installation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1072)
> Detect python 3.7 installation

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1071)
> In case of error, show which directory doesn't exist

- benchmark.py
- build.py
- run_tests.py
- update_boost.py
- update_clang.py
Bundled argparse was removed in PR https://github.com/Valloric/ycmd/pull/904.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1089)
> [READY] Do not add third-party argparse path in scripts

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/debug_info_test.py
This is particularly useful when writing an extra conf that modify Python's `sys.path`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1100)
> [READY] Add Python path to debugging information

- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/cpp/include_cache.py
- ycmd/completers/general/filename_completer.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clang/get_completions_test.py
- ycmd/tests/clang/subcommands_test.py
- ycmd/tests/clang/testdata/test-include/.ycm_extra_conf.py
- ycmd/tests/clang/testdata/test-include/main.cpp
- ycmd/tests/utils_test.py
- ycmd/utils.py
On macOS, the compiler searches header paths of the form `A/B/.../Z` as `A.framework/Headers/B/.../Z` in the `/System/Library/Frameworks` and `/Library/Frameworks` directories, e.g. `CoreServices/CoreServices.h` is found as `/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h`. More generally, the compiler does that for each path specified through the `-F` or `-iframework` flags. This PR adds support for completing those paths and jumping to them.
Demo:
Fixes https://github.com/Valloric/YouCompleteMe/issues/2647.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1103)
> [READY] Support framework headers completion and code navigation

- update_unicode.py
Since @micbou didn't like the slow execution of the script, as @puremourning suggested, this now uses `StringIO` in the unicode `table`.
Brings down the execution time from 2:55 to 0:19.5 (on my laptop).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1144)
> [READY] Optimize update_unicode.py

- ycmd/tests/clangd/get_completions_test.py
This messes up the tests output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1146)
> [READY] Do not print to stderr in Clangd tests

- .gitignore
This prevents annoying untracked files in git status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1150)
> [READY] Ignore the local clangd installation and cache

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/subcommands_test.py
- ycmd/tests/python/testdata/GetType.py
Closes https://github.com/Valloric/YouCompleteMe/issues/3189.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1151)
> [READY] Add GetType command to Python completer

- ycmd/completers/completer.py
- ycmd/completers/python/python_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/javascript/get_completions_test.py
- ycmd/tests/typescript/diagnostics_test.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/testdata/test.ts
Apply the logic introduced by PR #1153 to the TypeScript completer. This tremendously speeds up completion at global scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1155)
> [READY] Detail candidates after filtering in TypeScript completer

- ycmd/completers/language_server/language_server_completer.py
Per a comment on #1161, which I did but totally forgot to push!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1165)
> [READY] Rename _ResolveCompletionItems to _CandidatesFromCompletionItems

- ycmd/__main__.py
- ycmd/completers/all/identifier_completer.py
- ycmd/completers/completer_utils.py
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/cs/solutiondetection.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/python/python_completer.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/extra_conf_store.py
- ycmd/handlers.py
- ycmd/hmac_plugin.py
- ycmd/request_wrap.py
- ycmd/server_state.py
- ycmd/server_utils.py
- ycmd/tests/extra_conf_store_test.py
- ycmd/tests/server_utils_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
- ycmd/watchdog_plugin.py
Instead of redefining `_logger` in each module, define it once in `ycmd/utils.py` and import it from there. Also, don't use `format()` when logging a message because if the formatting fails then the code is interrupted. Let the `logging` module handle the formatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1158)
> [READY] Refactor logging

- ycmd/tests/java/diagnostics_test.py
Throwing an exception in another thread doesn't cause the test to fail, so instead we update some variable.
We use a dict because they are mutable (`aborted = True` doesn't work because of the python scoping rules) and we check the result of that after joining the thread.
We also increase the number of tries because we know we have issues with the current number.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1166)
> [READY] Fix java poll thread abort test by ensuring that the abort actually happens

- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/language_server/language_server_connection_test.py
Some LSP features allow the language server to request that the language client does things, like [apply edits](https://microsoft.github.io/language-server-protocol/specification#workspace_applyEdit) and such.
We don't currently support these requests, so we should reject them.
Perhaps one day we will support them, but right now the requests just never get a response which makes us a bad LSP citizen.
This is the next patch in the now infamous "yaml" branch. RFC because no tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1203)
> [READY] Reject any server to client requests

- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/java/java_completer.py
- ycmd/tests/clangd/server_management_test.py
- ycmd/tests/clangd/subcommands_test.py
- ycmd/tests/java/server_management_test.py
- ycmd/tests/test_utils.py
Rename the `shutdown_test.py` file to `server_managment_test.py` and add a test for the `RestartServer` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1201)
> [READY] Add RestartServer command to Clangd completer

- cpp/ycm/Candidate.cpp
- cpp/ycm/Candidate.h
- cpp/ycm/CandidateRepository.cpp
- cpp/ycm/CandidateRepository.h
- cpp/ycm/Character.h
- cpp/ycm/CodePoint.cpp
- cpp/ycm/CodePoint.h
- cpp/ycm/IdentifierCompleter.cpp
- cpp/ycm/IdentifierCompleter.h
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/IdentifierDatabase.h
- cpp/ycm/IdentifierUtils.cpp
- cpp/ycm/PythonSupport.cpp
- cpp/ycm/PythonSupport.h
- cpp/ycm/Word.cpp
- cpp/ycm/Word.h
- cpp/ycm/benchmarks/IdentifierCompleter_bench.cpp
- cpp/ycm/tests/CandidateRepository_test.cpp
- cpp/ycm/tests/IdentifierCompleter_test.cpp
- cpp/ycm/tests/Word_test.cpp
The idea is that everything we get from python and plan to store, instead of passing around by `const T&`, we pass by `T&&` and finally `std::move` into the object that will own the resource.
The performance increase is about 5%
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1235)
> [READY] Move semantics

- .mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1242)
> [READY] Set up Mergify configuration

- ycmd/tests/go/debug_info_test.py
- ycmd/tests/go/diagnostics_test.py
- ycmd/tests/go/subcommands_test.py
Adds two thing.
- Diagnostics test which I somehow forgot to commit.
- A test to address the concern from #1257. Needs to be isolated so we are sure it starts in a different directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1258)
> [READY] Go tests for diagnostics and go.mod detection

- .mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1271)
> Use ycm-core for azure build

- ycmd/tests/java/diagnostics_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1272)
> [READY] Make tests less flaky: join poll thread

- ycmd/tests/java/diagnostics_test.py
Wait longer and ensure we exit the thread even if there's an exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1273)
> [READY] Java test still flaky

- README.md
- ycmd/completers/cpp/clang_completer.py
- ycmd/completers/cpp/clangd_completer.py
- ycmd/completers/cpp/flags.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/simple_language_server_completer.py
- ycmd/completers/python/python_completer.py
- ycmd/tests/clang/flags_test.py
- ycmd/tests/clangd/debug_info_test.py
- ycmd/tests/clangd/get_completions_test.py
- ycmd/tests/clangd/server_management_test.py
- ycmd/tests/clangd/testdata/extra_conf/.ycm_extra_conf.py
- ycmd/tests/clangd/testdata/extra_conf/bar.cpp
- ycmd/tests/clangd/testdata/extra_conf/foo.cpp
- ycmd/tests/clangd/testdata/extra_conf/global_extra_conf.py
- ycmd/tests/clangd/testdata/extra_conf/include/foo.h
- ycmd/tests/clangd/testdata/extra_conf/subdir/include/bar.h
- ycmd/tests/java/diagnostics_test.py
Rebased and fixed up @micbou's PR #1250 
I have been using this for some time and it works well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/valloric/ycmd/1267)
> [READY] Add extra conf support to Clangd completer

- ycmd/default_settings.json
- ycmd/tests/go/go_module/td/test.go
I forgot to remove gocode and godef options when I submitted the gopls pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1277)
> [READY] Remove old references to gocode and godef

- .gitmodules
Fixes #1280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1286)
> [READY] Change go tools URL to github

- ycmd/completers/rust/rust_completer.py
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/rust/testdata/formatting/src/main.rs
RLS actually supports `codeAction`s and this PR implements support for RLS `FixIt`s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1284)
> [READY] FixIt support for RLS

- azure/linux/install_dependencies.sh
This should fix CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1314)
> Use openssl 1.0 as python 2.7.1 does not compile with 1.1

- ycmd/completers/go/go_completer.py
- ycmd/tests/go/__init__.py
- ycmd/tests/go/diagnostics_test.py
- ycmd/tests/go/get_completions_test.py
- ycmd/tests/go/subcommands_test.py
Significant changes:
- Rename support
- References support
- Single file outside `$GOPATH` or a go module support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1301)
> [READY] Update go completer

- .gitignore
For obvious reasons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1321)
> [READY] Ignore clangd index output

- README.md
change valloric to ycm-core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1322)
> [READY] Update URLs in README for ycm-core

- ycmd/completers/language_server/language_server_completer.py
This just makes it easier to find and add stuff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1319)
> [READY] NFC: SignatureHelp: Sort subcommands map

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1335)
> [READY] Update jdt.ls to snapshot 45

- build.py
Should be "analysis on" instead of "analysison"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1342)
> Fix typo in argument help

- ycmd/tests/go/go_module/td/signature_help.go
- ycmd/tests/go/signature_help_test.py
Just tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1346)
> Go: Implement and test signature help

- build.py
#1316 forgot to update `check_sum`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1349)
> fix check_sum

- ycmd/completers/completer.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/typescript/signature_help_test.py
- ycmd/tests/typescript/testdata/signatures.ts
This adds signature help to typescript completer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1352)
> [READY] Signature help: Tyepscript

- ycmd/completers/java/java_completer.py
- ycmd/completers/language_server/simple_language_server_completer.py
- ycmd/tests/java/debug_info_test.py
- ycmd/tests/java/testdata/extra_confs/.ycm_extra_conf.py
Again no tests because no behavioral changes were made. All tests are passing locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1356)
> [READY] Make JavaCompleter inherit from SimpleLSPCompleter

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/get_completions_test.py
- ycmd/tests/cs/signature_help_test.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/cs/testdata/testy/ContinuousTest.cs
- ycmd/tests/cs/testdata/testy/FixItTestCase.cs
This PR adds RefactorRename and FixIt subcommands, as well as signature help to the C# completer.
WIP because signature help needs better testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1357)
> [READY] Roslyn update

- build.py
Fixes #1392 
Closes #1391 
I think this would be a cleaner solution than the one proposed in #1391.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1394)
> [READY] Fix IndexError in build.py script

- README.md
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/cs/hook.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/hook.py
- ycmd/completers/rust/hook.py
- ycmd/completers/rust/rust_completer.py
- ycmd/completers/typescript/hook.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/completers/typescriptreact/hook.py
- ycmd/default_settings.json
- ycmd/tests/cs/debug_info_test.py
- ycmd/tests/go/go_completer_test.py
- ycmd/tests/rust/debug_info_test.py
- ycmd/tests/rust/rust_completer_test.py
- ycmd/tests/typescript/typescript_completer_test.py
- ycmd/tests/utils_test.py
- ycmd/utils.py
Closes https://github.com/ycm-core/ycmd/issues/1289
JDT is intentionally left out for the sake of complexity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1395)
> [READY] Allow users to specify paths to external executables

- azure-pipelines.yml
- valgrind.suppressions
Let's see if this works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1410)
> [READY] Make azure triggers explicit

- ycmd/tests/java/server_management_test.py
Let's see what happens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1416)
> [READY] Don't use a clean workspace for WipeWorkspace testing

- .gitmodules
- .ycm_extra_conf.py
- benchmark.py
- build.py
- run_tests.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/server_utils.py
- ycmd/tests/language_server/__init__.py
- ycmd/tests/language_server/language_server_completer_test.py
Marked WIP because it prevents shutdown on macOS and I have no way of debugging that.
There are a few concerns that are worth discussing
- Client should just know which files need to be watched.
- F... fiiine...
- "Watching for changes" should be interpreted as "watching for create, modify *and* delete events"
- That's doable, but why the f\*\*\* wasn't that made clear?
- It watches a whole directory and leaves up to the event handler which files are actually processed (filtered with a glob pattern).
- I'm worried about slow IO metadata, and a limit on the number of open file descriptors.
- It can watch directories recursively.
- This makes the above concern even greater.
- There might be a better "observer", but I haven't found it.
- Documentation: …
> [READY] Add support for didChangeWatchedFiles LSP notification

- .gitignore
Makes otherwise, marked as untracked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1426)
> Ignore go installation directory

- docs/index.html
- docs/openapi.yml
- ycmd/completers/completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/tests/java/debug_info_test.py
- ycmd/tests/language_server/language_server_completer_test.py
Seems like we will eventually need to send `didSave` notification to LSP servers. This PR implements that part of the protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1428)
> [READY] Implement FileSave event, needed for didSave LSP capability

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/language_server/language_server_completer_test.py
Fixes #1433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1434)
> [READY] Do not return False from the message poll attempting to start the server

- azure/windows/install_dependencies.bat
- build.py
- ycmd/tests/go/get_completions_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1436)
> [READY] Upgrade gopls to version 0.4.1

- .gitmodules
f666d38fbbfdc3a5c585cb97596ef954a91763ec
https://github.com/maralla/pack/issues/47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1440)
> Delete third_party/go/src/golang.org/x/tools from .gitmodules

- examples/.ycm_extra_conf.py
Update examples/.ycm_extra_conf.py to replace FlagsForFile with Settings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1439)
> Update .ycm_extra_conf.py in examples to drop FlagsForFile

- build.py
- ycmd/tests/cs/conftest.py
- ycmd/tests/cs/diagnostics_test.py
- ycmd/tests/cs/get_completions_test.py
- ycmd/tests/cs/subcommands_test.py
- ycmd/tests/cs/testdata/testy/DiagnosticRange.cs
- ycmd/tests/cs/testdata/testy/FixItTestCase.cs
- ycmd/tests/cs/testdata/testy/MaxDiagnostics.cs
The "wait for diagnostics, to know that server is actually actually ready" trick is not reliable at all now, especially on linux. That meant that I had to think of something else. Details in the review.
Ping: @mispencer @sverbist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1443)
> [READY] Update Roslyn to v1.35.3

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/subcommands_test.py
This should fix https://github.com/ycm-core/YouCompleteMe/issues/3665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1444)
> [READY] Gracefully handle invalid Jedi definitions

- build.py
- ycmd/tests/go/subcommands_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1449)
> Upgrade gopls to verion 0.4.2

- build.py
- ycmd/tests/go/get_completions_test.py
- ycmd/tests/go/subcommands_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1460)
> Update to gopls 0.4.4

- ycmd/completers/completer_utils.py
- ycmd/completers/javascriptreact/hook.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/tests/javascriptreact/__init__.py
- ycmd/tests/javascriptreact/conftest.py
- ycmd/tests/javascriptreact/get_completions_test.py
- ycmd/tests/javascriptreact/subcommands_test.py
- ycmd/tests/javascriptreact/testdata/jsconfig.json
- ycmd/tests/javascriptreact/testdata/test.jsx
Looks like this weird thing can actually work. WIP because I haven't written any tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1462)
> [READY] Add javascriptreact support

- ycmd/completers/language_server/language_server_completer.py
This is the first experiment trying to fix #1458.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1476)
> [READY] Resolve a possible deadlock in LSP poll thread

- build.py
Before (with `--quiet`):
> Installing RLS for Rust support...OK
Now:
> Installing rust-analyzer for Rust support...OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1477)
> [READY] build.py - replace RLS references with rust-analyzer

- .gitignore
- .ycm_extra_conf.py
- build.py
- run_tests.py
- update_unicode.py
- ycmd/server_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1493)
> [READY] Clean up regex module's build directory

- ycmd/completers/language_server/language_server_completer.py
Fixes #1497
No tests, because we currently have no server that would hit this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1498)
> [READY] Assume ERROR when LSP server does not specify diagnostic severity

- .gitmodules
- test_requirements.txt
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/hmac_plugin.py
- ycmd/tests/tern/subcommands_test.py
Turns out we can ditch requests pretty easily. I've left requests in our test suite, but that can be changed easily as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1507)
> [READY] Drop the dependency on requests

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1510)
> [READY] Update gopls to v0.5.4

- build.py
https://github.com/golang/tools/releases/tag/gopls/v0.6.0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1514)
> Update gopls to v0.6.0

- README.md
- benchmark.py
- codecov.yml
Fixes #1499
Just a minor makeover. The codecov.yml change should explain to codecov not to create comments before it receives the entire data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1516)
> [READY] Update README and codecov.yml

- build.py
- update_clang.py
- update_omnisharp.py
- update_unicode.py
- ycmd/completers/cs/cs_completer.py
- ycmd/completers/javascript/tern_completer.py
As discussed yesterday, this stops ycmd from leaking all those socket handles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1520)
> [READY] Call close() on urllib socket handles after use

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1530)
> Update gopls to v0.6.4

- build.py
- cpp/ycm/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1548)
> [READY] Move libclang and clangd archives to github.com/ycm-core/llvm

- ycmd/completers/language_server/language_server_completer.py
- ycmd/tests/java/debug_info_test.py
If an unexpected exception happens during `_ServerToClientRequest`, we
used to erroneously close the connection with the server.
This can happen with gopls, as it tells us to just "watch everything"
which can hit the user's limit on the number of open files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1547)
> [READY] Catch exceptions and reject server-to-client requests

- .gitignore
- .ycm_extra_conf.py
- cpp/CMakeLists.txt
- cpp/ycm/CMakeLists.txt
- cpp/ycm/CandidateRepository.h
- cpp/ycm/CharacterRepository.h
- cpp/ycm/CodePointRepository.h
- cpp/ycm/IdentifierDatabase.cpp
- cpp/ycm/IdentifierDatabase.h
Here we replace standard associative containers with Abseil's "Swiss tables". It provides a massive performance improvement, but it takes a while to compile. Similar question as for parallel algorithms/TBB: Should it be opt-in? Opt-out?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1546)
> [READY] Use abseil hash tables

- azure/run_tests.sh
- azure/windows/run_tests.bat
- run_tests.py
- test_requirements.txt
Tests are grouped by module for test functions and by class for test methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1549)
> [READY] Execute python tests in separate processes.

- run_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1551)
> [READY] Allow individual test executions

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1556)
> Modified build.py to add support for MSYS2

- ycmd/handlers.py
With waitress gone, the wsgi server already logs all requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1555)
> [ReADY] Trim request logging

- build.py
This reverts commit 2fb2038ed05a7c7071fa54bad309961cf2d4059e, reversing
changes made to b7986d4d0b102287e4ef832591d731c0be33e26b.
This PR was accidentally merged by the bot.
A follow up was created, but @bstaletic makes the point that this should really work from the top level (YCM) area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1567)
> Revert "Merge pull request #1559 from AP2008/try-submodule-update"

- build.py
- ycmd/completers/completer.py
- ycmd/completers/language_server/language_server_completer.py
I'm lazy, so a single PR.
First commit discourages `sudo ./build.py`.
Second commit fixes a typo in `def Langauge()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1575)
> [READY] Two minor fixes

- third_party/tsserver/package.json
- ycmd/completers/typescript/typescript_completer.py
As mentioned in #1579, this PR pulls the update for typescript and gopls to a new PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1580)
> [READY] Upgrade TSServer and gopls

- build.py
- ycmd/tests/go/diagnostics_test.py
Hopefully, this time CI will actually install the new version of gopls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1589)
> [READY] Upgrade gopls to 0.7.1

- build.py
Addresses https://github.com/ycm-core/YouCompleteMe/issues/3944
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1595)
> [READY] Unset _JAVA_OPTIONS while checking for java version

- ycmd/completers/cs/cs_completer.py
- ycmd/tests/cs/subcommands_test.py
Let's see how well this goes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1601)
> [READY] Upgrade Omnisharp-Roslyn and add OgranizeImports subcommand

- build.py
- cpp/ycm/CMakeLists.txt
@puremourning Thanks for noticing my error and helping with figuring this out.
If we set out to do the M1 cross-compiling quickly, we may delay this PR. Also, please test the new archives on your side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1611)
> [READY] Update checksums after having fixed ARM archives in ycm-core/llvm

- build.py
- ycmd/tests/cs/testdata/testy/testy.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1610)
> [READY] Upgrade to newer Omnisharp

- .github/workflows/ci.yml
Otherwise it populates the cache with nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1614)
> [READY] Don't cache libclang on benchmark runs

- .mergify.yml
https://blog.mergify.com/strict-mode-deprecation/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1625)
> Switch to mergify queues

- build.py
Closes #1619 
Closes #1628 
Closes #1596
This Is the same solution I use in vimspector. Tested with latest go:
```
ben@BenMBP2021 ycmd % ./build.py --skip-build --go-completer
Building gopls for go completion...OK
```
And in ubuntu 20.04:
```
vagrant@vagrant:~/.vim/bundle/YouCompleteMe-Clean/third_party/ycmd$ ./build.py --skip-build --go-completer
Building gopls for go completion...can't load package: package golang.org/x/tools/gopls@v0.7.1: can only use path@version syntax with 'go get'
FAILED
Trying legacy get get...OK
OK
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1629)
> [READY] Try to go install, if that fails, go get

- ycmd/completers/completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/handlers.py
- ycmd/responses.py
- ycmd/tests/clangd/semantic_highlighting_test.py
- ycmd/tests/go/semantic_highlighting_test.py
- ycmd/tests/python/semantic_highlighting_test.py
We decode the strange LSP protocol in ycmd and send a simple one to the client. This might use more data, but means the client code is simpler too, where it probably matters more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1643)
> Support for semantic highlighting (experimental)

- cpp/pybind11/pybind11/attr.h
- cpp/pybind11/pybind11/buffer_info.h
- cpp/pybind11/pybind11/cast.h
- cpp/pybind11/pybind11/chrono.h
- cpp/pybind11/pybind11/complex.h
- cpp/pybind11/pybind11/detail/class.h
- cpp/pybind11/pybind11/detail/common.h
- cpp/pybind11/pybind11/detail/descr.h
- cpp/pybind11/pybind11/detail/init.h
- cpp/pybind11/pybind11/detail/internals.h
- cpp/pybind11/pybind11/detail/type_caster_base.h
- cpp/pybind11/pybind11/detail/typeid.h
- cpp/pybind11/pybind11/eigen.h
- cpp/pybind11/pybind11/embed.h
- cpp/pybind11/pybind11/eval.h
- cpp/pybind11/pybind11/functional.h
- cpp/pybind11/pybind11/gil.h
- cpp/pybind11/pybind11/iostream.h
- cpp/pybind11/pybind11/numpy.h
- cpp/pybind11/pybind11/operators.h
- cpp/pybind11/pybind11/options.h
- cpp/pybind11/pybind11/pybind11.h
- cpp/pybind11/pybind11/pytypes.h
- cpp/pybind11/pybind11/stl.h
- cpp/pybind11/pybind11/stl/filesystem.h
- cpp/pybind11/pybind11/stl_bind.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1647)
> Update pybind11 to 2.9.2

- ycmd/completers/python/python_completer.py
- ycmd/tests/python/subcommands_test.py
I didn't understand why adding the Refactor Inline would be inconsistent and it seemed to me that using the [extract_variable](https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Script.extract_variable) and extract_function without additional arguments is easy to implement exactly like Refactor Rename, and the arguments **until_line** and **until_column** are used in visual block mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1640)
> Add more Refactor* subcommands for python

- build.py
- docs/index.html
- docs/openapi.yml
- third_party/tsserver/package.json
- ycmd/completers/completer.py
- ycmd/completers/go/go_completer.py
- ycmd/completers/javascript/hook.py
- ycmd/completers/javascript/tern_completer.py
- ycmd/completers/language_server/language_server_completer.py
- ycmd/completers/language_server/language_server_protocol.py
- ycmd/completers/typescript/typescript_completer.py
- ycmd/handlers.py
- ycmd/responses.py
- ycmd/tests/go/debug_info_test.py
- ycmd/tests/go/semantic_highlighting_test.py
- ycmd/tests/go/subcommands_test.py
- ycmd/tests/javascript/__init__.py
- ycmd/tests/javascript/get_completions_test.py
- ycmd/tests/javascript/subcommands_test.py
- ycmd/tests/javascript/testdata/imports.js
- ycmd/tests/rust/subcommands_test.py
- ycmd/tests/test_utils.py
- ycmd/tests/typescript/get_completions_test.py
- ycmd/tests/typescript/subcommands_test.py
- ycmd/tests/typescript/testdata/imports.ts
This is the bare minimum, just forawrding the LSP response, with a few
fixups for ycmd/LSP differences.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1651)
* we use a cut-down version of the LSP spec (which is over specified for our uses)
* we update the docs
* we update all the servers to version that support it
* manual implementation for typescript, but it's essentially the LSP spec under the hood.
* add a setting to disable tern, as this is helpful for testing and where you have a mix of projects.
* had to hack go completer due to upstream bug in atlas usage
> Inlay hints

- cpp/ycm/CodePoint.cpp
- cpp/ycm/CodePoint.h
See: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1653)
> Fix build on gcc-13

- ycmd/tests/python/subcommands_test.py
Fixes https://github.com/ycm-core/YouCompleteMe/issues/4056
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1657)
> Update third-party dependencies to latest

- .github/workflows/ci.yml
- README.md
- build.py
- examples/example_client.py
- ycmd/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1668)
> Python 3.10 is now required

- .github/workflows/ci.yml
Thanks to @gdams
Equivalent of https://github.com/ycm-core/YouCompleteMe/pull/4102
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1669)
> Adopt is now temurin

- .github/workflows/ci.yml
- README.md
- build.py
- examples/example_client.py
- ycmd/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1671)
> Actually, just require 3.8 for now

- ycmd/completers/java/java_completer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1698)
> Add support for Gradle project that uses Gradle Kotlin DSL

- ycmd/completers/cs/cs_completer.py
Handle off-by-one error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1699)
> C# - Handle invalid line number better

- build.py
- third_party/tern_runtime/package.json
- third_party/tsserver/package.json
No tests were harmed during the making of this pull request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1703)
> Upgrade gopls, tsserver, tern and rust-analyzer

- .github/workflows/ci.yml
Let's see how lucky we are.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1702)
> Optimistically update all actions

- .github/workflows/ci.yml
This should shut GHA up for real this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1708)
> Fix GHA warnings

- ycmd/completers/go/go_completer.py
I have given it a very brief test and it seems to work.
@puremourning please give it a shot as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1706)
> Clean up a gopls hack

- build.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1717)
> Upgrade gopls to 0.14.0

- ycmd/tests/clangd/inlay_hints_test.py
- ycmd/tests/clangd/testdata/inlay_hints_basic.cpp
- ycmd/tests/clangd/testdata/inlay_hints_multiple.cpp
- ycmd/tests/go/inlay_hints_test.py
- ycmd/tests/rust/inlay_hints_test.py
Just a few basic tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1739)
> [READY] Add inlay hints tests

- ycmd/completers/language_server/language_server_completer.py
As discussed on gitter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1742)
> [READY] Pass the project root as one of the workspaces to LSP servers

- build.py
- third_party/tsserver/package.json
- ycmd/tests/java/subcommands_test.py
- ycmd/tests/rust/diagnostics_test.py
- ycmd/tests/typescript/diagnostics_test.py
- JDT v1.35.0
- R-A 2024-06-11
- TSServer 5.4.5
- Gopls 0.15.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ycm-core/ycmd/1745)
> [READY] Upgrade completers
